# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    class AuthPersonalAccessTokenRequest
      include Ovh::Api::Serializable
      include Ovh::Api::Validations

      attribute :description,
        type: 'String',
        json_key: 'description',
        required: true

      attribute :expires_at,
        type: 'Time',
        json_key: 'expiresAt',
        required: false

      attribute :expires_in,
        type: 'Integer',
        json_key: 'expiresIn',
        required: false

      attribute :name,
        type: 'String',
        json_key: 'name',
        required: true

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
