# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    class AuthApiCredential
      include Ovh::Api::Serializable
      include Ovh::Api::Validations

      attribute :allowed_ips,
        type: 'Array<String>',
        json_key: 'allowedIPs',
        required: false

      attribute :application_id,
        type: 'Integer',
        json_key: 'applicationId',
        required: false

      attribute :creation,
        type: 'Time',
        json_key: 'creation',
        required: false

      attribute :credential_id,
        type: 'Integer',
        json_key: 'credentialId',
        required: false

      attribute :expiration,
        type: 'Time',
        json_key: 'expiration',
        required: false

      attribute :last_use,
        type: 'Time',
        json_key: 'lastUse',
        required: false

      attribute :ovh_support,
        type: 'Boolean',
        json_key: 'ovhSupport',
        required: false

      attribute :rules,
        type: 'Array<AuthAccessRule>',
        json_key: 'rules',
        required: false

      attribute :status,
        type: 'AuthCredentialStateEnum',
        json_key: 'status',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
