# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    module AuthHTTPMethodEnum
      DELETE = 'DELETE'
      GET = 'GET'
      PATCH = 'PATCH'
      POST = 'POST'
      PUT = 'PUT'

      def self.all
        @all ||= [
          DELETE,
          GET,
          PATCH,
          POST,
          PUT,
        ].freeze
      end

      def self.valid?(value)
        all.include?(value)
      end
    end
  end
end
