# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    module AuthUserStatusEnum
      DISABLED = 'DISABLED'
      OK = 'OK'
      PASSWORD_CHANGE_REQUIRED = 'PASSWORD_CHANGE_REQUIRED'

      def self.all
        @all ||= [
          DISABLED,
          OK,
          PASSWORD_CHANGE_REQUIRED,
        ].freeze
      end

      def self.valid?(value)
        all.include?(value)
      end
    end
  end
end
