# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    module BillingOrderRetractionReasonEnum
      COMPETITOR = 'competitor'
      DIFFICULTY = 'difficulty'
      EXPENSIVE = 'expensive'
      OTHER = 'other'
      PERFORMANCE = 'performance'
      RELIABILITY = 'reliability'
      UNUSED = 'unused'

      def self.all
        @all ||= [
          COMPETITOR,
          DIFFICULTY,
          EXPENSIVE,
          OTHER,
          PERFORMANCE,
          RELIABILITY,
          UNUSED,
        ].freeze
      end

      def self.valid?(value)
        all.include?(value)
      end
    end
  end
end
