# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    module BillingReusablePaymentMeanEnum
      CREDIT_CARD = 'CREDIT_CARD'
      CURRENT_ACCOUNT = 'CURRENT_ACCOUNT'
      DEFERRED_PAYMENT_ACCOUNT = 'DEFERRED_PAYMENT_ACCOUNT'
      DOMESTIC_CARD = 'DOMESTIC_CARD'
      ENTERPRISE = 'ENTERPRISE'
      INTERNAL_TRUSTED_ACCOUNT = 'INTERNAL_TRUSTED_ACCOUNT'
      PAYPAL = 'PAYPAL'
      RUPAY = 'RUPAY'
      SEPA_DIRECT_DEBIT = 'SEPA_DIRECT_DEBIT'
      BANK_ACCOUNT = 'bankAccount'
      CREDIT_CARD2 = 'creditCard'
      DEFERRED_PAYMENT_ACCOUNT2 = 'deferredPaymentAccount'
      FIDELITY_ACCOUNT = 'fidelityAccount'
      OVH_ACCOUNT = 'ovhAccount'
      PAYPAL2 = 'paypal'

      def self.all
        @all ||= [
          CREDIT_CARD,
          CURRENT_ACCOUNT,
          DEFERRED_PAYMENT_ACCOUNT,
          DOMESTIC_CARD,
          ENTERPRISE,
          INTERNAL_TRUSTED_ACCOUNT,
          PAYPAL,
          RUPAY,
          SEPA_DIRECT_DEBIT,
          BANK_ACCOUNT,
          CREDIT_CARD2,
          DEFERRED_PAYMENT_ACCOUNT2,
          FIDELITY_ACCOUNT,
          OVH_ACCOUNT,
          PAYPAL2,
        ].freeze
      end

      def self.valid?(value)
        all.include?(value)
      end
    end
  end
end
