# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    module CdnOptionTypeEnum
      BROTLI = 'brotli'
      CACHE_RULE = 'cache_rule'
      CORS = 'cors'
      DEVMODE = 'devmode'
      GEO_HEADERS = 'geo_headers'
      HSTS = 'hsts'
      HTTPS_REDIRECT = 'https_redirect'
      MIXED_CONTENT = 'mixed_content'
      MOBILE_REDIRECT = 'mobile_redirect'
      PREFETCH = 'prefetch'
      PREWARM = 'prewarm'
      QUERYSTRING = 'querystring'
      WAF = 'waf'

      def self.all
        @all ||= [
          BROTLI,
          CACHE_RULE,
          CORS,
          DEVMODE,
          GEO_HEADERS,
          HSTS,
          HTTPS_REDIRECT,
          MIXED_CONTENT,
          MOBILE_REDIRECT,
          PREFETCH,
          PREWARM,
          QUERYSTRING,
          WAF,
        ].freeze
      end

      def self.valid?(value)
        all.include?(value)
      end
    end
  end
end
