# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    module CdnanycastCacheRuleStatusEnum
      CREATING = 'creating'
      DELETING = 'deleting'
      ERROR = 'error'
      OFF = 'off'
      ON = 'on'
      UPDATING = 'updating'

      def self.all
        @all ||= [
          CREATING,
          DELETING,
          ERROR,
          OFF,
          ON,
          UPDATING,
        ].freeze
      end

      def self.valid?(value)
        all.include?(value)
      end
    end
  end
end
