# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    module CdnanycastOrderCacheRuleEnum
      N100 = '100'
      N1000 = '1000'

      def self.all
        @all ||= [
          N100,
          N1000,
        ].freeze
      end

      def self.valid?(value)
        all.include?(value)
      end
    end
  end
end
