# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    class CloudProjectDatabaseMysqlMigration
      include Ovh::Api::Serializable
      include Ovh::Api::Validations

      attribute :source_host,
        type: 'String',
        json_key: 'sourceHost',
        required: true

      attribute :source_password,
        type: 'String',
        json_key: 'sourcePassword',
        required: true

      attribute :source_port,
        type: 'Integer',
        json_key: 'sourcePort',
        required: true

      attribute :source_ssl,
        type: 'Boolean',
        json_key: 'sourceSsl',
        required: true

      attribute :source_username,
        type: 'String',
        json_key: 'sourceUsername',
        required: true

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
