# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    class CloudShareShareCreate
      include Ovh::Api::Serializable
      include Ovh::Api::Validations

      attribute :availability_zone,
        type: 'String',
        json_key: 'availabilityZone',
        required: false

      attribute :description,
        type: 'String',
        json_key: 'description',
        required: false

      attribute :name,
        type: 'String',
        json_key: 'name',
        required: false

      attribute :network_id,
        type: 'String',
        json_key: 'networkId',
        required: false

      attribute :share_network_id,
        type: 'String',
        json_key: 'shareNetworkId',
        required: false

      attribute :size,
        type: 'Integer',
        json_key: 'size',
        required: false

      attribute :snapshot_id,
        type: 'String',
        json_key: 'snapshotId',
        required: false

      attribute :subnet_id,
        type: 'String',
        json_key: 'subnetId',
        required: false

      attribute :type,
        type: 'CloudShareTypeEnum',
        json_key: 'type',
        required: true

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
