# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    class CloudProjectAiVolumeVolumeSource
      include Ovh::Api::Serializable
      include Ovh::Api::Validations

      attribute :data_store,
        type: 'CloudProjectAiVolumeDataStore',
        json_key: 'dataStore',
        required: false

      attribute :public_git,
        type: 'CloudProjectAiVolumePublicGit',
        json_key: 'publicGit',
        required: false

      attribute :public_swift,
        type: 'CloudProjectAiVolumePublicSwift',
        json_key: 'publicSwift',
        required: false

      attribute :standalone,
        type: 'CloudProjectAiVolumeStandalone',
        json_key: 'standalone',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
