# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    module CloudProjectLoadbalancerStatusEnum
      APPLYING = 'APPLYING'
      CREATED = 'CREATED'
      DELETING = 'DELETING'
      ERROR = 'ERROR'
      FROZEN = 'FROZEN'
      RUNNING = 'RUNNING'

      def self.all
        @all ||= [
          APPLYING,
          CREATED,
          DELETING,
          ERROR,
          FROZEN,
          RUNNING,
        ].freeze
      end

      def self.valid?(value)
        all.include?(value)
      end
    end
  end
end
