# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    module CloudLoadbalancingPoolProtocolEnum
      HTTP = 'http'
      HTTPS = 'https'
      PROXY = 'proxy'
      PROXY_V2 = 'proxyV2'
      SCTP = 'sctp'
      TCP = 'tcp'
      UDP = 'udp'

      def self.all
        @all ||= [
          HTTP,
          HTTPS,
          PROXY,
          PROXY_V2,
          SCTP,
          TCP,
          UDP,
        ].freeze
      end

      def self.valid?(value)
        all.include?(value)
      end
    end
  end
end
