# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    module CloudProjectLoadbalancerBackendBalancerAlgorithmEnum
      FIRST = 'first'
      LEASTCONN = 'leastconn'
      ROUNDROBIN = 'roundrobin'
      SOURCE = 'source'
      STATIC_RR = 'static-rr'

      def self.all
        @all ||= [
          FIRST,
          LEASTCONN,
          ROUNDROBIN,
          SOURCE,
          STATIC_RR,
        ].freeze
      end

      def self.valid?(value)
        all.include?(value)
      end
    end
  end
end
