# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    class CloudProjectAiVolumeDataStore
      include Ovh::Api::Serializable
      include Ovh::Api::Validations

      attribute :alias_,
        type: 'String',
        json_key: 'alias',
        required: true

      attribute :archive,
        type: 'String',
        json_key: 'archive',
        required: false

      attribute :container,
        type: 'String',
        json_key: 'container',
        required: true

      attribute :internal,
        type: 'Boolean',
        json_key: 'internal',
        required: false

      attribute :prefix,
        type: 'String',
        json_key: 'prefix',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
