# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    module CloudUserRoleEnum
      ADMINISTRATOR = 'administrator'
      AI_TRAINING_OPERATOR = 'ai_training_operator'
      AI_TRAINING_READ = 'ai_training_read'
      AUTHENTICATION = 'authentication'
      BACKUP_OPERATOR = 'backup_operator'
      COMPUTE_OPERATOR = 'compute_operator'
      IMAGE_OPERATOR = 'image_operator'
      INFRASTRUCTURE_SUPERVISOR = 'infrastructure_supervisor'
      KEY_MANAGER_OPERATOR = 'key-manager_operator'
      KEY_MANAGER_READ = 'key-manager_read'
      LOAD_BALANCER_OPERATOR = 'load-balancer_operator'
      NETWORK_OPERATOR = 'network_operator'
      NETWORK_SECURITY_OPERATOR = 'network_security_operator'
      OBJECTSTORE_OPERATOR = 'objectstore_operator'
      QUANTUM_OPERATOR = 'quantum_operator'
      QUANTUM_READER = 'quantum_reader'
      SHARE_OPERATOR = 'share_operator'
      VOLUME_OPERATOR = 'volume_operator'

      def self.all
        @all ||= [
          ADMINISTRATOR,
          AI_TRAINING_OPERATOR,
          AI_TRAINING_READ,
          AUTHENTICATION,
          BACKUP_OPERATOR,
          COMPUTE_OPERATOR,
          IMAGE_OPERATOR,
          INFRASTRUCTURE_SUPERVISOR,
          KEY_MANAGER_OPERATOR,
          KEY_MANAGER_READ,
          LOAD_BALANCER_OPERATOR,
          NETWORK_OPERATOR,
          NETWORK_SECURITY_OPERATOR,
          OBJECTSTORE_OPERATOR,
          QUANTUM_OPERATOR,
          QUANTUM_READER,
          SHARE_OPERATOR,
          VOLUME_OPERATOR,
        ].freeze
      end

      def self.valid?(value)
        all.include?(value)
      end
    end
  end
end
