# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    module CloudLoadbalancingL7PolicyActionEnum
      REDIRECT_PREFIX = 'redirectPrefix'
      REDIRECT_TO_POOL = 'redirectToPool'
      REDIRECT_TO_URL = 'redirectToURL'
      REJECT = 'reject'

      def self.all
        @all ||= [
          REDIRECT_PREFIX,
          REDIRECT_TO_POOL,
          REDIRECT_TO_URL,
          REJECT,
        ].freeze
      end

      def self.valid?(value)
        all.include?(value)
      end
    end
  end
end
