# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    class CloudProjectKubeOpenIdConnectUpdate
      include Ovh::Api::Serializable
      include Ovh::Api::Validations

      attribute :ca_content,
        type: 'String',
        json_key: 'caContent',
        required: false

      attribute :client_id,
        type: 'String',
        json_key: 'clientId',
        required: false

      attribute :groups_claim,
        type: 'Array<Object>',
        json_key: 'groupsClaim',
        required: false

      attribute :groups_prefix,
        type: 'String',
        json_key: 'groupsPrefix',
        required: false

      attribute :issuer_url,
        type: 'String',
        json_key: 'issuerUrl',
        required: false

      attribute :required_claim,
        type: 'Array<Object>',
        json_key: 'requiredClaim',
        required: false

      attribute :signing_algorithms,
        type: 'Array<CloudKubeOpenIdConnectSigningAlgorithmsEnum>',
        json_key: 'signingAlgorithms',
        required: false

      attribute :username_claim,
        type: 'String',
        json_key: 'usernameClaim',
        required: false

      attribute :username_prefix,
        type: 'String',
        json_key: 'usernamePrefix',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
