# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    module CloudKubeUpdateStrategyEnum
      LATEST_PATCH = 'LATEST_PATCH'
      NEXT_MINOR = 'NEXT_MINOR'

      def self.all
        @all ||= [
          LATEST_PATCH,
          NEXT_MINOR,
        ].freeze
      end

      def self.valid?(value)
        all.include?(value)
      end
    end
  end
end
