# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    module CloudAclTypeEnum
      READ_ONLY = 'readOnly'
      READ_WRITE = 'readWrite'

      def self.all
        @all ||= [
          READ_ONLY,
          READ_WRITE,
        ].freeze
      end

      def self.valid?(value)
        all.include?(value)
      end
    end
  end
end
