# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    class CloudProjectLoadbalancerFrontend
      include Ovh::Api::Serializable
      include Ovh::Api::Validations

      attribute :backends,
        type: 'Array<CloudProjectLoadbalancerBackendSelector>',
        json_key: 'backends',
        required: true

      attribute :mode,
        type: 'CloudProjectLoadbalancerFrontendModeEnum',
        json_key: 'mode',
        required: false

      attribute :name,
        type: 'String',
        json_key: 'name',
        required: true

      attribute :port,
        type: 'Integer',
        json_key: 'port',
        required: false

      attribute :port_ranges,
        type: 'Array<CloudProjectLoadbalancerPortRange>',
        json_key: 'portRanges',
        required: false

      attribute :ports,
        type: 'Array<Object>',
        json_key: 'ports',
        required: false

      attribute :tls,
        type: 'Boolean',
        json_key: 'tls',
        required: false

      attribute :whitelist,
        type: 'Array<String>',
        json_key: 'whitelist',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
