# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    class CloudProjectKubeNodePoolAutoscalingParams
      include Ovh::Api::Serializable
      include Ovh::Api::Validations

      attribute :scale_down_unneeded_time_seconds,
        type: 'Integer',
        json_key: 'scaleDownUnneededTimeSeconds',
        required: false

      attribute :scale_down_unready_time_seconds,
        type: 'Integer',
        json_key: 'scaleDownUnreadyTimeSeconds',
        required: false

      attribute :scale_down_utilization_threshold,
        type: 'Float',
        json_key: 'scaleDownUtilizationThreshold',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
