# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    class CloudNetworkCreateSubnetForGatewaySummary
      include Ovh::Api::Serializable
      include Ovh::Api::Validations

      attribute :allocation_pools,
        type: 'Array<CloudProjectAllocationPool>',
        json_key: 'allocationPools',
        required: false

      attribute :cidr,
        type: 'String',
        json_key: 'cidr',
        required: true

      attribute :dns_name_servers,
        type: 'Array<String>',
        json_key: 'dnsNameServers',
        required: false

      attribute :enable_dhcp,
        type: 'Boolean',
        json_key: 'enableDhcp',
        required: true

      attribute :gateway_ip,
        type: 'String',
        json_key: 'gatewayIp',
        required: false

      attribute :host_routes,
        type: 'Array<CloudNetworkHostRoute>',
        json_key: 'hostRoutes',
        required: false

      attribute :ip_version,
        type: 'Integer',
        json_key: 'ipVersion',
        required: true

      attribute :name,
        type: 'String',
        json_key: 'name',
        required: false

      attribute :use_default_public_dns_resolver,
        type: 'Boolean',
        json_key: 'useDefaultPublicDNSResolver',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
