# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    class CloudProjectAiNotebookNotebookWorkspaceBackupRetentionPH9799f5d8
      include Ovh::Api::Serializable
      include Ovh::Api::Validations

      attribute :lifetime_eviction_threshold,
        type: 'Integer',
        json_key: 'lifetimeEvictionThreshold',
        required: false

      attribute :lifetime_in_days,
        type: 'Integer',
        json_key: 'lifetimeInDays',
        required: false

      attribute :retained_number,
        type: 'Integer',
        json_key: 'retainedNumber',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
