# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    class CloudProjectAiVolumeVolume
      include Ovh::Api::Serializable
      include Ovh::Api::Validations

      attribute :cache,
        type: 'Boolean',
        json_key: 'cache',
        required: false

      attribute :container,
        type: 'String',
        json_key: 'container',
        required: false

      attribute :data_store,
        type: 'CloudProjectAiVolumeDataStore',
        json_key: 'dataStore',
        required: false

      attribute :id,
        type: 'String',
        json_key: 'id',
        required: false

      attribute :mount_path,
        type: 'String',
        json_key: 'mountPath',
        required: true

      attribute :permission,
        type: 'CloudProjectAiVolumePermissionEnum',
        json_key: 'permission',
        required: true

      attribute :prefix,
        type: 'String',
        json_key: 'prefix',
        required: false

      attribute :public_git,
        type: 'CloudProjectAiVolumePublicGit',
        json_key: 'publicGit',
        required: false

      attribute :public_swift,
        type: 'CloudProjectAiVolumePublicSwift',
        json_key: 'publicSwift',
        required: false

      attribute :region,
        type: 'String',
        json_key: 'region',
        required: false

      attribute :standalone,
        type: 'CloudProjectAiVolumeStandalone',
        json_key: 'standalone',
        required: false

      attribute :target_data_store,
        type: 'CloudProjectAiVolumeDataStore',
        json_key: 'targetDataStore',
        required: false

      attribute :volume_source,
        type: 'CloudProjectAiVolumeVolumeSource',
        json_key: 'volumeSource',
        required: false

      attribute :volume_target,
        type: 'CloudProjectAiVolumeVolumeTarget',
        json_key: 'volumeTarget',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
