# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    class CloudProjectAiAppUpdateInput
      include Ovh::Api::Serializable
      include Ovh::Api::Validations

      attribute :command,
        type: 'Array<Object>',
        json_key: 'command',
        required: false

      attribute :cpu,
        type: 'Integer',
        json_key: 'cpu',
        required: false

      attribute :default_http_port,
        type: 'Integer',
        json_key: 'defaultHttpPort',
        required: false

      attribute :deployment_strategy,
        type: 'CloudProjectAiAppDeploymentStrategy',
        json_key: 'deploymentStrategy',
        required: false

      attribute :env_vars,
        type: 'Array<CloudProjectAiEnv>',
        json_key: 'envVars',
        required: false

      attribute :flavor,
        type: 'String',
        json_key: 'flavor',
        required: false

      attribute :flavor_count,
        type: 'Integer',
        json_key: 'flavorCount',
        required: false

      attribute :gpu,
        type: 'Integer',
        json_key: 'gpu',
        required: false

      attribute :grpc_port,
        type: 'Integer',
        json_key: 'grpcPort',
        required: false

      attribute :liveness_probe,
        type: 'CloudProjectAiAppProbeInput',
        json_key: 'livenessProbe',
        required: false

      attribute :probe,
        type: 'CloudProjectAiAppProbeInput',
        json_key: 'probe',
        required: false

      attribute :url,
        type: 'String',
        json_key: 'url',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
