# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    module CloudLoadbalancingLoadBalancerProvisioningStatusEnum
      ACTIVE = 'active'
      CREATING = 'creating'
      DELETED = 'deleted'
      DELETING = 'deleting'
      ERROR = 'error'
      UPDATING = 'updating'

      def self.all
        @all ||= [
          ACTIVE,
          CREATING,
          DELETED,
          DELETING,
          ERROR,
          UPDATING,
        ].freeze
      end

      def self.valid?(value)
        all.include?(value)
      end
    end
  end
end
