# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    class CloudLoadbalancingHealthMonitorHTTPConfiguration
      include Ovh::Api::Serializable
      include Ovh::Api::Validations

      attribute :domain_name,
        type: 'String',
        json_key: 'domainName',
        required: false

      attribute :expected_codes,
        type: 'String',
        json_key: 'expectedCodes',
        required: false

      attribute :http_method,
        type: 'CloudLoadbalancingLoadBalancerHealthMonitorHTTPMethodEnum',
        json_key: 'httpMethod',
        required: true

      attribute :http_version,
        type: 'CloudLoadbalancingLoadBalancerHealthMonitorHTTPVersionEnum',
        json_key: 'httpVersion',
        required: false

      attribute :url_path,
        type: 'String',
        json_key: 'urlPath',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
