# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    class CloudLoadbalancingLoadbalancerCreateInputNetworkPrivate
      include Ovh::Api::Serializable
      include Ovh::Api::Validations

      attribute :floating_ip,
        type: 'CloudLoadbalancingLoadbalancerCreateInputNetworkPrivateHfdabf0eb',
        json_key: 'floatingIp',
        required: false

      attribute :floating_ip_create,
        type: 'CloudLoadbalancingLoadbalancerCreateInputNetworkPrivateHdadf6adb',
        json_key: 'floatingIpCreate',
        required: false

      attribute :gateway,
        type: 'CloudLoadbalancingLoadbalancerCreateInputNetworkPrivateGateway',
        json_key: 'gateway',
        required: false

      attribute :gateway_create,
        type: 'CloudLoadbalancingLoadbalancerCreateInputNetworkPrivateGH967fecfe',
        json_key: 'gatewayCreate',
        required: false

      attribute :network,
        type: 'CloudLoadbalancingLoadbalancerCreateInputNetworkPrivateNetwork',
        json_key: 'network',
        required: true

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
