# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    module CloudNetworkGatewayModelEnum
      N2XL = '2xl'
      N3XL = '3xl'
      L = 'l'
      M = 'm'
      S = 's'
      XL = 'xl'

      def self.all
        @all ||= [
          N2XL,
          N3XL,
          L,
          M,
          S,
          XL,
        ].freeze
      end

      def self.valid?(value)
        all.include?(value)
      end
    end
  end
end
