# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    class CloudProjectAiAppDeploymentStrategy
      include Ovh::Api::Serializable
      include Ovh::Api::Validations

      attribute :max_surge,
        type: 'String',
        json_key: 'maxSurge',
        required: false

      attribute :max_unavailable,
        type: 'String',
        json_key: 'maxUnavailable',
        required: false

      attribute :progress_deadline_seconds,
        type: 'Integer',
        json_key: 'progressDeadlineSeconds',
        required: false

      attribute :termination_grace_period_seconds,
        type: 'Integer',
        json_key: 'terminationGracePeriodSeconds',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
