# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    class CloudProjectUserCreation
      include Ovh::Api::Serializable
      include Ovh::Api::Validations

      attribute :description,
        type: 'String',
        json_key: 'description',
        required: false

      attribute :role,
        type: 'CloudUserRoleEnum',
        json_key: 'role',
        required: false

      attribute :roles,
        type: 'Array<CloudUserRoleEnum>',
        json_key: 'roles',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
