# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    class CloudLoadbalancingCreateListener
      include Ovh::Api::Serializable
      include Ovh::Api::Validations

      attribute :allowed_cidrs,
        type: 'Array<String>',
        json_key: 'allowedCidrs',
        required: false

      attribute :certificate_id,
        type: 'String',
        json_key: 'certificateId',
        required: false

      attribute :default_pool_id,
        type: 'String',
        json_key: 'defaultPoolId',
        required: false

      attribute :description,
        type: 'String',
        json_key: 'description',
        required: false

      attribute :loadbalancer_id,
        type: 'String',
        json_key: 'loadbalancerId',
        required: true

      attribute :name,
        type: 'String',
        json_key: 'name',
        required: true

      attribute :port,
        type: 'Integer',
        json_key: 'port',
        required: true

      attribute :protocol,
        type: 'CloudLoadbalancingListenerProtocolEnum',
        json_key: 'protocol',
        required: true

      attribute :timeout_client_data,
        type: 'Integer',
        json_key: 'timeoutClientData',
        required: false

      attribute :timeout_member_data,
        type: 'Integer',
        json_key: 'timeoutMemberData',
        required: false

      attribute :tls_versions,
        type: 'Array<CloudLoadbalancingListenerTlsVersionEnum>',
        json_key: 'tlsVersions',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
