# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    class CloudProjectLoadBalancer
      include Ovh::Api::Serializable
      include Ovh::Api::Validations

      attribute :address,
        type: 'CloudProjectLoadbalancerAddress',
        json_key: 'address',
        required: false

      attribute :configuration,
        type: 'CloudProjectLoadbalancerConfigurationVersion',
        json_key: 'configuration',
        required: false

      attribute :created_at,
        type: 'Time',
        json_key: 'createdAt',
        required: false

      attribute :description,
        type: 'String',
        json_key: 'description',
        required: false

      attribute :egress_address,
        type: 'CloudProjectLoadbalancerAddresses',
        json_key: 'egressAddress',
        required: false

      attribute :id,
        type: 'String',
        json_key: 'id',
        required: false

      attribute :name,
        type: 'String',
        json_key: 'name',
        required: false

      attribute :networking,
        type: 'CloudProjectLoadbalancerNetworkingNetworking',
        json_key: 'networking',
        required: false

      attribute :openstack_region,
        type: 'String',
        json_key: 'openstackRegion',
        required: false

      attribute :region,
        type: 'String',
        json_key: 'region',
        required: false

      attribute :size,
        type: 'CloudProjectLoadbalancerSizeEnum',
        json_key: 'size',
        required: false

      attribute :status,
        type: 'CloudProjectLoadbalancerStatusEnum',
        json_key: 'status',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
