# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    class CloudProjectKubeCreation
      include Ovh::Api::Serializable
      include Ovh::Api::Validations

      attribute :customization,
        type: 'CloudProjectKubeCustomization',
        json_key: 'customization',
        required: false

      attribute :ip_allocation_policy,
        type: 'CloudProjectKubeIpAllocationPolicy',
        json_key: 'ipAllocationPolicy',
        required: false

      attribute :kube_proxy_mode,
        type: 'CloudKubeKubeProxyModeEnum',
        json_key: 'kubeProxyMode',
        required: false

      attribute :load_balancers_subnet_id,
        type: 'String',
        json_key: 'loadBalancersSubnetId',
        required: false

      attribute :name,
        type: 'String',
        json_key: 'name',
        required: false

      attribute :nodepool,
        type: 'CloudProjectKubeCreationNodePool',
        json_key: 'nodepool',
        required: false

      attribute :nodepools,
        type: 'Array<CloudProjectKubeCreationNodePool>',
        json_key: 'nodepools',
        required: false

      attribute :nodes_subnet_id,
        type: 'String',
        json_key: 'nodesSubnetId',
        required: false

      attribute :plan,
        type: 'String',
        json_key: 'plan',
        required: false

      attribute :private_network_configuration,
        type: 'CloudKubePrivateNetworkConfiguration',
        json_key: 'privateNetworkConfiguration',
        required: false

      attribute :private_network_id,
        type: 'String',
        json_key: 'privateNetworkId',
        required: false

      attribute :region,
        type: 'String',
        json_key: 'region',
        required: true

      attribute :update_policy,
        type: 'CloudKubeUpdatePolicyEnum',
        json_key: 'updatePolicy',
        required: false

      attribute :version,
        type: 'CloudKubeVersionEnum',
        json_key: 'version',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
