# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    class CloudProjectDatabaseKafkaTopic
      include Ovh::Api::Serializable
      include Ovh::Api::Validations

      attribute :id,
        type: 'String',
        json_key: 'id',
        required: false

      attribute :min_insync_replicas,
        type: 'Integer',
        json_key: 'minInsyncReplicas',
        required: false

      attribute :name,
        type: 'String',
        json_key: 'name',
        required: false

      attribute :partitions,
        type: 'Integer',
        json_key: 'partitions',
        required: false

      attribute :replication,
        type: 'Integer',
        json_key: 'replication',
        required: false

      attribute :retention_bytes,
        type: 'Integer',
        json_key: 'retentionBytes',
        required: false

      attribute :retention_hours,
        type: 'Integer',
        json_key: 'retentionHours',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
