# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    module CloudKubeUpdatePolicyEnum
      ALWAYS_UPDATE = 'ALWAYS_UPDATE'
      MINIMAL_DOWNTIME = 'MINIMAL_DOWNTIME'
      NEVER_UPDATE = 'NEVER_UPDATE'

      def self.all
        @all ||= [
          ALWAYS_UPDATE,
          MINIMAL_DOWNTIME,
          NEVER_UPDATE,
        ].freeze
      end

      def self.valid?(value)
        all.include?(value)
      end
    end
  end
end
