# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    class CloudLoadbalancingUpdateHealthMonitor
      include Ovh::Api::Serializable
      include Ovh::Api::Validations

      attribute :delay,
        type: 'Integer',
        json_key: 'delay',
        required: false

      attribute :http_configuration,
        type: 'CloudLoadbalancingHealthMonitorHTTPConfiguration',
        json_key: 'httpConfiguration',
        required: false

      attribute :max_retries,
        type: 'Integer',
        json_key: 'maxRetries',
        required: false

      attribute :max_retries_down,
        type: 'Integer',
        json_key: 'maxRetriesDown',
        required: false

      attribute :name,
        type: 'String',
        json_key: 'name',
        required: false

      attribute :timeout,
        type: 'Integer',
        json_key: 'timeout',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
