# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    class CloudProjectAiResourcesInput
      include Ovh::Api::Serializable
      include Ovh::Api::Validations

      attribute :cpu,
        type: 'Integer',
        json_key: 'cpu',
        required: false

      attribute :ephemeral_storage,
        type: 'Integer',
        json_key: 'ephemeralStorage',
        required: false

      attribute :flavor,
        type: 'String',
        json_key: 'flavor',
        required: false

      attribute :flavor_count,
        type: 'Integer',
        json_key: 'flavorCount',
        required: false

      attribute :gpu,
        type: 'Integer',
        json_key: 'gpu',
        required: false

      attribute :gpu_brand,
        type: 'String',
        json_key: 'gpuBrand',
        required: false

      attribute :gpu_memory,
        type: 'Integer',
        json_key: 'gpuMemory',
        required: false

      attribute :gpu_model,
        type: 'String',
        json_key: 'gpuModel',
        required: false

      attribute :memory,
        type: 'Integer',
        json_key: 'memory',
        required: false

      attribute :private_network,
        type: 'Integer',
        json_key: 'privateNetwork',
        required: false

      attribute :public_network,
        type: 'Integer',
        json_key: 'publicNetwork',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
