# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    module CloudStorageStorageClassReplicationEnum
      DEEP_ARCHIVE = 'DEEP_ARCHIVE'
      GLACIER = 'GLACIER'
      GLACIER_IR = 'GLACIER_IR'
      HIGH_PERF = 'HIGH_PERF'
      INTELLIGENT_TIERING = 'INTELLIGENT_TIERING'
      ONEZONE_IA = 'ONEZONE_IA'
      STANDARD = 'STANDARD'
      STANDARD_IA = 'STANDARD_IA'

      def self.all
        @all ||= [
          DEEP_ARCHIVE,
          GLACIER,
          GLACIER_IR,
          HIGH_PERF,
          INTELLIGENT_TIERING,
          ONEZONE_IA,
          STANDARD,
          STANDARD_IA,
        ].freeze
      end

      def self.valid?(value)
        all.include?(value)
      end
    end
  end
end
