# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    class CloudProjectLoadbalancerConfigurationCreation
      include Ovh::Api::Serializable
      include Ovh::Api::Validations

      attribute :backends,
        type: 'Array<CloudProjectLoadbalancerBackend>',
        json_key: 'backends',
        required: false

      attribute :certificates,
        type: 'Array<Object>',
        json_key: 'certificates',
        required: false

      attribute :frontends,
        type: 'Array<CloudProjectLoadbalancerFrontend>',
        json_key: 'frontends',
        required: false

      attribute :networking,
        type: 'CloudProjectLoadbalancerConfigurationNetworkingNetworking',
        json_key: 'networking',
        required: false

      attribute :version,
        type: 'Integer',
        json_key: 'version',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
