# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    module CloudLoadbalancingListenerTlsVersionEnum
      SSLV3 = 'SSLv3'
      TLSV1 = 'TLSv1'
      TLSV1_1 = 'TLSv1.1'
      TLSV1_2 = 'TLSv1.2'
      TLSV1_3 = 'TLSv1.3'

      def self.all
        @all ||= [
          SSLV3,
          TLSV1,
          TLSV1_1,
          TLSV1_2,
          TLSV1_3,
        ].freeze
      end

      def self.valid?(value)
        all.include?(value)
      end
    end
  end
end
