# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    class CloudProjectDatabaseServiceUserWithRoles
      include Ovh::Api::Serializable
      include Ovh::Api::Validations

      attribute :created_at,
        type: 'Time',
        json_key: 'createdAt',
        required: false

      attribute :id,
        type: 'String',
        json_key: 'id',
        required: false

      attribute :roles,
        type: 'Array<Object>',
        json_key: 'roles',
        required: false

      attribute :status,
        type: 'CloudProjectDatabaseStatusEnum',
        json_key: 'status',
        required: false

      attribute :username,
        type: 'String',
        json_key: 'username',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
