# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    module CloudStorageEncryptionAlgorithmEnum
      AES256 = 'AES256'
      PLAINTEXT = 'plaintext'

      def self.all
        @all ||= [
          AES256,
          PLAINTEXT,
        ].freeze
      end

      def self.valid?(value)
        all.include?(value)
      end
    end
  end
end
