# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    class CloudKeymanagerCertificateCreate
      include Ovh::Api::Serializable
      include Ovh::Api::Validations

      attribute :certificate,
        type: 'String',
        json_key: 'certificate',
        required: true

      attribute :intermediates,
        type: 'String',
        json_key: 'intermediates',
        required: false

      attribute :name,
        type: 'String',
        json_key: 'name',
        required: true

      attribute :private_key,
        type: 'String',
        json_key: 'privateKey',
        required: true

      attribute :private_key_passphrase,
        type: 'String',
        json_key: 'privateKeyPassphrase',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
