# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    class CloudProjectAiDataStoreInput
      include Ovh::Api::Serializable
      include Ovh::Api::Validations

      attribute :alias_,
        type: 'String',
        json_key: 'alias',
        required: true

      attribute :credentials,
        type: 'CloudProjectAiDataStoreCredentialsInput',
        json_key: 'credentials',
        required: true

      attribute :endpoint,
        type: 'String',
        json_key: 'endpoint',
        required: true

      attribute :owner,
        type: 'CloudProjectAiDataStoreOwnerEnum',
        json_key: 'owner',
        required: true

      attribute :prefix,
        type: 'String',
        json_key: 'prefix',
        required: false

      attribute :type,
        type: 'CloudProjectAiDataStoreTypeEnum',
        json_key: 'type',
        required: true

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
