# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    class CloudProjectDatabaseServiceReplication
      include Ovh::Api::Serializable
      include Ovh::Api::Validations

      attribute :emit_heartbeats,
        type: 'Boolean',
        json_key: 'emitHeartbeats',
        required: false

      attribute :enabled,
        type: 'Boolean',
        json_key: 'enabled',
        required: true

      attribute :id,
        type: 'String',
        json_key: 'id',
        required: false

      attribute :replication_policy_class,
        type: 'CloudProjectDatabaseServiceReplicationPolicyClassEnum',
        json_key: 'replicationPolicyClass',
        required: false

      attribute :source_integration,
        type: 'String',
        json_key: 'sourceIntegration',
        required: false

      attribute :sync_group_offsets,
        type: 'Boolean',
        json_key: 'syncGroupOffsets',
        required: false

      attribute :sync_interval,
        type: 'Integer',
        json_key: 'syncInterval',
        required: false

      attribute :target_integration,
        type: 'String',
        json_key: 'targetIntegration',
        required: false

      attribute :topic_exclude_list,
        type: 'Array<Object>',
        json_key: 'topicExcludeList',
        required: false

      attribute :topics,
        type: 'Array<Object>',
        json_key: 'topics',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
