# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    module CloudVolumeVolumeTypeEnum
      CLASSIC = 'classic'
      CLASSIC_LUKS = 'classic-luks'
      CLASSIC_MULTIATTACH = 'classic-multiattach'
      HIGH_SPEED = 'high-speed'
      HIGH_SPEED_GEN2 = 'high-speed-gen2'
      HIGH_SPEED_GEN2_LUKS = 'high-speed-gen2-luks'
      HIGH_SPEED_LUKS = 'high-speed-luks'

      def self.all
        @all ||= [
          CLASSIC,
          CLASSIC_LUKS,
          CLASSIC_MULTIATTACH,
          HIGH_SPEED,
          HIGH_SPEED_GEN2,
          HIGH_SPEED_GEN2_LUKS,
          HIGH_SPEED_LUKS,
        ].freeze
      end

      def self.valid?(value)
        all.include?(value)
      end
    end
  end
end
