# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    class CloudProjectAiAppScalingAutomaticStrategyInput
      include Ovh::Api::Serializable
      include Ovh::Api::Validations

      attribute :average_usage_target,
        type: 'Integer',
        json_key: 'averageUsageTarget',
        required: false

      attribute :cooldown_period_seconds,
        type: 'Integer',
        json_key: 'cooldownPeriodSeconds',
        required: false

      attribute :custom_metrics,
        type: 'CloudProjectAiAppAutomaticScalingStrategyCustomMetricsInput',
        json_key: 'customMetrics',
        required: false

      attribute :replicas_max,
        type: 'Integer',
        json_key: 'replicasMax',
        required: false

      attribute :replicas_min,
        type: 'Integer',
        json_key: 'replicasMin',
        required: false

      attribute :resource_type,
        type: 'CloudProjectAiAppScalingAutomaticStrategyResourceTypeEnum',
        json_key: 'resourceType',
        required: false

      attribute :scale_down_stabilization_window_seconds,
        type: 'Integer',
        json_key: 'scaleDownStabilizationWindowSeconds',
        required: false

      attribute :scale_up_stabilization_window_seconds,
        type: 'Integer',
        json_key: 'scaleUpStabilizationWindowSeconds',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
