# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    class CloudProjectAiNotebookNotebookSpecInput
      include Ovh::Api::Serializable
      include Ovh::Api::Validations

      attribute :env,
        type: 'CloudProjectAiNotebookNotebookEnv',
        json_key: 'env',
        required: true

      attribute :env_vars,
        type: 'Array<CloudProjectAiJobJobEnv>',
        json_key: 'envVars',
        required: false

      attribute :labels,
        type: 'Hash<String, String>',
        json_key: 'labels',
        required: false

      attribute :name,
        type: 'String',
        json_key: 'name',
        required: false

      attribute :quantum_resources,
        type: 'CloudProjectQuantumQuantumResourcesInput',
        json_key: 'quantumResources',
        required: false

      attribute :region,
        type: 'String',
        json_key: 'region',
        required: true

      attribute :resources,
        type: 'CloudProjectAiResourcesInput',
        json_key: 'resources',
        required: true

      attribute :shutdown,
        type: 'CloudProjectAiShutdownStrategyEnum',
        json_key: 'shutdown',
        required: false

      attribute :ssh_public_keys,
        type: 'Array<Object>',
        json_key: 'sshPublicKeys',
        required: false

      attribute :timeout_auto_restart,
        type: 'Boolean',
        json_key: 'timeoutAutoRestart',
        required: false

      attribute :unsecure_http,
        type: 'Boolean',
        json_key: 'unsecureHttp',
        required: false

      attribute :volumes,
        type: 'Array<CloudProjectAiVolumeVolume>',
        json_key: 'volumes',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
