# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    class CloudProjectKubeNodePoolUpdate
      include Ovh::Api::Serializable
      include Ovh::Api::Validations

      attribute :attach_floating_ips,
        type: 'CloudProjectKubeNodePoolAttachFloatingIpsParams',
        json_key: 'attachFloatingIps',
        required: false

      attribute :autoscale,
        type: 'Boolean',
        json_key: 'autoscale',
        required: false

      attribute :autoscaling,
        type: 'CloudProjectKubeNodePoolAutoscalingParams',
        json_key: 'autoscaling',
        required: false

      attribute :desired_nodes,
        type: 'Integer',
        json_key: 'desiredNodes',
        required: false

      attribute :max_nodes,
        type: 'Integer',
        json_key: 'maxNodes',
        required: false

      attribute :min_nodes,
        type: 'Integer',
        json_key: 'minNodes',
        required: false

      attribute :nodes_to_remove,
        type: 'Array<Object>',
        json_key: 'nodesToRemove',
        required: false

      attribute :template,
        type: 'CloudKubeNodePoolTemplate',
        json_key: 'template',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
