# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    class CloudInstanceCreateInput
      include Ovh::Api::Serializable
      include Ovh::Api::Validations

      attribute :autobackup,
        type: 'CloudInstanceAutoBackup',
        json_key: 'autobackup',
        required: false

      attribute :availability_zone,
        type: 'String',
        json_key: 'availabilityZone',
        required: false

      attribute :billing_period,
        type: 'CloudInstanceCreateInputBillingPeriodEnum',
        json_key: 'billingPeriod',
        required: true

      attribute :boot_from,
        type: 'CloudInstanceCreateInputBootFrom',
        json_key: 'bootFrom',
        required: true

      attribute :bulk,
        type: 'Integer',
        json_key: 'bulk',
        required: false

      attribute :flavor,
        type: 'CloudInstanceCreateInputFlavor',
        json_key: 'flavor',
        required: true

      attribute :group,
        type: 'CloudInstanceCreateInputGroup',
        json_key: 'group',
        required: false

      attribute :name,
        type: 'String',
        json_key: 'name',
        required: false

      attribute :network,
        type: 'CloudInstanceCreateInputNetwork',
        json_key: 'network',
        required: true

      attribute :ssh_key,
        type: 'CloudInstanceCreateInputSshKey',
        json_key: 'sshKey',
        required: false

      attribute :ssh_key_create,
        type: 'CloudInstanceCreateInputSshKeyCreate',
        json_key: 'sshKeyCreate',
        required: false

      attribute :user_data,
        type: 'String',
        json_key: 'userData',
        required: false

      attribute :volume,
        type: 'CloudInstanceCreateInputVolume',
        json_key: 'volume',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
