# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    module CloudProjectAiTokenRoleEnum
      AI_TRAINING_OPERATOR = 'ai_training_operator'
      AI_TRAINING_READ = 'ai_training_read'
      QUANTUM_OPERATOR = 'quantum_operator'
      QUANTUM_READER = 'quantum_reader'

      def self.all
        @all ||= [
          AI_TRAINING_OPERATOR,
          AI_TRAINING_READ,
          QUANTUM_OPERATOR,
          QUANTUM_READER,
        ].freeze
      end

      def self.valid?(value)
        all.include?(value)
      end
    end
  end
end
