# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    class CloudProjectDatabaseKafkaConnectConnector
      include Ovh::Api::Serializable
      include Ovh::Api::Validations

      attribute :configuration,
        type: 'Hash<String, String>',
        json_key: 'configuration',
        required: true

      attribute :connector_id,
        type: 'String',
        json_key: 'connectorId',
        required: false

      attribute :id,
        type: 'String',
        json_key: 'id',
        required: false

      attribute :name,
        type: 'String',
        json_key: 'name',
        required: false

      attribute :status,
        type: 'CloudProjectDatabaseKafkaConnectConnectorStatusEnum',
        json_key: 'status',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
