# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    class CloudStorageReplicationRuleIn
      include Ovh::Api::Serializable
      include Ovh::Api::Validations

      attribute :delete_marker_replication,
        type: 'CloudStorageReplicationRuleDeleteMarkerReplicationStatusEnum',
        json_key: 'deleteMarkerReplication',
        required: false

      attribute :destination,
        type: 'CloudStorageReplicationRuleDestinationIn',
        json_key: 'destination',
        required: false

      attribute :filter,
        type: 'CloudStorageReplicationRuleFilter',
        json_key: 'filter',
        required: false

      attribute :id,
        type: 'String',
        json_key: 'id',
        required: false

      attribute :priority,
        type: 'Integer',
        json_key: 'priority',
        required: false

      attribute :status,
        type: 'CloudStorageReplicationRuleStatusEnum',
        json_key: 'status',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
