# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    module ClusterHadoopClusterServiceNameEnum
      H_BASE = 'HBase'
      HDFS = 'HDFS'
      HUE = 'HUE'
      HIVE = 'Hive'
      OOZIE = 'Oozie'
      SOLR = 'Solr'
      SPARK = 'Spark'
      SQOOP = 'Sqoop'
      YARN = 'YARN'
      ZOO_KEEPER = 'ZooKeeper'

      def self.all
        @all ||= [
          H_BASE,
          HDFS,
          HUE,
          HIVE,
          OOZIE,
          SOLR,
          SPARK,
          SQOOP,
          YARN,
          ZOO_KEEPER,
        ].freeze
      end

      def self.valid?(value)
        all.include?(value)
      end
    end
  end
end
