# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    class ClusterHadoopUser
      include Ovh::Api::Serializable
      include Ovh::Api::Validations

      attribute :cloudera_manager,
        type: 'Boolean',
        json_key: 'clouderaManager',
        required: false

      attribute :http_frontend,
        type: 'Boolean',
        json_key: 'httpFrontend',
        required: false

      attribute :hue,
        type: 'Boolean',
        json_key: 'hue',
        required: false

      attribute :username,
        type: 'String',
        json_key: 'username',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
