# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    module ClusterHadoopRoleTypeEnum
      CLOUDERA_MANAGER = 'cloudera_manager'
      DATA_NODE = 'data_node'
      ELASTICSEARCH_SERVER = 'elasticsearch_server'
      HBASE_MASTER = 'hbase_master'
      HBASE_REGION_SERVER = 'hbase_region_server'
      HIVE_SERVER2 = 'hive_server2'
      HUE = 'hue'
      IMPALA_DAEMON = 'impala_daemon'
      IMPALA_SERVER = 'impala_server'
      MAP_REDUCE_HISTORY_SERVER = 'map_reduce_history_server'
      NAME_NODE = 'name_node'
      OOZIE_SERVER = 'oozie_server'
      OPEN_TSDB = 'open_tsdb'
      SECONDARY_NAME_NODE = 'secondary_name_node'
      SOLR_SERVER = 'solr_server'
      SPARK_MASTER = 'spark_master'
      SPARK_WORKER = 'spark_worker'
      SQOOP_SERVER = 'sqoop_server'
      YARN_NODE_MANAGER = 'yarn_node_manager'
      YARN_RESOURCE_MANAGER = 'yarn_resource_manager'
      ZOO_KEEPER = 'zoo_keeper'

      def self.all
        @all ||= [
          CLOUDERA_MANAGER,
          DATA_NODE,
          ELASTICSEARCH_SERVER,
          HBASE_MASTER,
          HBASE_REGION_SERVER,
          HIVE_SERVER2,
          HUE,
          IMPALA_DAEMON,
          IMPALA_SERVER,
          MAP_REDUCE_HISTORY_SERVER,
          NAME_NODE,
          OOZIE_SERVER,
          OPEN_TSDB,
          SECONDARY_NAME_NODE,
          SOLR_SERVER,
          SPARK_MASTER,
          SPARK_WORKER,
          SQOOP_SERVER,
          YARN_NODE_MANAGER,
          YARN_RESOURCE_MANAGER,
          ZOO_KEEPER,
        ].freeze
      end

      def self.valid?(value)
        all.include?(value)
      end
    end
  end
end
