# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    class ConnectivityEligibilityTestAddressPost
      include Ovh::Api::Serializable
      include Ovh::Api::Validations

      attribute :hexacle,
        type: 'String',
        json_key: 'hexacle',
        required: false

      attribute :product_family,
        type: 'ConnectivityEligibilityProductFamilyEnum',
        json_key: 'productFamily',
        required: false

      attribute :street_alt_code,
        type: 'String',
        json_key: 'streetAltCode',
        required: false

      attribute :street_code,
        type: 'String',
        json_key: 'streetCode',
        required: false

      attribute :street_number,
        type: 'String',
        json_key: 'streetNumber',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
