# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    module DbaasLogsStreamAlertConditionConditionTypeEnum
      FIELD_CONTENT_VALUE = 'FIELD_CONTENT_VALUE'
      FIELD_VALUE = 'FIELD_VALUE'
      MESSAGE_COUNT = 'MESSAGE_COUNT'

      def self.all
        @all ||= [
          FIELD_CONTENT_VALUE,
          FIELD_VALUE,
          MESSAGE_COUNT,
        ].freeze
      end

      def self.valid?(value)
        all.include?(value)
      end
    end
  end
end
