# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    class DbaasLogsOutputGraylogStreamCreation
      include Ovh::Api::Serializable
      include Ovh::Api::Validations

      attribute :cold_storage_compression,
        type: 'DbaasLogsStreamColdStorageCompressionEnum',
        json_key: 'coldStorageCompression',
        required: false

      attribute :cold_storage_content,
        type: 'DbaasLogsStreamColdStorageContentEnum',
        json_key: 'coldStorageContent',
        required: false

      attribute :cold_storage_enabled,
        type: 'Boolean',
        json_key: 'coldStorageEnabled',
        required: false

      attribute :cold_storage_notify_enabled,
        type: 'Boolean',
        json_key: 'coldStorageNotifyEnabled',
        required: false

      attribute :cold_storage_retention,
        type: 'Integer',
        json_key: 'coldStorageRetention',
        required: false

      attribute :description,
        type: 'String',
        json_key: 'description',
        required: true

      attribute :encryption_keys_ids,
        type: 'Array<String>',
        json_key: 'encryptionKeysIds',
        required: false

      attribute :indexing_enabled,
        type: 'Boolean',
        json_key: 'indexingEnabled',
        required: false

      attribute :indexing_max_size,
        type: 'Integer',
        json_key: 'indexingMaxSize',
        required: false

      attribute :indexing_notify_enabled,
        type: 'Boolean',
        json_key: 'indexingNotifyEnabled',
        required: false

      attribute :parent_stream_id,
        type: 'String',
        json_key: 'parentStreamId',
        required: false

      attribute :pause_indexing_on_max_size,
        type: 'Boolean',
        json_key: 'pauseIndexingOnMaxSize',
        required: false

      attribute :retention_id,
        type: 'String',
        json_key: 'retentionId',
        required: false

      attribute :title,
        type: 'String',
        json_key: 'title',
        required: true

      attribute :web_socket_enabled,
        type: 'Boolean',
        json_key: 'webSocketEnabled',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
