# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    class DbaasLogsEncryptionKey
      include Ovh::Api::Serializable
      include Ovh::Api::Validations

      attribute :algorithm,
        type: 'DbaasLogsEncryptionKeyAlgorithmEnum',
        json_key: 'algorithm',
        required: false

      attribute :content,
        type: 'String',
        json_key: 'content',
        required: true

      attribute :created_at,
        type: 'Time',
        json_key: 'createdAt',
        required: false

      attribute :encryption_key_id,
        type: 'String',
        json_key: 'encryptionKeyId',
        required: false

      attribute :fingerprint,
        type: 'String',
        json_key: 'fingerprint',
        required: true

      attribute :is_editable,
        type: 'Boolean',
        json_key: 'isEditable',
        required: false

      attribute :nb_archive,
        type: 'Integer',
        json_key: 'nbArchive',
        required: false

      attribute :title,
        type: 'String',
        json_key: 'title',
        required: true

      attribute :uid,
        type: 'String',
        json_key: 'uid',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
