# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    module DbaasLogsStreamRuleOperatorEnum
      FIELD_PRESENCE = 'FIELD_PRESENCE'
      GREATER_THAN = 'GREATER_THAN'
      MATCH_EXACTLY = 'MATCH_EXACTLY'
      SMALLER_THAN = 'SMALLER_THAN'

      def self.all
        @all ||= [
          FIELD_PRESENCE,
          GREATER_THAN,
          MATCH_EXACTLY,
          SMALLER_THAN,
        ].freeze
      end

      def self.valid?(value)
        all.include?(value)
      end
    end
  end
end
