# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    class DbaasLogsInputConfigurationFlowggerUpdate
      include Ovh::Api::Serializable
      include Ovh::Api::Validations

      attribute :log_format,
        type: 'DbaasLogsFlowggerConfigurationLogFormatEnum',
        json_key: 'logFormat',
        required: true

      attribute :log_framing,
        type: 'DbaasLogsFlowggerConfigurationLogFramingEnum',
        json_key: 'logFraming',
        required: true

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
