# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    module DedicatedCloudSecurityOptionSecurityOptionEnum
      ACCESS_NETWORK_FILTERED = 'accessNetworkFiltered'
      ADVANCED_SECURITY = 'advancedSecurity'
      BASE = 'base'
      CONTENT_LIBRARY = 'contentLibrary'
      GRSEC_KERNEL = 'grsecKernel'
      HDS = 'hds'
      HIDS = 'hids'
      HIPAA = 'hipaa'
      LOG_FORWARDER = 'logForwarder'
      NIDS = 'nids'
      PCIDSS = 'pcidss'
      PRIVATE_CUSTOMER_VLAN = 'privateCustomerVlan'
      PRIVATE_GW = 'privateGw'
      SEND_LOG_TO_CUSTOMER = 'sendLogToCustomer'
      SESSION_TIMEOUT = 'sessionTimeout'
      SFTP = 'sftp'
      SNC = 'snc'
      SPLA = 'spla'
      SSL_V3 = 'sslV3'
      TLS1_2 = 'tls1.2'
      TOKEN_VALIDATION = 'tokenValidation'
      TWO_FA = 'twoFa'
      TWO_FA_FAIL2BAN = 'twoFaFail2ban'
      VRLI_FORWARDER = 'vrliForwarder'
      WAF = 'waf'

      def self.all
        @all ||= [
          ACCESS_NETWORK_FILTERED,
          ADVANCED_SECURITY,
          BASE,
          CONTENT_LIBRARY,
          GRSEC_KERNEL,
          HDS,
          HIDS,
          HIPAA,
          LOG_FORWARDER,
          NIDS,
          PCIDSS,
          PRIVATE_CUSTOMER_VLAN,
          PRIVATE_GW,
          SEND_LOG_TO_CUSTOMER,
          SESSION_TIMEOUT,
          SFTP,
          SNC,
          SPLA,
          SSL_V3,
          TLS1_2,
          TOKEN_VALIDATION,
          TWO_FA,
          TWO_FA_FAIL2BAN,
          VRLI_FORWARDER,
          WAF,
        ].freeze
      end

      def self.valid?(value)
        all.include?(value)
      end
    end
  end
end
