# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    class DedicatedCloudDedicatedCloud
      include Ovh::Api::Serializable
      include Ovh::Api::Validations

      attribute :advanced_security,
        type: 'Boolean',
        json_key: 'advancedSecurity',
        required: false

      attribute :bandwidth,
        type: 'String',
        json_key: 'bandwidth',
        required: false

      attribute :billing_type,
        type: 'DedicatedCloudBillingTypeEnum',
        json_key: 'billingType',
        required: false

      attribute :can_migrate_to_vcd,
        type: 'Boolean',
        json_key: 'canMigrateToVCD',
        required: false

      attribute :certified_interface_url,
        type: 'String',
        json_key: 'certifiedInterfaceUrl',
        required: false

      attribute :commercial_range,
        type: 'String',
        json_key: 'commercialRange',
        required: false

      attribute :description,
        type: 'String',
        json_key: 'description',
        required: false

      attribute :generation,
        type: 'DedicatedCloudGenerationEnum',
        json_key: 'generation',
        required: false

      attribute :location,
        type: 'String',
        json_key: 'location',
        required: false

      attribute :management_interface,
        type: 'DedicatedCloudManagementInterfaceEnum',
        json_key: 'managementInterface',
        required: false

      attribute :product_reference,
        type: 'DedicatedCloudProductReferenceEnum',
        json_key: 'productReference',
        required: false

      attribute :service_name,
        type: 'String',
        json_key: 'serviceName',
        required: false

      attribute :service_pack_name,
        type: 'String',
        json_key: 'servicePackName',
        required: false

      attribute :spla,
        type: 'Boolean',
        json_key: 'spla',
        required: false

      attribute :ssl_v3,
        type: 'Boolean',
        json_key: 'sslV3',
        required: false

      attribute :state,
        type: 'DedicatedCloudStateEnum',
        json_key: 'state',
        required: false

      attribute :user_access_policy,
        type: 'DedicatedCloudUserAccessPolicyEnum',
        json_key: 'userAccessPolicy',
        required: false

      attribute :user_limit_concurrent_session,
        type: 'Integer',
        json_key: 'userLimitConcurrentSession',
        required: false

      attribute :user_logout_policy,
        type: 'DedicatedCloudUserLogoutPolicyEnum',
        json_key: 'userLogoutPolicy',
        required: false

      attribute :user_session_timeout,
        type: 'Integer',
        json_key: 'userSessionTimeout',
        required: false

      attribute :v_scope_url,
        type: 'String',
        json_key: 'vScopeUrl',
        required: false

      attribute :version,
        type: 'DedicatedCloudVersion',
        json_key: 'version',
        required: false

      attribute :web_interface_url,
        type: 'String',
        json_key: 'webInterfaceUrl',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
