# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    class DedicatedServerReinstallStoragePartitioningLayout
      include Ovh::Api::Serializable
      include Ovh::Api::Validations

      attribute :extras,
        type: 'DedicatedServerReinstallStoragePartitioningLayoutExtras',
        json_key: 'extras',
        required: false

      attribute :file_system,
        type: 'DedicatedServerReinstallStoragePartitioningLayoutFileSystemEnum',
        json_key: 'fileSystem',
        required: true

      attribute :mount_point,
        type: 'String',
        json_key: 'mountPoint',
        required: true

      attribute :raid_level,
        type: 'DedicatedServerReinstallStoragePartitioningLayoutRaidLevelEnum',
        json_key: 'raidLevel',
        required: false

      attribute :size,
        type: 'Integer',
        json_key: 'size',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
