# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    module DedicatedCloudBackupOfferTypeEnum
      ADVANCED = 'advanced'
      BACKUP = 'backup'
      CLASSIC = 'classic'
      LEGACY = 'legacy'
      PREMIUM = 'premium'

      def self.all
        @all ||= [
          ADVANCED,
          BACKUP,
          CLASSIC,
          LEGACY,
          PREMIUM,
        ].freeze
      end

      def self.valid?(value)
        all.include?(value)
      end
    end
  end
end
