# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    module DedicatedCloudRightNetworkRoleEnum
      ADMIN = 'admin'
      MANAGER = 'manager'
      NO_ACCESS = 'noAccess'
      READONLY = 'readonly'

      def self.all
        @all ||= [
          ADMIN,
          MANAGER,
          NO_ACCESS,
          READONLY,
        ].freeze
      end

      def self.valid?(value)
        all.include?(value)
      end
    end
  end
end
