# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    module DedicatedServerReinstallCustomizationsImageCheckSumTypeEnum
      MD5 = 'md5'
      SHA1 = 'sha1'
      SHA256 = 'sha256'
      SHA512 = 'sha512'

      def self.all
        @all ||= [
          MD5,
          SHA1,
          SHA256,
          SHA512,
        ].freeze
      end

      def self.valid?(value)
        all.include?(value)
      end
    end
  end
end
