# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    module DedicatedCloudBackupBackupDaysEnum
      FRIDAY = 'Friday'
      MONDAY = 'Monday'
      SATURDAY = 'Saturday'
      SUNDAY = 'Sunday'
      THURSDAY = 'Thursday'
      TUESDAY = 'Tuesday'
      WEDNESDAY = 'Wednesday'

      def self.all
        @all ||= [
          FRIDAY,
          MONDAY,
          SATURDAY,
          SUNDAY,
          THURSDAY,
          TUESDAY,
          WEDNESDAY,
        ].freeze
      end

      def self.valid?(value)
        all.include?(value)
      end
    end
  end
end
