# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    module DedicatedServerIpmiAccessTypeEnum
      KVMIP_HTML5_URL = 'kvmipHtml5URL'
      KVMIP_JNLP = 'kvmipJnlp'
      SERIAL_OVER_LAN_SSH_KEY = 'serialOverLanSshKey'
      SERIAL_OVER_LAN_URL = 'serialOverLanURL'

      def self.all
        @all ||= [
          KVMIP_HTML5_URL,
          KVMIP_JNLP,
          SERIAL_OVER_LAN_SSH_KEY,
          SERIAL_OVER_LAN_URL,
        ].freeze
      end

      def self.valid?(value)
        all.include?(value)
      end
    end
  end
end
