# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    module DedicatedCloudDisasterRecoveryZertoVraResourceSizeEnum
      L = 'L'
      S = 'S'
      XL = 'XL'
      XS = 'XS'

      def self.all
        @all ||= [
          L,
          S,
          XL,
          XS,
        ].freeze
      end

      def self.valid?(value)
        all.include?(value)
      end
    end
  end
end
