# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    module DedicatedCloudManagementInterfaceEnum
      AZURE = 'azure'
      OPENSTACK = 'openstack'
      SYSTEMCENTER = 'systemcenter'
      VCLOUD = 'vcloud'
      VCSA = 'vcsa'
      VSPHERE = 'vsphere'

      def self.all
        @all ||= [
          AZURE,
          OPENSTACK,
          SYSTEMCENTER,
          VCLOUD,
          VCSA,
          VSPHERE,
        ].freeze
      end

      def self.valid?(value)
        all.include?(value)
      end
    end
  end
end
