# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    class DedicatedCloudServiceNameDatacenterDatacenterIdDisasterHf0523897
      include Ovh::Api::Serializable
      include Ovh::Api::Validations

      attribute :pre_shared_key,
        type: 'String',
        json_key: 'preSharedKey',
        required: true

      attribute :remote_endpoint_internal_ip,
        type: 'String',
        json_key: 'remoteEndpointInternalIp',
        required: true

      attribute :remote_endpoint_public_ip,
        type: 'String',
        json_key: 'remoteEndpointPublicIp',
        required: true

      attribute :remote_vra_network,
        type: 'String',
        json_key: 'remoteVraNetwork',
        required: false

      attribute :remote_zvm_internal_ip,
        type: 'String',
        json_key: 'remoteZvmInternalIp',
        required: true

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
