# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    module DedicatedServerUsbKeyCapacityEnum
      N16 = '16'
      N32 = '32'
      N64 = '64'
      N128 = '128'
      N256 = '256'

      def self.all
        @all ||= [
          N16,
          N32,
          N64,
          N128,
          N256,
        ].freeze
      end

      def self.valid?(value)
        all.include?(value)
      end
    end
  end
end
