# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    module DedicatedCloudOrderableIpBlockRangeEnum
      N24 = '24'
      N25 = '25'
      N26 = '26'
      N27 = '27'
      N28 = '28'

      def self.all
        @all ||= [
          N24,
          N25,
          N26,
          N27,
          N28,
        ].freeze
      end

      def self.valid?(value)
        all.include?(value)
      end
    end
  end
end
