# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    module DedicatedStorageProtocolEnum
      CIFS = 'CIFS'
      NFS = 'NFS'
      NFS_CIFS = 'NFS_CIFS'

      def self.all
        @all ||= [
          CIFS,
          NFS,
          NFS_CIFS,
        ].freeze
      end

      def self.valid?(value)
        all.include?(value)
      end
    end
  end
end
