# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    module DedicatedServerTrafficOrderEnum
      N100_MBPS_UNLIMITED = '100Mbps-Unlimited'
      N250_MBPS_UNLIMITED = '250Mbps-Unlimited'
      N500_MBPS_UNLIMITED = '500Mbps-Unlimited'

      def self.all
        @all ||= [
          N100_MBPS_UNLIMITED,
          N250_MBPS_UNLIMITED,
          N500_MBPS_UNLIMITED,
        ].freeze
      end

      def self.valid?(value)
        all.include?(value)
      end
    end
  end
end
