# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    module DedicatedServerStateEnum
      ERROR = 'error'
      HACKED = 'hacked'
      HACKED_BLOCKED = 'hackedBlocked'
      OK = 'ok'

      def self.all
        @all ||= [
          ERROR,
          HACKED,
          HACKED_BLOCKED,
          OK,
        ].freeze
      end

      def self.valid?(value)
        all.include?(value)
      end
    end
  end
end
