# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    module DedicatedServerCacheTTLEnum
      N1 = '1'
      N3 = '3'
      N5 = '5'
      N10 = '10'
      N15 = '15'

      def self.all
        @all ||= [
          N1,
          N3,
          N5,
          N10,
          N15,
        ].freeze
      end

      def self.valid?(value)
        all.include?(value)
      end
    end
  end
end
