# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    module DedicatedServerOrderableSysFeatureEnum
      BACKUP_PROTOCOL = 'backupProtocol'
      MONITORING = 'monitoring'

      def self.all
        @all ||= [
          BACKUP_PROTOCOL,
          MONITORING,
        ].freeze
      end

      def self.valid?(value)
        all.include?(value)
      end
    end
  end
end
