# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    module DedicatedCloudAllowedNetworkStateEnum
      ALLOWED = 'allowed'
      TO_DELETE = 'toDelete'
      TO_UPDATE = 'toUpdate'

      def self.all
        @all ||= [
          ALLOWED,
          TO_DELETE,
          TO_UPDATE,
        ].freeze
      end

      def self.valid?(value)
        all.include?(value)
      end
    end
  end
end
