# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    module DedicatedCloudFilerFilerTypeEnum
      NAS = 'nas'
      VSAN = 'vsan'

      def self.all
        @all ||= [
          NAS,
          VSAN,
        ].freeze
      end

      def self.valid?(value)
        all.include?(value)
      end
    end
  end
end
