# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    class DedicatedServerReinstall
      include Ovh::Api::Serializable
      include Ovh::Api::Validations

      attribute :customizations,
        type: 'DedicatedServerReinstallCustomizations',
        json_key: 'customizations',
        required: false

      attribute :operating_system,
        type: 'String',
        json_key: 'operatingSystem',
        required: true

      attribute :properties,
        type: 'Hash<String, String>',
        json_key: 'properties',
        required: false

      attribute :storage,
        type: 'Array<DedicatedServerReinstallStorage>',
        json_key: 'storage',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
