# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    class DedicatedNashaServiceNamePartitionPartitionNameOptionsPH10fa2c9b
      include Ovh::Api::Serializable
      include Ovh::Api::Validations

      attribute :atime,
        type: 'DedicatedStorageAtimeEnum',
        json_key: 'atime',
        required: false

      attribute :recordsize,
        type: 'DedicatedStorageRecordSizeEnum',
        json_key: 'recordsize',
        required: false

      attribute :sync,
        type: 'DedicatedStorageSyncEnum',
        json_key: 'sync',
        required: false

      attribute :template_name,
        type: 'DedicatedStorageTemplateUsageOptionsEnum',
        json_key: 'templateName',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
