# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    class DedicatedCloudAllowedNetwork
      include Ovh::Api::Serializable
      include Ovh::Api::Validations

      attribute :description,
        type: 'String',
        json_key: 'description',
        required: false

      attribute :network,
        type: 'String',
        json_key: 'network',
        required: false

      attribute :network_access_id,
        type: 'Integer',
        json_key: 'networkAccessId',
        required: false

      attribute :state,
        type: 'DedicatedCloudAllowedNetworkStateEnum',
        json_key: 'state',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
