# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    module DedicatedServerReinstallStorageHardwareRaidRaidLevelEnum
      N0 = 0
      N1 = 1
      N5 = 5
      N6 = 6
      N10 = 10
      N50 = 50
      N60 = 60

      def self.all
        @all ||= [
          N0,
          N1,
          N5,
          N6,
          N10,
          N50,
          N60,
        ].freeze
      end

      def self.valid?(value)
        all.include?(value)
      end
    end
  end
end
