# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    class DedicatedCloudServiceNameUserPostRequest
      include Ovh::Api::Serializable
      include Ovh::Api::Validations

      attribute :can_add_ressource,
        type: 'Boolean',
        json_key: 'canAddRessource',
        required: false

      attribute :can_manage_rights,
        type: 'Boolean',
        json_key: 'canManageRights',
        required: false

      attribute :email,
        type: 'String',
        json_key: 'email',
        required: false

      attribute :encryption_right,
        type: 'Boolean',
        json_key: 'encryptionRight',
        required: false

      attribute :expiration_date,
        type: 'Time',
        json_key: 'expirationDate',
        required: false

      attribute :first_name,
        type: 'String',
        json_key: 'firstName',
        required: false

      attribute :last_name,
        type: 'String',
        json_key: 'lastName',
        required: false

      attribute :name,
        type: 'String',
        json_key: 'name',
        required: true

      attribute :network_role,
        type: 'DedicatedCloudRightNetworkRoleEnum',
        json_key: 'networkRole',
        required: false

      attribute :nsx_right,
        type: 'Boolean',
        json_key: 'nsxRight',
        required: false

      attribute :password,
        type: 'String',
        json_key: 'password',
        required: false

      attribute :phone_number,
        type: 'String',
        json_key: 'phoneNumber',
        required: false

      attribute :receive_alerts,
        type: 'Boolean',
        json_key: 'receiveAlerts',
        required: false

      attribute :right,
        type: 'DedicatedCloudRightRightEnum',
        json_key: 'right',
        required: false

      attribute :token_validator,
        type: 'Boolean',
        json_key: 'tokenValidator',
        required: false

      attribute :vm_network_role,
        type: 'DedicatedCloudRightVmNetworkRoleEnum',
        json_key: 'vmNetworkRole',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
