# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    class DedicatedServerFirewall
      include Ovh::Api::Serializable
      include Ovh::Api::Validations

      attribute :enabled,
        type: 'Boolean',
        json_key: 'enabled',
        required: false

      attribute :firewall,
        type: 'String',
        json_key: 'firewall',
        required: false

      attribute :ip,
        type: 'String',
        json_key: 'ip',
        required: false

      attribute :mode,
        type: 'DedicatedServerFirewallModeEnum',
        json_key: 'mode',
        required: false

      attribute :model,
        type: 'DedicatedServerFirewallModelEnum',
        json_key: 'model',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
