# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    class DedicatedCloudDatacenter
      include Ovh::Api::Serializable
      include Ovh::Api::Validations

      attribute :commercial_name,
        type: 'DedicatedCloudCommercialNameEnum',
        json_key: 'commercialName',
        required: false

      attribute :commercial_range_name,
        type: 'String',
        json_key: 'commercialRangeName',
        required: false

      attribute :datacenter_id,
        type: 'Integer',
        json_key: 'datacenterId',
        required: false

      attribute :description,
        type: 'String',
        json_key: 'description',
        required: false

      attribute :has_mixed_host_profiles,
        type: 'Boolean',
        json_key: 'hasMixedHostProfiles',
        required: false

      attribute :has_mixed_vsan_host_profiles,
        type: 'Boolean',
        json_key: 'hasMixedVsanHostProfiles',
        required: false

      attribute :horizon_view_name,
        type: 'String',
        json_key: 'horizonViewName',
        required: false

      attribute :is_removable,
        type: 'Boolean',
        json_key: 'isRemovable',
        required: false

      attribute :name,
        type: 'String',
        json_key: 'name',
        required: false

      attribute :version,
        type: 'String',
        json_key: 'version',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
