# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    module DedicatedCloudRessourcesUpgradeRessourceTypeEnum
      ACCOUNT = 'account'
      ALL = 'all'
      FILER = 'filer'
      HOST = 'host'

      def self.all
        @all ||= [
          ACCOUNT,
          ALL,
          FILER,
          HOST,
        ].freeze
      end

      def self.valid?(value)
        all.include?(value)
      end
    end
  end
end
