# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    module DedicatedStorageRecordSizeEnum
      N1048576 = '1048576'
      N131072 = '131072'
      N16384 = '16384'
      N32768 = '32768'
      N4096 = '4096'
      N65536 = '65536'
      N8192 = '8192'

      def self.all
        @all ||= [
          N1048576,
          N131072,
          N16384,
          N32768,
          N4096,
          N65536,
          N8192,
        ].freeze
      end

      def self.valid?(value)
        all.include?(value)
      end
    end
  end
end
