# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    class DedicatedServerSpla
      include Ovh::Api::Serializable
      include Ovh::Api::Validations

      attribute :id,
        type: 'Integer',
        json_key: 'id',
        required: false

      attribute :last_update,
        type: 'Time',
        json_key: 'lastUpdate',
        required: false

      attribute :serial_number,
        type: 'String',
        json_key: 'serialNumber',
        required: false

      attribute :status,
        type: 'DedicatedServerSplaStatusEnum',
        json_key: 'status',
        required: false

      attribute :type,
        type: 'DedicatedServerSplaTypeEnum',
        json_key: 'type',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
