# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    class DedicatedCloudSapApplicationServers
      include Ovh::Api::Serializable
      include Ovh::Api::Validations

      attribute :datastore_name,
        type: 'String',
        json_key: 'datastoreName',
        required: true

      attribute :gateway,
        type: 'String',
        json_key: 'gateway',
        required: true

      attribute :instance_number,
        type: 'String',
        json_key: 'instanceNumber',
        required: true

      attribute :ip_address,
        type: 'String',
        json_key: 'ipAddress',
        required: true

      attribute :memory,
        type: 'Integer',
        json_key: 'memory',
        required: true

      attribute :name,
        type: 'String',
        json_key: 'name',
        required: true

      attribute :netmask,
        type: 'String',
        json_key: 'netmask',
        required: true

      attribute :network,
        type: 'String',
        json_key: 'network',
        required: true

      attribute :ova_template,
        type: 'DedicatedCloudSapOvaTemplatesEnum',
        json_key: 'ovaTemplate',
        required: true

      attribute :role,
        type: 'DedicatedCloudSapRolesEnum',
        json_key: 'role',
        required: true

      attribute :root_password,
        type: 'String',
        json_key: 'rootPassword',
        required: true

      attribute :vcpus,
        type: 'Integer',
        json_key: 'vcpus',
        required: true

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
