# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    class DedicatedCephUserPoolPermSetAllPermissions
      include Ovh::Api::Serializable
      include Ovh::Api::Validations

      attribute :class_read,
        type: 'Boolean',
        json_key: 'classRead',
        required: false

      attribute :class_write,
        type: 'Boolean',
        json_key: 'classWrite',
        required: false

      attribute :execute,
        type: 'Boolean',
        json_key: 'execute',
        required: false

      attribute :pool_name,
        type: 'String',
        json_key: 'poolName',
        required: false

      attribute :read,
        type: 'Boolean',
        json_key: 'read',
        required: false

      attribute :write,
        type: 'Boolean',
        json_key: 'write',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
