# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    class DedicatedCloudServiceNameDatacenterDatacenterIdDisasterH4aca9df3
      include Ovh::Api::Serializable
      include Ovh::Api::Validations

      attribute :resources_size,
        type: 'DedicatedCloudDisasterRecoveryZertoVraResourceSizeEnum',
        json_key: 'resourcesSize',
        required: true

      attribute :vm_id,
        type: 'Integer',
        json_key: 'vmId',
        required: true

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
