# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    module DedicatedCephClusterUpdateCrushTunablesEnum
      ARGONAUT = 'ARGONAUT'
      BOBTAIL = 'BOBTAIL'
      DEFAULT = 'DEFAULT'
      FIREFLY = 'FIREFLY'
      HAMMER = 'HAMMER'
      JEWEL = 'JEWEL'
      LEGACY = 'LEGACY'
      OPTIMAL = 'OPTIMAL'

      def self.all
        @all ||= [
          ARGONAUT,
          BOBTAIL,
          DEFAULT,
          FIREFLY,
          HAMMER,
          JEWEL,
          LEGACY,
          OPTIMAL,
        ].freeze
      end

      def self.valid?(value)
        all.include?(value)
      end
    end
  end
end
