# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    module DedicatedDatacenterEnum
      BHS1 = 'bhs1'
      BHS2 = 'bhs2'
      BHS3 = 'bhs3'
      BHS4 = 'bhs4'
      BHS5 = 'bhs5'
      BHS6 = 'bhs6'
      BHS7 = 'bhs7'
      BHS8 = 'bhs8'
      CCH01 = 'cch01'
      CRX1 = 'crx1'
      CRX2 = 'crx2'
      DC1 = 'dc1'
      ERI1 = 'eri1'
      ERI2 = 'eri2'
      GRA04 = 'gra04'
      GRA1 = 'gra1'
      GRA2 = 'gra2'
      GRA3 = 'gra3'
      GSW = 'gsw'
      HDF01 = 'hdf01'
      HIL1 = 'hil1'
      IEB01 = 'ieb01'
      ITBSI01 = 'itbsi01'
      ITMIL01 = 'itmil01'
      ITZVF01 = 'itzvf01'
      LIL1_INT1 = 'lil1-int1'
      LIM1 = 'lim1'
      LIM2 = 'lim2'
      LIM3 = 'lim3'
      MR901 = 'mr901'
      P19 = 'p19'
      RBX = 'rbx'
      RBX_HZ = 'rbx-hz'
      RBX1 = 'rbx1'
      RBX10 = 'rbx10'
      RBX2 = 'rbx2'
      RBX3 = 'rbx3'
      RBX4 = 'rbx4'
      RBX5 = 'rbx5'
      RBX6 = 'rbx6'
      RBX7 = 'rbx7'
      RBX8 = 'rbx8'
      RBX9 = 'rbx9'
      SBG1 = 'sbg1'
      SBG2 = 'sbg2'
      SBG3 = 'sbg3'
      SBG4 = 'sbg4'
      SBG5 = 'sbg5'
      SGP02 = 'sgp02'
      SGP1 = 'sgp1'
      SYD03 = 'syd03'
      SYD1 = 'syd1'
      SYD2 = 'syd2'
      VIN1 = 'vin1'
      WAW1 = 'waw1'
      YNM1 = 'ynm1'
      YYZ01 = 'yyz01'

      def self.all
        @all ||= [
          BHS1,
          BHS2,
          BHS3,
          BHS4,
          BHS5,
          BHS6,
          BHS7,
          BHS8,
          CCH01,
          CRX1,
          CRX2,
          DC1,
          ERI1,
          ERI2,
          GRA04,
          GRA1,
          GRA2,
          GRA3,
          GSW,
          HDF01,
          HIL1,
          IEB01,
          ITBSI01,
          ITMIL01,
          ITZVF01,
          LIL1_INT1,
          LIM1,
          LIM2,
          LIM3,
          MR901,
          P19,
          RBX,
          RBX_HZ,
          RBX1,
          RBX10,
          RBX2,
          RBX3,
          RBX4,
          RBX5,
          RBX6,
          RBX7,
          RBX8,
          RBX9,
          SBG1,
          SBG2,
          SBG3,
          SBG4,
          SBG5,
          SGP02,
          SGP1,
          SYD03,
          SYD1,
          SYD2,
          VIN1,
          WAW1,
          YNM1,
          YYZ01,
        ].freeze
      end

      def self.valid?(value)
        all.include?(value)
      end
    end
  end
end
