# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    module DedicatedStorageSnapshotEnum
      DAY_1 = 'day-1'
      DAY_2 = 'day-2'
      DAY_3 = 'day-3'
      DAY_7 = 'day-7'
      HOUR_1 = 'hour-1'
      HOUR_6 = 'hour-6'

      def self.all
        @all ||= [
          DAY_1,
          DAY_2,
          DAY_3,
          DAY_7,
          HOUR_1,
          HOUR_6,
        ].freeze
      end

      def self.valid?(value)
        all.include?(value)
      end
    end
  end
end
