# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    module DedicatedCloudSapApplicationVersionEnum
      NET_WEAVER_7_50 = 'NetWeaver 7.50'
      S_4_HANA_2021 = 'S/4HANA 2021'
      S_4_HANA_2022 = 'S/4HANA 2022'
      S_4_HANA_2023 = 'S/4HANA 2023'

      def self.all
        @all ||= [
          NET_WEAVER_7_50,
          S_4_HANA_2021,
          S_4_HANA_2022,
          S_4_HANA_2023,
        ].freeze
      end

      def self.valid?(value)
        all.include?(value)
      end
    end
  end
end
