# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    module DedicatedServerFirewallModeEnum
      ROUTED = 'routed'
      TRANSPARENT = 'transparent'

      def self.all
        @all ||= [
          ROUTED,
          TRANSPARENT,
        ].freeze
      end

      def self.valid?(value)
        all.include?(value)
      end
    end
  end
end
