# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    class DedicatedCloudSapParams
      include Ovh::Api::Serializable
      include Ovh::Api::Validations

      attribute :application_servers,
        type: 'Array<DedicatedCloudSapApplicationServers>',
        json_key: 'applicationServers',
        required: true

      attribute :application_type,
        type: 'DedicatedCloudSapApplicationTypeEnum',
        json_key: 'applicationType',
        required: true

      attribute :application_version,
        type: 'DedicatedCloudSapApplicationVersionEnum',
        json_key: 'applicationVersion',
        required: true

      attribute :bucket_backint,
        type: 'DedicatedCloudSapBucket',
        json_key: 'bucketBackint',
        required: false

      attribute :bucket_sources,
        type: 'DedicatedCloudSapBucket',
        json_key: 'bucketSources',
        required: true

      attribute :cluster_name,
        type: 'String',
        json_key: 'clusterName',
        required: true

      attribute :datacenter_id,
        type: 'Integer',
        json_key: 'datacenterId',
        required: true

      attribute :deployment_type,
        type: 'DedicatedCloudSapDeploymentTypeEnum',
        json_key: 'deploymentType',
        required: true

      attribute :domain_name,
        type: 'String',
        json_key: 'domainName',
        required: true

      attribute :firewall,
        type: 'DedicatedCloudSapFirewall',
        json_key: 'firewall',
        required: true

      attribute :hana_servers,
        type: 'Array<DedicatedCloudSapHanaServers>',
        json_key: 'hanaServers',
        required: true

      attribute :logs_data_platform,
        type: 'DedicatedCloudSapLdp',
        json_key: 'logsDataPlatform',
        required: false

      attribute :os_license,
        type: 'String',
        json_key: 'osLicense',
        required: false

      attribute :os_update,
        type: 'Boolean',
        json_key: 'osUpdate',
        required: true

      attribute :passwords,
        type: 'DedicatedCloudSapPasswords',
        json_key: 'passwords',
        required: true

      attribute :service_name,
        type: 'String',
        json_key: 'serviceName',
        required: false

      attribute :sids,
        type: 'DedicatedCloudSapSids',
        json_key: 'sids',
        required: true

      attribute :system_usage,
        type: 'DedicatedCloudSapSystemUsageEnum',
        json_key: 'systemUsage',
        required: true

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
