# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    module DedicatedVirtualNetworkInterfaceVirtualNetworkInterfaceModeEnum
      PUBLIC = 'public'
      PUBLIC_AGGREGATION = 'public_aggregation'
      VRACK = 'vrack'
      VRACK_AGGREGATION = 'vrack_aggregation'

      def self.all
        @all ||= [
          PUBLIC,
          PUBLIC_AGGREGATION,
          VRACK,
          VRACK_AGGREGATION,
        ].freeze
      end

      def self.valid?(value)
        all.include?(value)
      end
    end
  end
end
