# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    class DedicatedServerBackupFtpAcl
      include Ovh::Api::Serializable
      include Ovh::Api::Validations

      attribute :cifs,
        type: 'Boolean',
        json_key: 'cifs',
        required: false

      attribute :ftp,
        type: 'Boolean',
        json_key: 'ftp',
        required: false

      attribute :ip_block,
        type: 'String',
        json_key: 'ipBlock',
        required: false

      attribute :is_applied,
        type: 'Boolean',
        json_key: 'isApplied',
        required: false

      attribute :last_update,
        type: 'Time',
        json_key: 'lastUpdate',
        required: false

      attribute :nfs,
        type: 'Boolean',
        json_key: 'nfs',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
