# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    module DedicatedCloudSapOvaTemplatesEnum
      SLES_SLE_15_SP4_FULL_X86_64__BYOL = 'SLES SLE-15-SP4-Full-x86_64 (BYOL)'
      SLES_SLE_15_SP5_FULL_X86_64__BYOL = 'SLES SLE-15-SP5-Full-x86_64 (BYOL)'
      SLES_SLE_15_SP6_FULL_X86_64__BYOL = 'SLES SLE-15-SP6-Full-x86_64 (BYOL)'
      SLES_SLE_15_SP7_FULL_X86_64__BYOL = 'SLES SLE-15-SP7-Full-x86_64 (BYOL)'
      SLES_FOR_SAP_SLE_15_SP4_FULL_X86_64__BYOL = 'SLES for SAP SLE-15-SP4-Full-x86_64 (BYOL)'
      SLES_FOR_SAP_SLE_15_SP5_FULL_X86_64__BYOL = 'SLES for SAP SLE-15-SP5-Full-x86_64 (BYOL)'
      SLES_FOR_SAP_SLE_15_SP6_FULL_X86_64__BYOL = 'SLES for SAP SLE-15-SP6-Full-x86_64 (BYOL)'
      SLES_FOR_SAP_SLE_15_SP7_FULL_X86_64__BYOL = 'SLES for SAP SLE-15-SP7-Full-x86_64 (BYOL)'

      def self.all
        @all ||= [
          SLES_SLE_15_SP4_FULL_X86_64__BYOL,
          SLES_SLE_15_SP5_FULL_X86_64__BYOL,
          SLES_SLE_15_SP6_FULL_X86_64__BYOL,
          SLES_SLE_15_SP7_FULL_X86_64__BYOL,
          SLES_FOR_SAP_SLE_15_SP4_FULL_X86_64__BYOL,
          SLES_FOR_SAP_SLE_15_SP5_FULL_X86_64__BYOL,
          SLES_FOR_SAP_SLE_15_SP6_FULL_X86_64__BYOL,
          SLES_FOR_SAP_SLE_15_SP7_FULL_X86_64__BYOL,
        ].freeze
      end

      def self.valid?(value)
        all.include?(value)
      end
    end
  end
end
