# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    class DedicatedVirtualNetworkInterfaceVirtualNetworkInterface
      include Ovh::Api::Serializable
      include Ovh::Api::Validations

      attribute :enabled,
        type: 'Boolean',
        json_key: 'enabled',
        required: false

      attribute :mode,
        type: 'DedicatedVirtualNetworkInterfaceVirtualNetworkInterfaceModeEnum',
        json_key: 'mode',
        required: false

      attribute :name,
        type: 'String',
        json_key: 'name',
        required: false

      attribute :network_interface_controller,
        type: 'Array<String>',
        json_key: 'networkInterfaceController',
        required: false

      attribute :server_name,
        type: 'String',
        json_key: 'serverName',
        required: false

      attribute :uuid,
        type: 'String',
        json_key: 'uuid',
        required: false

      attribute :vrack,
        type: 'String',
        json_key: 'vrack',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
