# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    module DnssecKeyAlgorithmEnum
      N3 = 3
      N5 = 5
      N6 = 6
      N7 = 7
      N8 = 8
      N10 = 10
      N12 = 12
      N13 = 13
      N14 = 14
      N15 = 15
      N16 = 16

      def self.all
        @all ||= [
          N3,
          N5,
          N6,
          N7,
          N8,
          N10,
          N12,
          N13,
          N14,
          N15,
          N16,
        ].freeze
      end

      def self.valid?(value)
        all.include?(value)
      end
    end
  end
end
