# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    module DnssecKeyStatusEnum
      ACTIVE = 'active'
      GENERATED = 'generated'
      PUBLISHED = 'published'
      REMOVED = 'removed'
      RETIRED = 'retired'
      REVOKED = 'revoked'

      def self.all
        @all ||= [
          ACTIVE,
          GENERATED,
          PUBLISHED,
          REMOVED,
          RETIRED,
          REVOKED,
        ].freeze
      end

      def self.valid?(value)
        all.include?(value)
      end
    end
  end
end
