# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    module DomainDomainMXFilterEnum
      CUSTOM = 'CUSTOM'
      FULL_FILTERING = 'FULL_FILTERING'
      NO_FILTERING = 'NO_FILTERING'
      REDIRECT = 'REDIRECT'
      SIMPLE_FILTERING = 'SIMPLE_FILTERING'

      def self.all
        @all ||= [
          CUSTOM,
          FULL_FILTERING,
          NO_FILTERING,
          REDIRECT,
          SIMPLE_FILTERING,
        ].freeze
      end

      def self.valid?(value)
        all.include?(value)
      end
    end
  end
end
