# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    class DomainDomainService
      include Ovh::Api::Serializable
      include Ovh::Api::Validations

      attribute :contact_admin,
        type: 'DomainContactSummary',
        json_key: 'contactAdmin',
        required: false

      attribute :contact_billing,
        type: 'DomainContactSummary',
        json_key: 'contactBilling',
        required: false

      attribute :contact_owner,
        type: 'DomainContactSummary',
        json_key: 'contactOwner',
        required: false

      attribute :contact_tech,
        type: 'DomainContactSummary',
        json_key: 'contactTech',
        required: false

      attribute :dnssec_state,
        type: 'DomainDnssecStateEnum',
        json_key: 'dnssecState',
        required: false

      attribute :dnssec_supported,
        type: 'Boolean',
        json_key: 'dnssecSupported',
        required: false

      attribute :domain,
        type: 'String',
        json_key: 'domain',
        required: false

      attribute :expiration_date,
        type: 'Time',
        json_key: 'expirationDate',
        required: false

      attribute :glue_record_ipv6_supported,
        type: 'Boolean',
        json_key: 'glueRecordIpv6Supported',
        required: false

      attribute :glue_record_multi_ip_supported,
        type: 'Boolean',
        json_key: 'glueRecordMultiIpSupported',
        required: false

      attribute :host_supported,
        type: 'Boolean',
        json_key: 'hostSupported',
        required: false

      attribute :last_update,
        type: 'Time',
        json_key: 'lastUpdate',
        required: false

      attribute :name_server_type,
        type: 'DomainNameServerNameServerTypeEnum',
        json_key: 'nameServerType',
        required: false

      attribute :name_servers,
        type: 'Array<DomainNameServerNameServer>',
        json_key: 'nameServers',
        required: false

      attribute :offer,
        type: 'DomainOfferEnum',
        json_key: 'offer',
        required: false

      attribute :owo_supported,
        type: 'Boolean',
        json_key: 'owoSupported',
        required: false

      attribute :parent_service,
        type: 'DomainParentService',
        json_key: 'parentService',
        required: false

      attribute :renewal_date,
        type: 'Time',
        json_key: 'renewalDate',
        required: false

      attribute :renewal_state,
        type: 'DomainRenewalStateEnum',
        json_key: 'renewalState',
        required: false

      attribute :service_id,
        type: 'Integer',
        json_key: 'serviceId',
        required: false

      attribute :state,
        type: 'DomainDomainStateEnum',
        json_key: 'state',
        required: false

      attribute :suspension_state,
        type: 'DomainSuspensionStateEnum',
        json_key: 'suspensionState',
        required: false

      attribute :transfer_lock_status,
        type: 'DomainLockStatusEnum',
        json_key: 'transferLockStatus',
        required: false

      attribute :whois_owner,
        type: 'String',
        json_key: 'whoisOwner',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
