# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    module DomainIsForEnum
      CAMPAIGN_WEBSITE = 'campaign_website'
      EDUCATIONAL_WEBSITE = 'educational_website'
      EMAILS = 'emails'
      INFORMATION_WEBSITE = 'information_website'
      OTHER_PURPOSE = 'other_purpose'
      REDIRECT_PAGE = 'redirect_page'
      TRANSACTIONAL_WEBSITE = 'transactional_website'

      def self.all
        @all ||= [
          CAMPAIGN_WEBSITE,
          EDUCATIONAL_WEBSITE,
          EMAILS,
          INFORMATION_WEBSITE,
          OTHER_PURPOSE,
          REDIRECT_PAGE,
          TRANSACTIONAL_WEBSITE,
        ].freeze
      end

      def self.valid?(value)
        all.include?(value)
      end
    end
  end
end
