# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    module DomainDocumentFormatsEnum
      GIF = 'gif'
      JPEG = 'jpeg'
      JPG = 'jpg'
      PDF = 'pdf'
      PNG = 'png'

      def self.all
        @all ||= [
          GIF,
          JPEG,
          JPG,
          PDF,
          PNG,
        ].freeze
      end

      def self.valid?(value)
        all.include?(value)
      end
    end
  end
end
