# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    module DomainZoneResettableNamedResolutionFieldTypeEnum
      A = 'A'
      MX = 'MX'

      def self.all
        @all ||= [
          A,
          MX,
        ].freeze
      end

      def self.valid?(value)
        all.include?(value)
      end
    end
  end
end
