# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    module DomainDomainStateEnum
      AUTORENEW_IN_PROGRESS = 'autorenew_in_progress'
      AUTORENEW_REGISTRY_IN_PROGRESS = 'autorenew_registry_in_progress'
      DELETED = 'deleted'
      DISPUTE = 'dispute'
      EXPIRED = 'expired'
      OK = 'ok'
      OUTGOING_TRANSFER = 'outgoing_transfer'
      PENDING_CREATE = 'pending_create'
      PENDING_DELETE = 'pending_delete'
      PENDING_INCOMING_TRANSFER = 'pending_incoming_transfer'
      PENDING_INSTALLATION = 'pending_installation'
      REGISTRY_SUSPENDED = 'registry_suspended'
      RESTORABLE = 'restorable'
      TECHNICAL_SUSPENDED = 'technical_suspended'

      def self.all
        @all ||= [
          AUTORENEW_IN_PROGRESS,
          AUTORENEW_REGISTRY_IN_PROGRESS,
          DELETED,
          DISPUTE,
          EXPIRED,
          OK,
          OUTGOING_TRANSFER,
          PENDING_CREATE,
          PENDING_DELETE,
          PENDING_INCOMING_TRANSFER,
          PENDING_INSTALLATION,
          REGISTRY_SUSPENDED,
          RESTORABLE,
          TECHNICAL_SUSPENDED,
        ].freeze
      end

      def self.valid?(value)
        all.include?(value)
      end
    end
  end
end
