# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    module DomainRenewalStateEnum
      AUTOMATIC_RENEW = 'automatic_renew'
      CANCELLATION_COMPLETE = 'cancellation_complete'
      CANCELLATION_REQUESTED = 'cancellation_requested'
      MANUAL_RENEW = 'manual_renew'
      UNPAID = 'unpaid'

      def self.all
        @all ||= [
          AUTOMATIC_RENEW,
          CANCELLATION_COMPLETE,
          CANCELLATION_REQUESTED,
          MANUAL_RENEW,
          UNPAID,
        ].freeze
      end

      def self.valid?(value)
        all.include?(value)
      end
    end
  end
end
