# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    class EmailProServiceDomainPostRequest
      include Ovh::Api::Serializable
      include Ovh::Api::Validations

      attribute :auto_enable_dkim,
        type: 'Boolean',
        json_key: 'autoEnableDKIM',
        required: false

      attribute :configure_autodiscover,
        type: 'Boolean',
        json_key: 'configureAutodiscover',
        required: false

      attribute :configure_dkim,
        type: 'Boolean',
        json_key: 'configureDKIM',
        required: false

      attribute :configure_mx,
        type: 'Boolean',
        json_key: 'configureMx',
        required: false

      attribute :configure_spf,
        type: 'Boolean',
        json_key: 'configureSPF',
        required: false

      attribute :mx_relay,
        type: 'String',
        json_key: 'mxRelay',
        required: false

      attribute :name,
        type: 'String',
        json_key: 'name',
        required: true

      attribute :type,
        type: 'EmailProDomainTypeEnum',
        json_key: 'type',
        required: true

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
