# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    class EmailDomainDomainAccountPostRequest
      include Ovh::Api::Serializable
      include Ovh::Api::Validations

      attribute :account_name,
        type: 'String',
        json_key: 'accountName',
        required: true

      attribute :description,
        type: 'String',
        json_key: 'description',
        required: false

      attribute :password,
        type: 'String',
        json_key: 'password',
        required: true

      attribute :size,
        type: 'Integer',
        json_key: 'size',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
