# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    class EmailProService
      include Ovh::Api::Serializable
      include Ovh::Api::Validations

      attribute :complexity_enabled,
        type: 'Boolean',
        json_key: 'complexityEnabled',
        required: false

      attribute :display_name,
        type: 'String',
        json_key: 'displayName',
        required: false

      attribute :domain,
        type: 'String',
        json_key: 'domain',
        required: false

      attribute :hostname,
        type: 'String',
        json_key: 'hostname',
        required: false

      attribute :last_update_date,
        type: 'Time',
        json_key: 'lastUpdateDate',
        required: false

      attribute :lockout_duration,
        type: 'Integer',
        json_key: 'lockoutDuration',
        required: false

      attribute :lockout_observation_window,
        type: 'Integer',
        json_key: 'lockoutObservationWindow',
        required: false

      attribute :lockout_threshold,
        type: 'Integer',
        json_key: 'lockoutThreshold',
        required: false

      attribute :max_password_age,
        type: 'Integer',
        json_key: 'maxPasswordAge',
        required: false

      attribute :max_receive_size,
        type: 'Integer',
        json_key: 'maxReceiveSize',
        required: false

      attribute :max_send_size,
        type: 'Integer',
        json_key: 'maxSendSize',
        required: false

      attribute :min_password_age,
        type: 'Integer',
        json_key: 'minPasswordAge',
        required: false

      attribute :min_password_length,
        type: 'Integer',
        json_key: 'minPasswordLength',
        required: false

      attribute :offer,
        type: 'EmailProServiceOfferEnum',
        json_key: 'offer',
        required: false

      attribute :spam_and_virus_configuration,
        type: 'EmailProSpamAndVirusConfiguration',
        json_key: 'spamAndVirusConfiguration',
        required: false

      attribute :state,
        type: 'EmailProServiceStateEnum',
        json_key: 'state',
        required: false

      attribute :task_pending_id,
        type: 'Integer',
        json_key: 'taskPendingId',
        required: false

      attribute :web_url,
        type: 'String',
        json_key: 'webUrl',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
