# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    class EmailProAccount
      include Ovh::Api::Serializable
      include Ovh::Api::Validations

      attribute :sam_account_name,
        type: 'String',
        json_key: 'SAMAccountName',
        required: false

      attribute :configured,
        type: 'Boolean',
        json_key: 'configured',
        required: false

      attribute :creation_date,
        type: 'Time',
        json_key: 'creationDate',
        required: false

      attribute :current_usage,
        type: 'Integer',
        json_key: 'currentUsage',
        required: false

      attribute :delete_at_expiration,
        type: 'Boolean',
        json_key: 'deleteAtExpiration',
        required: false

      attribute :display_name,
        type: 'String',
        json_key: 'displayName',
        required: false

      attribute :domain,
        type: 'String',
        json_key: 'domain',
        required: false

      attribute :expiration_date,
        type: 'Time',
        json_key: 'expirationDate',
        required: false

      attribute :expiration_outlook_date,
        type: 'Time',
        json_key: 'expirationOutlookDate',
        required: false

      attribute :first_name,
        type: 'String',
        json_key: 'firstName',
        required: false

      attribute :hidden_from_gal,
        type: 'Boolean',
        json_key: 'hiddenFromGAL',
        required: false

      attribute :id,
        type: 'Integer',
        json_key: 'id',
        required: false

      attribute :initial,
        type: 'String',
        json_key: 'initial',
        required: false

      attribute :last_logoff_date,
        type: 'Time',
        json_key: 'lastLogoffDate',
        required: false

      attribute :last_logon_date,
        type: 'Time',
        json_key: 'lastLogonDate',
        required: false

      attribute :last_name,
        type: 'String',
        json_key: 'lastName',
        required: false

      attribute :last_update_date,
        type: 'Time',
        json_key: 'lastUpdateDate',
        required: false

      attribute :login,
        type: 'String',
        json_key: 'login',
        required: false

      attribute :mailing_filter,
        type: 'Array<EmailProMailingFilterEnum>',
        json_key: 'mailingFilter',
        required: false

      attribute :password_last_update,
        type: 'Time',
        json_key: 'passwordLastUpdate',
        required: false

      attribute :primary_email_address,
        type: 'String',
        json_key: 'primaryEmailAddress',
        required: false

      attribute :quota,
        type: 'Integer',
        json_key: 'quota',
        required: false

      attribute :renew_period,
        type: 'EmailProRenewPeriodEnum',
        json_key: 'renewPeriod',
        required: false

      attribute :spam_and_virus_configuration,
        type: 'EmailProSpamAndVirusConfiguration',
        json_key: 'spamAndVirusConfiguration',
        required: false

      attribute :spam_detected,
        type: 'Boolean',
        json_key: 'spamDetected',
        required: false

      attribute :spam_ticket_number,
        type: 'Integer',
        json_key: 'spamTicketNumber',
        required: false

      attribute :state,
        type: 'EmailProObjectStateEnum',
        json_key: 'state',
        required: false

      attribute :task_pending_id,
        type: 'Integer',
        json_key: 'taskPendingId',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
