# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    class EmailExchangeExchangeAccountProtocol
      include Ovh::Api::Serializable
      include Ovh::Api::Validations

      attribute :imap,
        type: 'Boolean',
        json_key: 'IMAP',
        required: false

      attribute :pop,
        type: 'Boolean',
        json_key: 'POP',
        required: false

      attribute :active_sync,
        type: 'Boolean',
        json_key: 'activeSync',
        required: false

      attribute :creation_date,
        type: 'Time',
        json_key: 'creationDate',
        required: false

      attribute :last_update,
        type: 'Time',
        json_key: 'lastUpdate',
        required: false

      attribute :task_pending_id,
        type: 'Integer',
        json_key: 'taskPendingId',
        required: false

      attribute :web_mail,
        type: 'Boolean',
        json_key: 'webMail',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
