# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    class EmailProExternalContact
      include Ovh::Api::Serializable
      include Ovh::Api::Validations

      attribute :creation_date,
        type: 'Time',
        json_key: 'creationDate',
        required: false

      attribute :display_name,
        type: 'String',
        json_key: 'displayName',
        required: false

      attribute :external_email_address,
        type: 'String',
        json_key: 'externalEmailAddress',
        required: false

      attribute :first_name,
        type: 'String',
        json_key: 'firstName',
        required: false

      attribute :hidden_from_gal,
        type: 'Boolean',
        json_key: 'hiddenFromGAL',
        required: false

      attribute :id,
        type: 'Integer',
        json_key: 'id',
        required: false

      attribute :initials,
        type: 'String',
        json_key: 'initials',
        required: false

      attribute :last_name,
        type: 'String',
        json_key: 'lastName',
        required: false

      attribute :state,
        type: 'EmailProObjectStateEnum',
        json_key: 'state',
        required: false

      attribute :task_pending_id,
        type: 'Integer',
        json_key: 'taskPendingId',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
