# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    class EmailExchangeAccount
      include Ovh::Api::Serializable
      include Ovh::Api::Validations

      attribute :sam_account_name,
        type: 'String',
        json_key: 'SAMAccountName',
        required: false

      attribute :account_license,
        type: 'EmailExchangeOvhLicenceEnum',
        json_key: 'accountLicense',
        required: false

      attribute :authentication_policy_id,
        type: 'Integer',
        json_key: 'authenticationPolicyId',
        required: false

      attribute :city,
        type: 'String',
        json_key: 'city',
        required: false

      attribute :company,
        type: 'String',
        json_key: 'company',
        required: false

      attribute :configured,
        type: 'Boolean',
        json_key: 'configured',
        required: false

      attribute :country_code,
        type: 'EmailExchangeCountryCodeEnum',
        json_key: 'countryCode',
        required: false

      attribute :creation_date,
        type: 'Time',
        json_key: 'creationDate',
        required: false

      attribute :current_usage,
        type: 'Integer',
        json_key: 'currentUsage',
        required: false

      attribute :custom_isolation_id,
        type: 'Integer',
        json_key: 'customIsolationId',
        required: false

      attribute :delete_at_expiration,
        type: 'Boolean',
        json_key: 'deleteAtExpiration',
        required: false

      attribute :delete_outlook_at_expiration,
        type: 'Boolean',
        json_key: 'deleteOutlookAtExpiration',
        required: false

      attribute :description,
        type: 'String',
        json_key: 'description',
        required: false

      attribute :display_name,
        type: 'String',
        json_key: 'displayName',
        required: false

      attribute :domain,
        type: 'String',
        json_key: 'domain',
        required: false

      attribute :exchange_guid,
        type: 'String',
        json_key: 'exchangeGuid',
        required: false

      attribute :expiration_date,
        type: 'Time',
        json_key: 'expirationDate',
        required: false

      attribute :expiration_outlook_date,
        type: 'Time',
        json_key: 'expirationOutlookDate',
        required: false

      attribute :fax,
        type: 'String',
        json_key: 'fax',
        required: false

      attribute :first_name,
        type: 'String',
        json_key: 'firstName',
        required: false

      attribute :forwarding_email,
        type: 'String',
        json_key: 'forwardingEmail',
        required: false

      attribute :guid,
        type: 'String',
        json_key: 'guid',
        required: false

      attribute :hidden_from_gal,
        type: 'Boolean',
        json_key: 'hiddenFromGAL',
        required: false

      attribute :id,
        type: 'Integer',
        json_key: 'id',
        required: false

      attribute :initial,
        type: 'String',
        json_key: 'initial',
        required: false

      attribute :job_department,
        type: 'String',
        json_key: 'jobDepartment',
        required: false

      attribute :job_title,
        type: 'String',
        json_key: 'jobTitle',
        required: false

      attribute :last_logoff_date,
        type: 'Time',
        json_key: 'lastLogoffDate',
        required: false

      attribute :last_logon_date,
        type: 'Time',
        json_key: 'lastLogonDate',
        required: false

      attribute :last_name,
        type: 'String',
        json_key: 'lastName',
        required: false

      attribute :last_update_date,
        type: 'Time',
        json_key: 'lastUpdateDate',
        required: false

      attribute :litigation,
        type: 'Boolean',
        json_key: 'litigation',
        required: false

      attribute :litigation_period,
        type: 'Integer',
        json_key: 'litigationPeriod',
        required: false

      attribute :login,
        type: 'String',
        json_key: 'login',
        required: false

      attribute :mail_sender_display,
        type: 'String',
        json_key: 'mailSenderDisplay',
        required: false

      attribute :mailing_filter,
        type: 'Array<EmailExchangeMailingFilterEnum>',
        json_key: 'mailingFilter',
        required: false

      attribute :mobile,
        type: 'String',
        json_key: 'mobile',
        required: false

      attribute :number_of_aliases,
        type: 'Integer',
        json_key: 'numberOfAliases',
        required: false

      attribute :office,
        type: 'String',
        json_key: 'office',
        required: false

      attribute :outlook_license,
        type: 'Boolean',
        json_key: 'outlookLicense',
        required: false

      attribute :owa_limited,
        type: 'Boolean',
        json_key: 'owaLimited',
        required: false

      attribute :password_last_update,
        type: 'Time',
        json_key: 'passwordLastUpdate',
        required: false

      attribute :phone,
        type: 'String',
        json_key: 'phone',
        required: false

      attribute :postal_code,
        type: 'String',
        json_key: 'postalCode',
        required: false

      attribute :primary_email_address,
        type: 'String',
        json_key: 'primaryEmailAddress',
        required: false

      attribute :quota,
        type: 'Integer',
        json_key: 'quota',
        required: false

      attribute :region,
        type: 'String',
        json_key: 'region',
        required: false

      attribute :renew_outlook_period,
        type: 'EmailExchangeRenewPeriodEnum',
        json_key: 'renewOutlookPeriod',
        required: false

      attribute :renew_period,
        type: 'EmailExchangeRenewPeriodEnum',
        json_key: 'renewPeriod',
        required: false

      attribute :sbr_destination,
        type: 'String',
        json_key: 'sbrDestination',
        required: false

      attribute :send_connector_id,
        type: 'Integer',
        json_key: 'sendConnectorId',
        required: false

      attribute :spam_and_virus_configuration,
        type: 'EmailExchangeSpamAndVirusConfiguration',
        json_key: 'spamAndVirusConfiguration',
        required: false

      attribute :spam_detected,
        type: 'Boolean',
        json_key: 'spamDetected',
        required: false

      attribute :spam_ticket_number,
        type: 'Integer',
        json_key: 'spamTicketNumber',
        required: false

      attribute :state,
        type: 'EmailExchangeObjectStateEnum',
        json_key: 'state',
        required: false

      attribute :store_copy_of_email,
        type: 'Boolean',
        json_key: 'storeCopyOfEmail',
        required: false

      attribute :street_address,
        type: 'String',
        json_key: 'streetAddress',
        required: false

      attribute :task_pending_id,
        type: 'Integer',
        json_key: 'taskPendingId',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
