# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    class EmailDomainResponderAccount
      include Ovh::Api::Serializable
      include Ovh::Api::Validations

      attribute :account,
        type: 'String',
        json_key: 'account',
        required: false

      attribute :content,
        type: 'String',
        json_key: 'content',
        required: false

      attribute :copy,
        type: 'Boolean',
        json_key: 'copy',
        required: false

      attribute :copy_to,
        type: 'String',
        json_key: 'copyTo',
        required: false

      attribute :from,
        type: 'Time',
        json_key: 'from',
        required: false

      attribute :to,
        type: 'Time',
        json_key: 'to',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
