# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    class EmailExchangeSendConnector
      include Ovh::Api::Serializable
      include Ovh::Api::Validations

      attribute :creation_date,
        type: 'Time',
        json_key: 'creationDate',
        required: false

      attribute :default,
        type: 'Boolean',
        json_key: 'default',
        required: false

      attribute :display_name,
        type: 'String',
        json_key: 'displayName',
        required: false

      attribute :dns_routing,
        type: 'Boolean',
        json_key: 'dnsRouting',
        required: false

      attribute :id,
        type: 'Integer',
        json_key: 'id',
        required: false

      attribute :last_update_date,
        type: 'Time',
        json_key: 'lastUpdateDate',
        required: false

      attribute :max_send_size,
        type: 'Integer',
        json_key: 'maxSendSize',
        required: false

      attribute :port,
        type: 'Integer',
        json_key: 'port',
        required: false

      attribute :require_tls,
        type: 'Boolean',
        json_key: 'requireTLS',
        required: false

      attribute :smart_host,
        type: 'String',
        json_key: 'smartHost',
        required: false

      attribute :smart_host_auth_mechanism,
        type: 'EmailExchangeSmartHostAuthMechanismEnum',
        json_key: 'smartHostAuthMechanism',
        required: false

      attribute :state,
        type: 'EmailExchangeObjectStateEnum',
        json_key: 'state',
        required: false

      attribute :task_pending_id,
        type: 'Integer',
        json_key: 'taskPendingId',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
