# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    class EmailDomainDelegatedAccountEmailFilterPostRequest
      include Ovh::Api::Serializable
      include Ovh::Api::Validations

      attribute :action,
        type: 'DomainDomainFilterActionEnum',
        json_key: 'action',
        required: true

      attribute :action_param,
        type: 'String',
        json_key: 'actionParam',
        required: false

      attribute :active,
        type: 'Boolean',
        json_key: 'active',
        required: true

      attribute :header,
        type: 'String',
        json_key: 'header',
        required: true

      attribute :name,
        type: 'String',
        json_key: 'name',
        required: true

      attribute :operand,
        type: 'DomainDomainFilterOperandEnum',
        json_key: 'operand',
        required: true

      attribute :priority,
        type: 'Integer',
        json_key: 'priority',
        required: true

      attribute :value,
        type: 'String',
        json_key: 'value',
        required: true

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
