# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    class EmailExchangeOrganizationNameServiceExchangeServiceAccoHb745f885
      include Ovh::Api::Serializable
      include Ovh::Api::Validations

      attribute :sam_account_name,
        type: 'String',
        json_key: 'SAMAccountName',
        required: false

      attribute :authentication_policy_id,
        type: 'Integer',
        json_key: 'authenticationPolicyId',
        required: false

      attribute :city,
        type: 'String',
        json_key: 'city',
        required: false

      attribute :company,
        type: 'String',
        json_key: 'company',
        required: false

      attribute :country_code,
        type: 'EmailExchangeCountryCodeEnum',
        json_key: 'countryCode',
        required: false

      attribute :description,
        type: 'String',
        json_key: 'description',
        required: false

      attribute :display_name,
        type: 'String',
        json_key: 'displayName',
        required: false

      attribute :domain,
        type: 'String',
        json_key: 'domain',
        required: true

      attribute :fax,
        type: 'String',
        json_key: 'fax',
        required: false

      attribute :first_name,
        type: 'String',
        json_key: 'firstName',
        required: false

      attribute :forwarding_email,
        type: 'String',
        json_key: 'forwardingEmail',
        required: false

      attribute :hidden_from_gal,
        type: 'Boolean',
        json_key: 'hiddenFromGAL',
        required: false

      attribute :initials,
        type: 'String',
        json_key: 'initials',
        required: false

      attribute :job_department,
        type: 'String',
        json_key: 'jobDepartment',
        required: false

      attribute :job_title,
        type: 'String',
        json_key: 'jobTitle',
        required: false

      attribute :last_name,
        type: 'String',
        json_key: 'lastName',
        required: false

      attribute :license,
        type: 'EmailExchangeOvhLicenceEnum',
        json_key: 'license',
        required: true

      attribute :litigation,
        type: 'Boolean',
        json_key: 'litigation',
        required: false

      attribute :litigation_period,
        type: 'Integer',
        json_key: 'litigationPeriod',
        required: false

      attribute :login,
        type: 'String',
        json_key: 'login',
        required: true

      attribute :mail_sender_display,
        type: 'String',
        json_key: 'mailSenderDisplay',
        required: false

      attribute :mailing_filter,
        type: 'Array<EmailExchangeMailingFilterEnum>',
        json_key: 'mailingFilter',
        required: false

      attribute :mobile,
        type: 'String',
        json_key: 'mobile',
        required: false

      attribute :office,
        type: 'String',
        json_key: 'office',
        required: false

      attribute :outlook_license,
        type: 'Boolean',
        json_key: 'outlookLicense',
        required: false

      attribute :password,
        type: 'String',
        json_key: 'password',
        required: true

      attribute :phone,
        type: 'String',
        json_key: 'phone',
        required: false

      attribute :postal_code,
        type: 'String',
        json_key: 'postalCode',
        required: false

      attribute :quota,
        type: 'Integer',
        json_key: 'quota',
        required: false

      attribute :region,
        type: 'String',
        json_key: 'region',
        required: false

      attribute :sbr_destination,
        type: 'String',
        json_key: 'sbrDestination',
        required: false

      attribute :send_connector_id,
        type: 'Integer',
        json_key: 'sendConnectorId',
        required: false

      attribute :spam_and_virus_configuration,
        type: 'EmailExchangeSpamAndVirusConfiguration',
        json_key: 'spamAndVirusConfiguration',
        required: false

      attribute :store_copy_of_email,
        type: 'Boolean',
        json_key: 'storeCopyOfEmail',
        required: false

      attribute :street_address,
        type: 'String',
        json_key: 'streetAddress',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
