# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    class EmailDomainDomainMailingListPostRequest
      include Ovh::Api::Serializable
      include Ovh::Api::Validations

      attribute :language,
        type: 'DomainDomainMlLanguageEnum',
        json_key: 'language',
        required: true

      attribute :name,
        type: 'String',
        json_key: 'name',
        required: true

      attribute :options,
        type: 'DomainDomainMlOptionsStruct',
        json_key: 'options',
        required: true

      attribute :owner_email,
        type: 'String',
        json_key: 'ownerEmail',
        required: true

      attribute :reply_to,
        type: 'String',
        json_key: 'replyTo',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
