# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    class EmailExchangeExchangeRemoteMailbox
      include Ovh::Api::Serializable
      include Ovh::Api::Validations

      attribute :sam_account_name,
        type: 'String',
        json_key: 'SAMAccountName',
        required: false

      attribute :city,
        type: 'String',
        json_key: 'city',
        required: false

      attribute :company,
        type: 'String',
        json_key: 'company',
        required: false

      attribute :country_code,
        type: 'EmailExchangeCountryCodeEnum',
        json_key: 'countryCode',
        required: false

      attribute :creation_date,
        type: 'Time',
        json_key: 'creationDate',
        required: false

      attribute :description,
        type: 'String',
        json_key: 'description',
        required: false

      attribute :display_name,
        type: 'String',
        json_key: 'displayName',
        required: false

      attribute :domain,
        type: 'String',
        json_key: 'domain',
        required: false

      attribute :exchange_guid,
        type: 'String',
        json_key: 'exchangeGuid',
        required: false

      attribute :fax,
        type: 'String',
        json_key: 'fax',
        required: false

      attribute :first_name,
        type: 'String',
        json_key: 'firstName',
        required: false

      attribute :guid,
        type: 'String',
        json_key: 'guid',
        required: false

      attribute :hidden_from_gal,
        type: 'Boolean',
        json_key: 'hiddenFromGAL',
        required: false

      attribute :id,
        type: 'Integer',
        json_key: 'id',
        required: false

      attribute :initial,
        type: 'String',
        json_key: 'initial',
        required: false

      attribute :job_department,
        type: 'String',
        json_key: 'jobDepartment',
        required: false

      attribute :job_title,
        type: 'String',
        json_key: 'jobTitle',
        required: false

      attribute :last_name,
        type: 'String',
        json_key: 'lastName',
        required: false

      attribute :login,
        type: 'String',
        json_key: 'login',
        required: false

      attribute :mobile,
        type: 'String',
        json_key: 'mobile',
        required: false

      attribute :number_of_aliases,
        type: 'Integer',
        json_key: 'numberOfAliases',
        required: false

      attribute :office,
        type: 'String',
        json_key: 'office',
        required: false

      attribute :phone,
        type: 'String',
        json_key: 'phone',
        required: false

      attribute :postal_code,
        type: 'String',
        json_key: 'postalCode',
        required: false

      attribute :primary_email_address,
        type: 'String',
        json_key: 'primaryEmailAddress',
        required: false

      attribute :region,
        type: 'String',
        json_key: 'region',
        required: false

      attribute :remote_routing_address,
        type: 'String',
        json_key: 'remoteRoutingAddress',
        required: false

      attribute :spam_and_virus_configuration,
        type: 'EmailExchangeSpamAndVirusConfiguration',
        json_key: 'spamAndVirusConfiguration',
        required: false

      attribute :state,
        type: 'EmailExchangeObjectStateEnum',
        json_key: 'state',
        required: false

      attribute :street_address,
        type: 'String',
        json_key: 'streetAddress',
        required: false

      attribute :task_pending_id,
        type: 'Integer',
        json_key: 'taskPendingId',
        required: false

      attribute :type,
        type: 'EmailExchangeExchangeRemoteMailboxTypeEnum',
        json_key: 'type',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
