# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    class EmailExchangeSharedAccount
      include Ovh::Api::Serializable
      include Ovh::Api::Validations

      attribute :creation_date,
        type: 'Time',
        json_key: 'creationDate',
        required: false

      attribute :current_usage,
        type: 'Integer',
        json_key: 'currentUsage',
        required: false

      attribute :display_name,
        type: 'String',
        json_key: 'displayName',
        required: false

      attribute :first_name,
        type: 'String',
        json_key: 'firstName',
        required: false

      attribute :hidden_from_gal,
        type: 'Boolean',
        json_key: 'hiddenFromGAL',
        required: false

      attribute :id,
        type: 'Integer',
        json_key: 'id',
        required: false

      attribute :initials,
        type: 'String',
        json_key: 'initials',
        required: false

      attribute :last_logoff_date,
        type: 'Time',
        json_key: 'lastLogoffDate',
        required: false

      attribute :last_logon_date,
        type: 'Time',
        json_key: 'lastLogonDate',
        required: false

      attribute :last_name,
        type: 'String',
        json_key: 'lastName',
        required: false

      attribute :mailing_filter,
        type: 'Array<EmailExchangeMailingFilterEnum>',
        json_key: 'mailingFilter',
        required: false

      attribute :quota,
        type: 'Integer',
        json_key: 'quota',
        required: false

      attribute :shared_email_address,
        type: 'String',
        json_key: 'sharedEmailAddress',
        required: false

      attribute :spam_detected,
        type: 'Boolean',
        json_key: 'spamDetected',
        required: false

      attribute :spam_ticket_number,
        type: 'Integer',
        json_key: 'spamTicketNumber',
        required: false

      attribute :state,
        type: 'EmailExchangeObjectStateEnum',
        json_key: 'state',
        required: false

      attribute :task_pending_id,
        type: 'Integer',
        json_key: 'taskPendingId',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
