# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    class EmailExchangeMailingList
      include Ovh::Api::Serializable
      include Ovh::Api::Validations

      attribute :company,
        type: 'String',
        json_key: 'company',
        required: false

      attribute :creation_date,
        type: 'Time',
        json_key: 'creationDate',
        required: false

      attribute :depart_restriction,
        type: 'EmailExchangeMailingListDepartRestrictionEnum',
        json_key: 'departRestriction',
        required: false

      attribute :display_name,
        type: 'String',
        json_key: 'displayName',
        required: false

      attribute :hidden_from_gal,
        type: 'Boolean',
        json_key: 'hiddenFromGAL',
        required: false

      attribute :join_restriction,
        type: 'EmailExchangeMailingListJoinRestrictionEnum',
        json_key: 'joinRestriction',
        required: false

      attribute :last_update_date,
        type: 'Time',
        json_key: 'lastUpdateDate',
        required: false

      attribute :mailing_list_address,
        type: 'String',
        json_key: 'mailingListAddress',
        required: false

      attribute :max_receive_size,
        type: 'Integer',
        json_key: 'maxReceiveSize',
        required: false

      attribute :max_send_size,
        type: 'Integer',
        json_key: 'maxSendSize',
        required: false

      attribute :sender_authentification,
        type: 'Boolean',
        json_key: 'senderAuthentification',
        required: false

      attribute :spam_detected,
        type: 'Boolean',
        json_key: 'spamDetected',
        required: false

      attribute :spam_ticket_number,
        type: 'Integer',
        json_key: 'spamTicketNumber',
        required: false

      attribute :state,
        type: 'EmailExchangeObjectStateEnum',
        json_key: 'state',
        required: false

      attribute :task_pending_id,
        type: 'Integer',
        json_key: 'taskPendingId',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
