# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    class EmailExchangeDomain
      include Ovh::Api::Serializable
      include Ovh::Api::Validations

      attribute :cname_to_check,
        type: 'String',
        json_key: 'cnameToCheck',
        required: false

      attribute :dkim_diagnostics,
        type: 'EmailExchangeDomainDkimDiagnostics',
        json_key: 'dkimDiagnostics',
        required: false

      attribute :domain_aliases,
        type: 'Array<Object>',
        json_key: 'domainAliases',
        required: false

      attribute :domain_validated,
        type: 'Boolean',
        json_key: 'domainValidated',
        required: false

      attribute :expected_autodiscover_srv,
        type: 'String',
        json_key: 'expectedAutodiscoverSRV',
        required: false

      attribute :expected_mx,
        type: 'Array<Object>',
        json_key: 'expectedMX',
        required: false

      attribute :expected_spf,
        type: 'String',
        json_key: 'expectedSPF',
        required: false

      attribute :is_alias_domain,
        type: 'Boolean',
        json_key: 'isAliasDomain',
        required: false

      attribute :main,
        type: 'Boolean',
        json_key: 'main',
        required: false

      attribute :mx_is_valid,
        type: 'Boolean',
        json_key: 'mxIsValid',
        required: false

      attribute :mx_record,
        type: 'Array<Object>',
        json_key: 'mxRecord',
        required: false

      attribute :mx_relay,
        type: 'String',
        json_key: 'mxRelay',
        required: false

      attribute :name,
        type: 'String',
        json_key: 'name',
        required: false

      attribute :organization2010,
        type: 'String',
        json_key: 'organization2010',
        required: false

      attribute :sbr_default,
        type: 'String',
        json_key: 'sbrDefault',
        required: false

      attribute :send_connector_id_default,
        type: 'Integer',
        json_key: 'sendConnectorIdDefault',
        required: false

      attribute :spf_is_valid,
        type: 'Boolean',
        json_key: 'spfIsValid',
        required: false

      attribute :spf_record,
        type: 'Array<Object>',
        json_key: 'spfRecord',
        required: false

      attribute :srv_is_valid,
        type: 'Boolean',
        json_key: 'srvIsValid',
        required: false

      attribute :srv_record,
        type: 'Array<Object>',
        json_key: 'srvRecord',
        required: false

      attribute :state,
        type: 'EmailExchangeObjectStateEnum',
        json_key: 'state',
        required: false

      attribute :task_pending_id,
        type: 'Integer',
        json_key: 'taskPendingId',
        required: false

      attribute :type,
        type: 'EmailExchangeDomainTypeEnum',
        json_key: 'type',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
