# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    class EmailExchangePublicFolder
      include Ovh::Api::Serializable
      include Ovh::Api::Validations

      attribute :anonymous_permission,
        type: 'EmailExchangePublicFolderRightTypeEnum',
        json_key: 'anonymousPermission',
        required: false

      attribute :creation_date,
        type: 'Time',
        json_key: 'creationDate',
        required: false

      attribute :default_permission,
        type: 'EmailExchangePublicFolderRightTypeEnum',
        json_key: 'defaultPermission',
        required: false

      attribute :has_sub_folders,
        type: 'Boolean',
        json_key: 'hasSubFolders',
        required: false

      attribute :item_count,
        type: 'Integer',
        json_key: 'itemCount',
        required: false

      attribute :last_access_time,
        type: 'Time',
        json_key: 'lastAccessTime',
        required: false

      attribute :last_modification_time,
        type: 'Time',
        json_key: 'lastModificationTime',
        required: false

      attribute :last_user_access_time,
        type: 'Time',
        json_key: 'lastUserAccessTime',
        required: false

      attribute :last_user_modification_time,
        type: 'Time',
        json_key: 'lastUserModificationTime',
        required: false

      attribute :path,
        type: 'String',
        json_key: 'path',
        required: false

      attribute :quota,
        type: 'Integer',
        json_key: 'quota',
        required: false

      attribute :state,
        type: 'EmailExchangeObjectStateEnum',
        json_key: 'state',
        required: false

      attribute :task_pending_id,
        type: 'Integer',
        json_key: 'taskPendingId',
        required: false

      attribute :total_item_size,
        type: 'Integer',
        json_key: 'totalItemSize',
        required: false

      attribute :type,
        type: 'EmailExchangePublicFolderTypeEnum',
        json_key: 'type',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
