# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    module EmailExchangeShowMeetingDetailsEnum
      AVAILABILITY_ONLY = 'availabilityOnly'
      LIMITED_DETAILS = 'limitedDetails'
      REVIEWER = 'reviewer'

      def self.all
        @all ||= [
          AVAILABILITY_ONLY,
          LIMITED_DETAILS,
          REVIEWER,
        ].freeze
      end

      def self.valid?(value)
        all.include?(value)
      end
    end
  end
end
