# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    class EmailExchangeOrganizationNameServiceExchangeServiceChanHe51654b9
      include Ovh::Api::Serializable
      include Ovh::Api::Validations

      attribute :dcv_email,
        type: 'String',
        json_key: 'dcvEmail',
        required: false

      attribute :hostname,
        type: 'String',
        json_key: 'hostname',
        required: true

      attribute :use_cname,
        type: 'Boolean',
        json_key: 'useCname',
        required: false

      attribute :use_dns_assist,
        type: 'Boolean',
        json_key: 'useDnsAssist',
        required: true

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
