# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    module EmailExchangeExchangeCommercialVersionEnum
      N2010 = '2010'
      N2013 = '2013'
      N2016 = '2016'
      N2019 = '2019'
      SE = 'SE'

      def self.all
        @all ||= [
          N2010,
          N2013,
          N2016,
          N2019,
          SE,
        ].freeze
      end

      def self.valid?(value)
        all.include?(value)
      end
    end
  end
end
