# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    module EmailExchangeDeviceActiveSyncStateEnum
      ALLOWED = 'allowed'
      BLOCKED = 'blocked'
      DEVICE_DISCOVERY = 'deviceDiscovery'
      QUARANTINED = 'quarantined'

      def self.all
        @all ||= [
          ALLOWED,
          BLOCKED,
          DEVICE_DISCOVERY,
          QUARANTINED,
        ].freeze
      end

      def self.valid?(value)
        all.include?(value)
      end
    end
  end
end
