# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    class EmailExchangeResourceAccount
      include Ovh::Api::Serializable
      include Ovh::Api::Validations

      attribute :add_organizer_to_subject,
        type: 'Boolean',
        json_key: 'addOrganizerToSubject',
        required: false

      attribute :allow_conflict,
        type: 'Boolean',
        json_key: 'allowConflict',
        required: false

      attribute :booking_window,
        type: 'Integer',
        json_key: 'bookingWindow',
        required: false

      attribute :capacity,
        type: 'Integer',
        json_key: 'capacity',
        required: false

      attribute :company,
        type: 'String',
        json_key: 'company',
        required: false

      attribute :creation_date,
        type: 'Time',
        json_key: 'creationDate',
        required: false

      attribute :delete_comments,
        type: 'Boolean',
        json_key: 'deleteComments',
        required: false

      attribute :delete_subject,
        type: 'Boolean',
        json_key: 'deleteSubject',
        required: false

      attribute :display_name,
        type: 'String',
        json_key: 'displayName',
        required: false

      attribute :location,
        type: 'String',
        json_key: 'location',
        required: false

      attribute :maximum_duration,
        type: 'Integer',
        json_key: 'maximumDuration',
        required: false

      attribute :resource_email_address,
        type: 'String',
        json_key: 'resourceEmailAddress',
        required: false

      attribute :show_meeting_details,
        type: 'EmailExchangeShowMeetingDetailsEnum',
        json_key: 'showMeetingDetails',
        required: false

      attribute :state,
        type: 'EmailExchangeObjectStateEnum',
        json_key: 'state',
        required: false

      attribute :task_pending_id,
        type: 'Integer',
        json_key: 'taskPendingId',
        required: false

      attribute :type,
        type: 'EmailExchangeResourceTypeEnum',
        json_key: 'type',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
