# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    class EmailProSpamAndVirusConfiguration
      include Ovh::Api::Serializable
      include Ovh::Api::Validations

      attribute :check_dkim,
        type: 'Boolean',
        json_key: 'checkDKIM',
        required: false

      attribute :check_spf,
        type: 'Boolean',
        json_key: 'checkSPF',
        required: false

      attribute :delete_spam,
        type: 'Boolean',
        json_key: 'deleteSpam',
        required: false

      attribute :delete_virus,
        type: 'Boolean',
        json_key: 'deleteVirus',
        required: false

      attribute :put_in_junk,
        type: 'Boolean',
        json_key: 'putInJunk',
        required: false

      attribute :tag_spam,
        type: 'Boolean',
        json_key: 'tagSpam',
        required: false

      attribute :tag_virus,
        type: 'Boolean',
        json_key: 'tagVirus',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
