# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    module EmailExchangeDomainDkimDiagnosticsStateEnum
      ACTIVE = 'active'
      DISABLED = 'disabled'
      ERROR = 'error'
      IN_PROGRESS = 'inProgress'
      TO_CONFIGURE = 'toConfigure'

      def self.all
        @all ||= [
          ACTIVE,
          DISABLED,
          ERROR,
          IN_PROGRESS,
          TO_CONFIGURE,
        ].freeze
      end

      def self.valid?(value)
        all.include?(value)
      end
    end
  end
end
