# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    class HorizonViewServiceNameAccessPointPostRequest
      include Ovh::Api::Serializable
      include Ovh::Api::Validations

      attribute :pool_type,
        type: 'HorizonViewPoolType',
        json_key: 'poolType',
        required: true

      attribute :private_block,
        type: 'String',
        json_key: 'privateBlock',
        required: false

      attribute :private_vlan,
        type: 'Integer',
        json_key: 'privateVlan',
        required: false

      attribute :vrouter_pool_public_ip,
        type: 'String',
        json_key: 'vrouterPoolPublicIp',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
