# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    module HorizonViewPoolType
      HYBRID_POOL = 'hybridPool'
      PRIVATE_POOL = 'privatePool'
      PUBLIC_POOL = 'publicPool'

      def self.all
        @all ||= [
          HYBRID_POOL,
          PRIVATE_POOL,
          PUBLIC_POOL,
        ].freeze
      end

      def self.valid?(value)
        all.include?(value)
      end
    end
  end
end
