# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    class HorizonViewServiceNameDomainTrustPostRequest
      include Ovh::Api::Serializable
      include Ovh::Api::Validations

      attribute :active_directory_ip,
        type: 'String',
        json_key: 'activeDirectoryIP',
        required: true

      attribute :dns1,
        type: 'String',
        json_key: 'dns1',
        required: false

      attribute :dns2,
        type: 'String',
        json_key: 'dns2',
        required: false

      attribute :domain,
        type: 'String',
        json_key: 'domain',
        required: true

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
