# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    class HostingWebServiceNameOvhConfigIdChangeConfigurationPostRequest
      include Ovh::Api::Serializable
      include Ovh::Api::Validations

      attribute :container,
        type: 'HostingWebOvhconfigContainerEnum',
        json_key: 'container',
        required: false

      attribute :engine_name,
        type: 'HostingWebOvhConfigEngineNameEnum',
        json_key: 'engineName',
        required: false

      attribute :engine_version,
        type: 'HostingWebOvhConfigAvailableEngineVersionEnum',
        json_key: 'engineVersion',
        required: false

      attribute :environment,
        type: 'HostingWebOvhConfigEnvironmentEnum',
        json_key: 'environment',
        required: false

      attribute :http_firewall,
        type: 'HostingWebOvhConfigHttpFirewallEnum',
        json_key: 'httpFirewall',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
