# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    module HostingPrivateDatabaseVersionEnum
      MARIADB_10_11 = 'mariadb_10.11'
      MARIADB_10_6 = 'mariadb_10.6'
      MARIADB_11_4 = 'mariadb_11.4'
      MARIADB_11_8 = 'mariadb_11.8'
      MYSQL_8_0 = 'mysql_8.0'
      MYSQL_8_4 = 'mysql_8.4'
      POSTGRESQL_14 = 'postgresql_14'
      POSTGRESQL_15 = 'postgresql_15'
      POSTGRESQL_16 = 'postgresql_16'
      POSTGRESQL_17 = 'postgresql_17'
      POSTGRESQL_18 = 'postgresql_18'
      VALKEY_7_2 = 'valkey_7.2'
      VALKEY_8_1 = 'valkey_8.1'
      VALKEY_9_1 = 'valkey_9.1'

      def self.all
        @all ||= [
          MARIADB_10_11,
          MARIADB_10_6,
          MARIADB_11_4,
          MARIADB_11_8,
          MYSQL_8_0,
          MYSQL_8_4,
          POSTGRESQL_14,
          POSTGRESQL_15,
          POSTGRESQL_16,
          POSTGRESQL_17,
          POSTGRESQL_18,
          VALKEY_7_2,
          VALKEY_8_1,
          VALKEY_9_1,
        ].freeze
      end

      def self.valid?(value)
        all.include?(value)
      end
    end
  end
end
