# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    module HostingWebDatabaseExtraSqlQuotaEnum
      N25 = '25'
      N100 = '100'
      N200 = '200'
      N256 = '256'
      N400 = '400'
      N512 = '512'
      N800 = '800'
      N1024 = '1024'

      def self.all
        @all ||= [
          N25,
          N100,
          N200,
          N256,
          N400,
          N512,
          N800,
          N1024,
        ].freeze
      end

      def self.valid?(value)
        all.include?(value)
      end
    end
  end
end
