# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    module HostingPrivateDatabaseStateEnum
      DETACHED = 'detached'
      RESTART_PENDING = 'restartPending'
      START_PENDING = 'startPending'
      STARTED = 'started'
      STOP_PENDING = 'stopPending'
      STOPPED = 'stopped'

      def self.all
        @all ||= [
          DETACHED,
          RESTART_PENDING,
          START_PENDING,
          STARTED,
          STOP_PENDING,
          STOPPED,
        ].freeze
      end

      def self.valid?(value)
        all.include?(value)
      end
    end
  end
end
