# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    class HostingWebUserCredentials
      include Ovh::Api::Serializable
      include Ovh::Api::Validations

      attribute :port,
        type: 'Integer',
        json_key: 'port',
        required: false

      attribute :url,
        type: 'String',
        json_key: 'url',
        required: false

      attribute :user,
        type: 'String',
        json_key: 'user',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
