# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    module HostingWebEnvVarStatusEnum
      CREATED = 'created'
      CREATING = 'creating'
      DELETING = 'deleting'
      UPDATING = 'updating'

      def self.all
        @all ||= [
          CREATED,
          CREATING,
          DELETING,
          UPDATING,
        ].freeze
      end

      def self.valid?(value)
        all.include?(value)
      end
    end
  end
end
