# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    class HostingWebEnvVar
      include Ovh::Api::Serializable
      include Ovh::Api::Validations

      attribute :key,
        type: 'String',
        json_key: 'key',
        required: false

      attribute :status,
        type: 'HostingWebEnvVarStatusEnum',
        json_key: 'status',
        required: false

      attribute :task_id,
        type: 'Integer',
        json_key: 'taskId',
        required: false

      attribute :type,
        type: 'HostingWebEnvVarTypeEnum',
        json_key: 'type',
        required: false

      attribute :value,
        type: 'String',
        json_key: 'value',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
