# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    module HostingWebStateEnum
      ACTIVE = 'active'
      BLOCKED = 'blocked'
      BLOQUED = 'bloqued'
      HARD_BLOCKED = 'hardBlocked'
      HARD_BLOQUED = 'hardBloqued'
      MAINTENANCE = 'maintenance'

      def self.all
        @all ||= [
          ACTIVE,
          BLOCKED,
          BLOQUED,
          HARD_BLOCKED,
          HARD_BLOQUED,
          MAINTENANCE,
        ].freeze
      end

      def self.valid?(value)
        all.include?(value)
      end
    end
  end
end
