# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    module HostingWebOvhConfigAvailableEngineVersionEnum
      N5_4 = '5.4'
      N5_5 = '5.5'
      N5_6 = '5.6'
      N7_0 = '7.0'
      N7_1 = '7.1'
      N7_2 = '7.2'
      N7_3 = '7.3'
      N7_4 = '7.4'
      N8_0 = '8.0'
      N8_1 = '8.1'
      N8_2 = '8.2'
      N8_3 = '8.3'
      N8_4 = '8.4'
      N8_5 = '8.5'

      def self.all
        @all ||= [
          N5_4,
          N5_5,
          N5_6,
          N7_0,
          N7_1,
          N7_2,
          N7_3,
          N7_4,
          N8_0,
          N8_1,
          N8_2,
          N8_3,
          N8_4,
          N8_5,
        ].freeze
      end

      def self.valid?(value)
        all.include?(value)
      end
    end
  end
end
