# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    module HostingPrivateDatabaseDatacenterEnum
      BHS1 = 'bhs1'
      GRA1 = 'gra1'
      GRA2 = 'gra2'
      GRA3 = 'gra3'

      def self.all
        @all ||= [
          BHS1,
          GRA1,
          GRA2,
          GRA3,
        ].freeze
      end

      def self.valid?(value)
        all.include?(value)
      end
    end
  end
end
