# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    class HostingPrivateDatabaseWhitelistCreatePayload
      include Ovh::Api::Serializable
      include Ovh::Api::Validations

      attribute :ip,
        type: 'String',
        json_key: 'ip',
        required: true

      attribute :name,
        type: 'String',
        json_key: 'name',
        required: false

      attribute :service,
        type: 'Boolean',
        json_key: 'service',
        required: false

      attribute :sftp,
        type: 'Boolean',
        json_key: 'sftp',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
