# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    class HostingPrivateDatabaseService
      include Ovh::Api::Serializable
      include Ovh::Api::Validations

      attribute :capabilities,
        type: 'Array<HostingPrivateDatabaseCapability>',
        json_key: 'capabilities',
        required: false

      attribute :cpu,
        type: 'Integer',
        json_key: 'cpu',
        required: false

      attribute :datacenter,
        type: 'HostingPrivateDatabaseDatacenterEnum',
        json_key: 'datacenter',
        required: false

      attribute :display_name,
        type: 'String',
        json_key: 'displayName',
        required: false

      attribute :graph_endpoint,
        type: 'HostingPrivateDatabaseGraphEndpoint',
        json_key: 'graphEndpoint',
        required: false

      attribute :gui_url,
        type: 'String',
        json_key: 'guiURL',
        required: false

      attribute :hostname,
        type: 'String',
        json_key: 'hostname',
        required: false

      attribute :hostname_ftp,
        type: 'String',
        json_key: 'hostnameFtp',
        required: false

      attribute :infrastructure,
        type: 'HostingPrivateDatabaseInfrastructureEnum',
        json_key: 'infrastructure',
        required: false

      attribute :ip,
        type: 'String',
        json_key: 'ip',
        required: false

      attribute :is_under_maintenance,
        type: 'Boolean',
        json_key: 'isUnderMaintenance',
        required: false

      attribute :last_check,
        type: 'Time',
        json_key: 'lastCheck',
        required: false

      attribute :offer,
        type: 'HostingPrivateDatabaseOfferEnum',
        json_key: 'offer',
        required: false

      attribute :port,
        type: 'Integer',
        json_key: 'port',
        required: false

      attribute :port_ftp,
        type: 'Integer',
        json_key: 'portFtp',
        required: false

      attribute :quota_size,
        type: 'ComplexTypeUnitAndValueLong',
        json_key: 'quotaSize',
        required: false

      attribute :quota_used,
        type: 'ComplexTypeUnitAndValueLong',
        json_key: 'quotaUsed',
        required: false

      attribute :ram,
        type: 'ComplexTypeUnitAndValueLong',
        json_key: 'ram',
        required: false

      attribute :server,
        type: 'String',
        json_key: 'server',
        required: false

      attribute :service_name,
        type: 'String',
        json_key: 'serviceName',
        required: false

      attribute :state,
        type: 'HostingPrivateDatabaseStateEnum',
        json_key: 'state',
        required: false

      attribute :tls_ca,
        type: 'String',
        json_key: 'tlsCa',
        required: false

      attribute :type,
        type: 'HostingPrivateDatabaseTypeEnum',
        json_key: 'type',
        required: false

      attribute :version,
        type: 'HostingPrivateDatabaseVersionEnum',
        json_key: 'version',
        required: false

      attribute :version_label,
        type: 'String',
        json_key: 'versionLabel',
        required: false

      attribute :version_number,
        type: 'Float',
        json_key: 'versionNumber',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
