# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    module HostingWebCountryEnum
      BE = 'BE'
      CA = 'CA'
      CZ = 'CZ'
      DE = 'DE'
      ES = 'ES'
      FI = 'FI'
      FR = 'FR'
      IE = 'IE'
      IT = 'IT'
      LT = 'LT'
      NL = 'NL'
      PL = 'PL'
      PT = 'PT'
      UK = 'UK'

      def self.all
        @all ||= [
          BE,
          CA,
          CZ,
          DE,
          ES,
          FI,
          FR,
          IE,
          IT,
          LT,
          NL,
          PL,
          PT,
          UK,
        ].freeze
      end

      def self.valid?(value)
        all.include?(value)
      end
    end
  end
end
