# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    module IpGameMitigationStateEnum
      CLEAN_RULES_PENDING = 'cleanRulesPending'
      FIREWALL_MODE_DISABLE_PENDING = 'firewallModeDisablePending'
      FIREWALL_MODE_ENABLE_PENDING = 'firewallModeEnablePending'
      OK = 'ok'

      def self.all
        @all ||= [
          CLEAN_RULES_PENDING,
          FIREWALL_MODE_DISABLE_PENDING,
          FIREWALL_MODE_ENABLE_PENDING,
          OK,
        ].freeze
      end

      def self.valid?(value)
        all.include?(value)
      end
    end
  end
end
