# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    class IpIpFirewallIpOnFirewallRulePostRequest
      include Ovh::Api::Serializable
      include Ovh::Api::Validations

      attribute :action,
        type: 'IpFirewallActionEnum',
        json_key: 'action',
        required: true

      attribute :destination_port,
        type: 'Integer',
        json_key: 'destinationPort',
        required: false

      attribute :destination_port_range,
        type: 'ComplexTypeRangeLong',
        json_key: 'destinationPortRange',
        required: false

      attribute :l3_packet_length,
        type: 'ComplexTypeRangeLong',
        json_key: 'l3PacketLength',
        required: false

      attribute :protocol,
        type: 'IpFirewallProtocolEnum',
        json_key: 'protocol',
        required: true

      attribute :sequence,
        type: 'IpFirewallSequenceRangeEnum',
        json_key: 'sequence',
        required: true

      attribute :source,
        type: 'String',
        json_key: 'source',
        required: false

      attribute :source_port,
        type: 'Integer',
        json_key: 'sourcePort',
        required: false

      attribute :source_port_range,
        type: 'ComplexTypeRangeLong',
        json_key: 'sourcePortRange',
        required: false

      attribute :tcp_option,
        type: 'IpFirewallOptionTCP',
        json_key: 'tcpOption',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
