# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    class IpLoadbalancingBackendProbe
      include Ovh::Api::Serializable
      include Ovh::Api::Validations

      attribute :force_ssl,
        type: 'Boolean',
        json_key: 'forceSsl',
        required: false

      attribute :interval,
        type: 'Integer',
        json_key: 'interval',
        required: false

      attribute :match,
        type: 'IpLoadbalancingProbeExpectMatchEnum',
        json_key: 'match',
        required: false

      attribute :method,
        type: 'IpLoadbalancingProbeMethodEnum',
        json_key: 'method',
        required: false

      attribute :negate,
        type: 'Boolean',
        json_key: 'negate',
        required: false

      attribute :pattern,
        type: 'String',
        json_key: 'pattern',
        required: false

      attribute :port,
        type: 'Integer',
        json_key: 'port',
        required: false

      attribute :type,
        type: 'IpLoadbalancingProbeTypeEnum',
        json_key: 'type',
        required: false

      attribute :url,
        type: 'String',
        json_key: 'url',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
