# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    module IpLoadbalancingRouteRuleMatchesEnum
      CONTAINS = 'contains'
      ENDSWITH = 'endswith'
      EXISTS = 'exists'
      IN = 'in'
      INTERNAL = 'internal'
      IS = 'is'
      MATCHES = 'matches'
      STARTSWITH = 'startswith'

      def self.all
        @all ||= [
          CONTAINS,
          ENDSWITH,
          EXISTS,
          IN,
          INTERNAL,
          IS,
          MATCHES,
          STARTSWITH,
        ].freeze
      end

      def self.valid?(value)
        all.include?(value)
      end
    end
  end
end
