# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    module IpLoadbalancingProbeExpectMatchEnum
      CONTAINS = 'contains'
      DEFAULT = 'default'
      INTERNAL = 'internal'
      MATCHES = 'matches'
      STATUS = 'status'

      def self.all
        @all ||= [
          CONTAINS,
          DEFAULT,
          INTERNAL,
          MATCHES,
          STATUS,
        ].freeze
      end

      def self.valid?(value)
        all.include?(value)
      end
    end
  end
end
