# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    class IpLoadbalancingServerState
      include Ovh::Api::Serializable
      include Ovh::Api::Validations

      attribute :check_code,
        type: 'String',
        json_key: 'checkCode',
        required: false

      attribute :check_status,
        type: 'String',
        json_key: 'checkStatus',
        required: false

      attribute :check_time,
        type: 'Time',
        json_key: 'checkTime',
        required: false

      attribute :instance_id,
        type: 'Integer',
        json_key: 'instanceId',
        required: false

      attribute :last_check_content,
        type: 'String',
        json_key: 'lastCheckContent',
        required: false

      attribute :status,
        type: 'String',
        json_key: 'status',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
