# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    module IpLoadbalancingProbeTypeEnum
      HTTP = 'http'
      INTERNAL = 'internal'
      MYSQL = 'mysql'
      OCO = 'oco'
      PGSQL = 'pgsql'
      SMTP = 'smtp'
      TCP = 'tcp'

      def self.all
        @all ||= [
          HTTP,
          INTERNAL,
          MYSQL,
          OCO,
          PGSQL,
          SMTP,
          TCP,
        ].freeze
      end

      def self.valid?(value)
        all.include?(value)
      end
    end
  end
end
