# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    class IpLoadbalancingServiceNameUdpFarmPostRequest
      include Ovh::Api::Serializable
      include Ovh::Api::Validations

      attribute :display_name,
        type: 'String',
        json_key: 'displayName',
        required: false

      attribute :port,
        type: 'Integer',
        json_key: 'port',
        required: true

      attribute :vrack_network_id,
        type: 'Integer',
        json_key: 'vrackNetworkId',
        required: false

      attribute :zone,
        type: 'String',
        json_key: 'zone',
        required: true

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
