# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    class IpLoadbalancingSslSsl
      include Ovh::Api::Serializable
      include Ovh::Api::Validations

      attribute :display_name,
        type: 'String',
        json_key: 'displayName',
        required: false

      attribute :expire_date,
        type: 'Time',
        json_key: 'expireDate',
        required: false

      attribute :fingerprint,
        type: 'String',
        json_key: 'fingerprint',
        required: false

      attribute :id,
        type: 'Integer',
        json_key: 'id',
        required: false

      attribute :san,
        type: 'Array<Object>',
        json_key: 'san',
        required: false

      attribute :serial,
        type: 'String',
        json_key: 'serial',
        required: false

      attribute :subject,
        type: 'String',
        json_key: 'subject',
        required: false

      attribute :type,
        type: 'IpLoadbalancingSslTypeEnum',
        json_key: 'type',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
