# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    module IpLoadbalancingIpStateEnum
      BLACKLISTED = 'blacklisted'
      DELETED = 'deleted'
      FREE = 'free'
      OK = 'ok'
      QUARANTINED = 'quarantined'
      SUSPENDED = 'suspended'

      def self.all
        @all ||= [
          BLACKLISTED,
          DELETED,
          FREE,
          OK,
          QUARANTINED,
          SUSPENDED,
        ].freeze
      end

      def self.valid?(value)
        all.include?(value)
      end
    end
  end
end
