# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    module IpMitigationStateEnum
      CREATION_PENDING = 'creationPending'
      OK = 'ok'
      REMOVAL_PENDING = 'removalPending'

      def self.all
        @all ||= [
          CREATION_PENDING,
          OK,
          REMOVAL_PENDING,
        ].freeze
      end

      def self.valid?(value)
        all.include?(value)
      end
    end
  end
end
