# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    module IpMitigationProfileAutoMitigationTimeOutEnum
      N0 = '0'
      N15 = '15'
      N60 = '60'
      N360 = '360'
      N1560 = '1560'

      def self.all
        @all ||= [
          N0,
          N15,
          N60,
          N360,
          N1560,
        ].freeze
      end

      def self.valid?(value)
        all.include?(value)
      end
    end
  end
end
