# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    class IpServiceIp
      include Ovh::Api::Serializable
      include Ovh::Api::Validations

      attribute :can_be_terminated,
        type: 'Boolean',
        json_key: 'canBeTerminated',
        required: false

      attribute :country,
        type: 'CoreTypesCountryEnum',
        json_key: 'country',
        required: false

      attribute :description,
        type: 'String',
        json_key: 'description',
        required: false

      attribute :ip,
        type: 'String',
        json_key: 'ip',
        required: false

      attribute :organisation_id,
        type: 'String',
        json_key: 'organisationId',
        required: false

      attribute :routed_to,
        type: 'IpRoutedTo',
        json_key: 'routedTo',
        required: false

      attribute :type,
        type: 'IpIpTypeEnum',
        json_key: 'type',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
