# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    module LicensePleskApplicationSetEnum
      APPLICATIONPACK = 'applicationpack'
      DEVELOPERPACK = 'developerpack'
      POWER_PACK_FOR_PLESK12 = 'power-pack-for-plesk12'
      POWERPACK = 'powerpack'

      def self.all
        @all ||= [
          APPLICATIONPACK,
          DEVELOPERPACK,
          POWER_PACK_FOR_PLESK12,
          POWERPACK,
        ].freeze
      end

      def self.valid?(value)
        all.include?(value)
      end
    end
  end
end
