# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    module LicenseOrderableAntispamEnum
      SPAM_ASSASSIN = 'SPAM_ASSASSIN'

      def self.all
        @all ||= [
          SPAM_ASSASSIN,
        ].freeze
      end

      def self.valid?(value)
        all.include?(value)
      end
    end
  end
end
