# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    module LicenseDirectAdminOsEnum
      CENT_OS_5_0_32 = 'CentOs_5.0_32'
      CENT_OS_5_0_64 = 'CentOs_5.0_64'
      CENT_OS_6_32 = 'CentOs_6_32'
      CENT_OS_6_64 = 'CentOs_6_64'
      CENT_OS_7_64 = 'CentOs_7_64'
      CENT_OS_8_64 = 'CentOs_8_64'
      DEBIAN_10_0_64 = 'Debian_10.0_64'
      DEBIAN_11_0_64 = 'Debian_11.0_64'
      DEBIAN_5_0_32 = 'Debian_5.0_32'
      DEBIAN_5_0_64 = 'Debian_5.0_64'
      DEBIAN_6_0_32 = 'Debian_6.0_32'
      DEBIAN_6_0_64 = 'Debian_6.0_64'
      DEBIAN_7_0_64 = 'Debian_7.0_64'
      DEBIAN_8_0_64 = 'Debian_8.0_64'
      DEBIAN_9_0_64 = 'Debian_9.0_64'
      FREE_BSD_11_X_64 = 'FreeBSD_11.x_64'
      FREE_BSD_12_X_64 = 'FreeBSD_12.x_64'
      FREE_BSD_7_X_32 = 'FreeBSD_7.x_32'
      FREE_BSD_7_X_64 = 'FreeBSD_7.x_64'
      FREE_BSD_8_X_64 = 'FreeBSD_8.x_64'
      FREE_BSD_9_X_64 = 'FreeBSD_9.x_64'

      def self.all
        @all ||= [
          CENT_OS_5_0_32,
          CENT_OS_5_0_64,
          CENT_OS_6_32,
          CENT_OS_6_64,
          CENT_OS_7_64,
          CENT_OS_8_64,
          DEBIAN_10_0_64,
          DEBIAN_11_0_64,
          DEBIAN_5_0_32,
          DEBIAN_5_0_64,
          DEBIAN_6_0_32,
          DEBIAN_6_0_64,
          DEBIAN_7_0_64,
          DEBIAN_8_0_64,
          DEBIAN_9_0_64,
          FREE_BSD_11_X_64,
          FREE_BSD_12_X_64,
          FREE_BSD_7_X_32,
          FREE_BSD_7_X_64,
          FREE_BSD_8_X_64,
          FREE_BSD_9_X_64,
        ].freeze
      end

      def self.valid?(value)
        all.include?(value)
      end
    end
  end
end
