# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    module LicenseLicenseTypeEnum
      DEDICATED = 'dedicated'
      DEDICATED_CLOUD = 'dedicatedCloud'
      DEDICATED_FAILOVER = 'dedicatedFailover'
      FAILOVER = 'failover'
      VM = 'vm'
      VPS = 'vps'
      VPS_CEPH = 'vps_ceph'
      VPS_CLASSIC = 'vps_classic'
      VPS_CLOUD = 'vps_cloud'
      VPS_CLOUD_2016 = 'vps_cloud_2016'
      VPS_SSD = 'vps_ssd'

      def self.all
        @all ||= [
          DEDICATED,
          DEDICATED_CLOUD,
          DEDICATED_FAILOVER,
          FAILOVER,
          VM,
          VPS,
          VPS_CEPH,
          VPS_CLASSIC,
          VPS_CLOUD,
          VPS_CLOUD_2016,
          VPS_SSD,
        ].freeze
      end

      def self.valid?(value)
        all.include?(value)
      end
    end
  end
end
