# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    module LicenseVirtuozzoContainerNumberEnum
      N2_CPU_001_CONTAINER = '2_CPU_001_CONTAINER'
      N2_CPU_003_CONTAINER = '2_CPU_003_CONTAINER'
      N2_CPU_010_CONTAINER = '2_CPU_010_CONTAINER'
      N2_CPU_030_CONTAINER = '2_CPU_030_CONTAINER'
      N2_CPU_060_CONTAINER = '2_CPU_060_CONTAINER'
      N2_CPU_100_CONTAINER = '2_CPU_100_CONTAINER'

      def self.all
        @all ||= [
          N2_CPU_001_CONTAINER,
          N2_CPU_003_CONTAINER,
          N2_CPU_010_CONTAINER,
          N2_CPU_030_CONTAINER,
          N2_CPU_060_CONTAINER,
          N2_CPU_100_CONTAINER,
        ].freeze
      end

      def self.valid?(value)
        all.include?(value)
      end
    end
  end
end
