# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    module LicenseOrderablePleskLanguagePackEnum
      N1 = '1'
      N1_EXTRA_LANGUAGE_FOR_PLESK = '1-extra-language-for-plesk'
      N1_EXTRA_LANGUAGE_FOR_PLESK_FOR_VPS = '1-extra-language-for-plesk-for-vps'
      N1_EXTRA_LANGUAGE_FOR_PLESK12 = '1-extra-language-for-plesk12'
      N1_EXTRA_LANGUAGE_FOR_PLESK12_FOR_VPS = '1-extra-language-for-plesk12-for-vps'
      N1_EXTRA_LANGUAGE_PACK_FOR_PLESK = '1-extra-language-pack-for-plesk'
      N2 = '2'
      N2_EXTRA_LANGUAGES_FOR_PLESK = '2-extra-languages-for-plesk'
      N2_EXTRA_LANGUAGES_FOR_PLESK_FOR_VPS = '2-extra-languages-for-plesk-for-vps'
      N2_EXTRA_LANGUAGES_FOR_PLESK12 = '2-extra-languages-for-plesk12'
      N2_EXTRA_LANGUAGES_FOR_PLESK12_FOR_VPS = '2-extra-languages-for-plesk12-for-vps'
      N2_EXTRA_LANGUAGES_PACK_FOR_PLESK = '2-extra-languages-pack-for-plesk'
      N3 = '3'
      N3_EXTRA_LANGUAGES_FOR_PLESK = '3-extra-languages-for-plesk'
      N3_EXTRA_LANGUAGES_FOR_PLESK_FOR_VPS = '3-extra-languages-for-plesk-for-vps'
      N3_EXTRA_LANGUAGES_FOR_PLESK12 = '3-extra-languages-for-plesk12'
      N3_EXTRA_LANGUAGES_FOR_PLESK12_FOR_VPS = '3-extra-languages-for-plesk12-for-vps'
      N3_EXTRA_LANGUAGES_PACK_FOR_PLESK = '3-extra-languages-pack-for-plesk'
      N4 = '4'
      N4_EXTRA_LANGUAGES_FOR_PLESK = '4-extra-languages-for-plesk'
      N4_EXTRA_LANGUAGES_FOR_PLESK_FOR_VPS = '4-extra-languages-for-plesk-for-vps'
      N4_EXTRA_LANGUAGES_FOR_PLESK12 = '4-extra-languages-for-plesk12'
      N4_EXTRA_LANGUAGES_FOR_PLESK12_FOR_VPS = '4-extra-languages-for-plesk12-for-vps'
      N4_EXTRA_LANGUAGES_PACK_FOR_PLESK = '4-extra-languages-pack-for-plesk'
      N5 = '5'
      N5_EXTRA_LANGUAGES_FOR_PLESK = '5-extra-languages-for-plesk'
      N5_EXTRA_LANGUAGES_FOR_PLESK_FOR_VPS = '5-extra-languages-for-plesk-for-vps'
      N5_EXTRA_LANGUAGES_FOR_PLESK12 = '5-extra-languages-for-plesk12'
      N5_EXTRA_LANGUAGES_FOR_PLESK12_FOR_VPS = '5-extra-languages-for-plesk12-for-vps'
      N5_EXTRA_LANGUAGES_PACK_FOR_PLESK = '5-extra-languages-pack-for-plesk'
      UNLIMITED = 'unlimited'
      UNLIMITED_EXTRA_LANGUAGES_FOR_PLESK = 'unlimited-extra-languages-for-plesk'
      UNLIMITED_EXTRA_LANGUAGES_FOR_PLESK_FOR_VPS = 'unlimited-extra-languages-for-plesk-for-vps'
      UNLIMITED_EXTRA_LANGUAGES_FOR_PLESK12 = 'unlimited-extra-languages-for-plesk12'
      UNLIMITED_EXTRA_LANGUAGES_FOR_PLESK12_FOR_VPS = 'unlimited-extra-languages-for-plesk12-for-vps'
      UNLIMITED_EXTRA_LANGUAGES_PACK_FOR_PLESK = 'unlimited-extra-languages-pack-for-plesk'

      def self.all
        @all ||= [
          N1,
          N1_EXTRA_LANGUAGE_FOR_PLESK,
          N1_EXTRA_LANGUAGE_FOR_PLESK_FOR_VPS,
          N1_EXTRA_LANGUAGE_FOR_PLESK12,
          N1_EXTRA_LANGUAGE_FOR_PLESK12_FOR_VPS,
          N1_EXTRA_LANGUAGE_PACK_FOR_PLESK,
          N2,
          N2_EXTRA_LANGUAGES_FOR_PLESK,
          N2_EXTRA_LANGUAGES_FOR_PLESK_FOR_VPS,
          N2_EXTRA_LANGUAGES_FOR_PLESK12,
          N2_EXTRA_LANGUAGES_FOR_PLESK12_FOR_VPS,
          N2_EXTRA_LANGUAGES_PACK_FOR_PLESK,
          N3,
          N3_EXTRA_LANGUAGES_FOR_PLESK,
          N3_EXTRA_LANGUAGES_FOR_PLESK_FOR_VPS,
          N3_EXTRA_LANGUAGES_FOR_PLESK12,
          N3_EXTRA_LANGUAGES_FOR_PLESK12_FOR_VPS,
          N3_EXTRA_LANGUAGES_PACK_FOR_PLESK,
          N4,
          N4_EXTRA_LANGUAGES_FOR_PLESK,
          N4_EXTRA_LANGUAGES_FOR_PLESK_FOR_VPS,
          N4_EXTRA_LANGUAGES_FOR_PLESK12,
          N4_EXTRA_LANGUAGES_FOR_PLESK12_FOR_VPS,
          N4_EXTRA_LANGUAGES_PACK_FOR_PLESK,
          N5,
          N5_EXTRA_LANGUAGES_FOR_PLESK,
          N5_EXTRA_LANGUAGES_FOR_PLESK_FOR_VPS,
          N5_EXTRA_LANGUAGES_FOR_PLESK12,
          N5_EXTRA_LANGUAGES_FOR_PLESK12_FOR_VPS,
          N5_EXTRA_LANGUAGES_PACK_FOR_PLESK,
          UNLIMITED,
          UNLIMITED_EXTRA_LANGUAGES_FOR_PLESK,
          UNLIMITED_EXTRA_LANGUAGES_FOR_PLESK_FOR_VPS,
          UNLIMITED_EXTRA_LANGUAGES_FOR_PLESK12,
          UNLIMITED_EXTRA_LANGUAGES_FOR_PLESK12_FOR_VPS,
          UNLIMITED_EXTRA_LANGUAGES_PACK_FOR_PLESK,
        ].freeze
      end

      def self.valid?(value)
        all.include?(value)
      end
    end
  end
end
