# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    class LicensePleskPlesk
      include Ovh::Api::Serializable
      include Ovh::Api::Validations

      attribute :creation,
        type: 'Time',
        json_key: 'creation',
        required: false

      attribute :delete_at_expiration,
        type: 'Boolean',
        json_key: 'deleteAtExpiration',
        required: false

      attribute :domain,
        type: 'String',
        json_key: 'domain',
        required: false

      attribute :domain_number,
        type: 'LicenseDomainNumberEnum',
        json_key: 'domainNumber',
        required: false

      attribute :information_key,
        type: 'String',
        json_key: 'informationKey',
        required: false

      attribute :ip,
        type: 'String',
        json_key: 'ip',
        required: false

      attribute :key,
        type: 'String',
        json_key: 'key',
        required: false

      attribute :license_id,
        type: 'String',
        json_key: 'licenseId',
        required: false

      attribute :product_key,
        type: 'String',
        json_key: 'productKey',
        required: false

      attribute :status,
        type: 'LicenseStateEnum',
        json_key: 'status',
        required: false

      attribute :version,
        type: 'LicensePleskVersionEnum',
        json_key: 'version',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
