# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    module LicenseVirtuozzoVersionEnum
      VIRTUOZZO_CONTAINERS_4_FOR_LINUX = 'VIRTUOZZO_CONTAINERS_4_FOR_LINUX'
      VIRTUOZZO_CONTAINERS_4_FOR_WINDOWS = 'VIRTUOZZO_CONTAINERS_4_FOR_WINDOWS'

      def self.all
        @all ||= [
          VIRTUOZZO_CONTAINERS_4_FOR_LINUX,
          VIRTUOZZO_CONTAINERS_4_FOR_WINDOWS,
        ].freeze
      end

      def self.valid?(value)
        all.include?(value)
      end
    end
  end
end
