# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    module LicenseWorkLightVersionEnum
      VERSION_6_1_U_1_CPU = 'VERSION-6.1U.1CPU'
      VERSION_6_1_U_2_CPU = 'VERSION-6.1U.2CPU'
      VERSION_6_2_U_1_CPU = 'VERSION-6.2U.1CPU'
      VERSION_6_2_U_2_CPU = 'VERSION-6.2U.2CPU'
      VERSION_6_EVALUATION = 'VERSION-6.EVALUATION'
      WORKLIGHT_LICENSE_VERSION_6_1CPU_1U = 'worklight-license-version-6-1cpu-1u'
      WORKLIGHT_LICENSE_VERSION_6_1CPU_2U = 'worklight-license-version-6-1cpu-2u'
      WORKLIGHT_LICENSE_VERSION_6_2CPU_1U = 'worklight-license-version-6-2cpu-1u'
      WORKLIGHT_LICENSE_VERSION_6_2CPU_2U = 'worklight-license-version-6-2cpu-2u'

      def self.all
        @all ||= [
          VERSION_6_1_U_1_CPU,
          VERSION_6_1_U_2_CPU,
          VERSION_6_2_U_1_CPU,
          VERSION_6_2_U_2_CPU,
          VERSION_6_EVALUATION,
          WORKLIGHT_LICENSE_VERSION_6_1CPU_1U,
          WORKLIGHT_LICENSE_VERSION_6_1CPU_2U,
          WORKLIGHT_LICENSE_VERSION_6_2CPU_1U,
          WORKLIGHT_LICENSE_VERSION_6_2CPU_2U,
        ].freeze
      end

      def self.valid?(value)
        all.include?(value)
      end
    end
  end
end
