# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    module LicenseOrderableAntivirusEnum
      DR_WEB = 'DR_WEB'
      KASPERSKY_UNLIMITED_MAILBOXES = 'KASPERSKY_UNLIMITED_MAILBOXES'
      KASPERSKY = 'kaspersky'

      def self.all
        @all ||= [
          DR_WEB,
          KASPERSKY_UNLIMITED_MAILBOXES,
          KASPERSKY,
        ].freeze
      end

      def self.valid?(value)
        all.include?(value)
      end
    end
  end
end
