# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    class LicenseOfficeOfficeUserNativeUpdate
      include Ovh::Api::Serializable
      include Ovh::Api::Validations

      attribute :activation_email,
        type: 'String',
        json_key: 'activationEmail',
        required: false

      attribute :delete_at_expiration,
        type: 'Boolean',
        json_key: 'deleteAtExpiration',
        required: false

      attribute :first_name,
        type: 'String',
        json_key: 'firstName',
        required: false

      attribute :last_name,
        type: 'String',
        json_key: 'lastName',
        required: false

      attribute :usage_location,
        type: 'LicenseOfficeCountryEnum',
        json_key: 'usageLocation',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
