# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    module MeBillingPurchaseOrderPurchaseOrderTypeEnum
      PURCHASE_ORDER = 'PURCHASE_ORDER'
      REFERENCE_ORDER = 'REFERENCE_ORDER'

      def self.all
        @all ||= [
          PURCHASE_ORDER,
          REFERENCE_ORDER,
        ].freeze
      end

      def self.valid?(value)
        all.include?(value)
      end
    end
  end
end
