# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    class MeMarketingConsentDetails
      include Ovh::Api::Serializable
      include Ovh::Api::Validations

      attribute :events,
        type: 'Boolean',
        json_key: 'events',
        required: false

      attribute :new_product_recommendation,
        type: 'Boolean',
        json_key: 'newProductRecommendation',
        required: false

      attribute :newsletter,
        type: 'Boolean',
        json_key: 'newsletter',
        required: false

      attribute :offer_and_discount,
        type: 'Boolean',
        json_key: 'offerAndDiscount',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
