# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    module MePaymentAvailableSubTypeEnum
      N30_DAYS = '30_DAYS'
      N45_DAYS = '45_DAYS'
      N60_DAYS = '60_DAYS'
      AMERICAN_EXPRESS = 'AMERICAN_EXPRESS'
      AURA = 'AURA'
      CARTE_BANCAIRE = 'CARTE_BANCAIRE'
      CARTE_BLEUE = 'CARTE_BLEUE'
      CHORUS = 'CHORUS'
      DINERS_CLUB = 'DINERS_CLUB'
      DISCOVER = 'DISCOVER'
      JCB = 'JCB'
      MAESTRO = 'MAESTRO'
      MASTERCARD = 'MASTERCARD'
      NONE = 'NONE'
      RUPAY = 'RUPAY'
      VISA = 'VISA'

      def self.all
        @all ||= [
          N30_DAYS,
          N45_DAYS,
          N60_DAYS,
          AMERICAN_EXPRESS,
          AURA,
          CARTE_BANCAIRE,
          CARTE_BLEUE,
          CHORUS,
          DINERS_CLUB,
          DISCOVER,
          JCB,
          MAESTRO,
          MASTERCARD,
          NONE,
          RUPAY,
          VISA,
        ].freeze
      end

      def self.valid?(value)
        all.include?(value)
      end
    end
  end
end
