# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    class MePaymentMethodCreation
      include Ovh::Api::Serializable
      include Ovh::Api::Validations

      attribute :billing_contact_id,
        type: 'Integer',
        json_key: 'billingContactId',
        required: false

      attribute :callback_url,
        type: 'MePaymentMethodCallbackUrl',
        json_key: 'callbackUrl',
        required: true

      attribute :default,
        type: 'Boolean',
        json_key: 'default',
        required: false

      attribute :description,
        type: 'String',
        json_key: 'description',
        required: false

      attribute :form_data,
        type: 'String',
        json_key: 'formData',
        required: false

      attribute :order_id,
        type: 'Integer',
        json_key: 'orderId',
        required: false

      attribute :payment_sub_type,
        type: 'MePaymentCreationSubTypeEnum',
        json_key: 'paymentSubType',
        required: false

      attribute :payment_type,
        type: 'String',
        json_key: 'paymentType',
        required: true

      attribute :register,
        type: 'Boolean',
        json_key: 'register',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
