# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    class MePaymentMethodCallbackUrl
      include Ovh::Api::Serializable
      include Ovh::Api::Validations

      attribute :cancel,
        type: 'String',
        json_key: 'cancel',
        required: true

      attribute :error,
        type: 'String',
        json_key: 'error',
        required: true

      attribute :failure,
        type: 'String',
        json_key: 'failure',
        required: true

      attribute :pending,
        type: 'String',
        json_key: 'pending',
        required: true

      attribute :success,
        type: 'String',
        json_key: 'success',
        required: true

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
