# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    module MePaymentMethodStatusEnum
      CANCELED = 'CANCELED'
      CANCELING = 'CANCELING'
      CREATED = 'CREATED'
      CREATING = 'CREATING'
      ERROR = 'ERROR'
      EXPIRED = 'EXPIRED'
      FAILED = 'FAILED'
      MAINTENANCE = 'MAINTENANCE'
      PAUSED = 'PAUSED'
      REJECTED = 'REJECTED'
      REPLACED = 'REPLACED'
      VALID = 'VALID'
      VALIDATING = 'VALIDATING'

      def self.all
        @all ||= [
          CANCELED,
          CANCELING,
          CREATED,
          CREATING,
          ERROR,
          EXPIRED,
          FAILED,
          MAINTENANCE,
          PAUSED,
          REJECTED,
          REPLACED,
          VALID,
          VALIDATING,
        ].freeze
      end

      def self.valid?(value)
        all.include?(value)
      end
    end
  end
end
