# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    module MePaymentMeanPaypalStateEnum
      FAILING = 'failing'
      TOO_MANY_FAILURES = 'tooManyFailures'
      VALID = 'valid'

      def self.all
        @all ||= [
          FAILING,
          TOO_MANY_FAILURES,
          VALID,
        ].freeze
      end

      def self.valid?(value)
        all.include?(value)
      end
    end
  end
end
