# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    class MePaymentMeanDeferred
      include Ovh::Api::Serializable
      include Ovh::Api::Validations

      attribute :creation_date,
        type: 'Time',
        json_key: 'creationDate',
        required: false

      attribute :default_payment_mean,
        type: 'Boolean',
        json_key: 'defaultPaymentMean',
        required: false

      attribute :description,
        type: 'String',
        json_key: 'description',
        required: false

      attribute :icon,
        type: 'MePaymentMeanIconData',
        json_key: 'icon',
        required: false

      attribute :id,
        type: 'Integer',
        json_key: 'id',
        required: false

      attribute :label,
        type: 'String',
        json_key: 'label',
        required: false

      attribute :state,
        type: 'MePaymentMeanDeferredStateEnum',
        json_key: 'state',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
