# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    class MsServicesSharepointService
      include Ovh::Api::Serializable
      include Ovh::Api::Validations

      attribute :current_usage,
        type: 'Integer',
        json_key: 'currentUsage',
        required: false

      attribute :display_name,
        type: 'String',
        json_key: 'displayName',
        required: false

      attribute :domain,
        type: 'String',
        json_key: 'domain',
        required: false

      attribute :farm_url,
        type: 'String',
        json_key: 'farmUrl',
        required: false

      attribute :offer,
        type: 'MsServicesSharepointServiceOfferEnum',
        json_key: 'offer',
        required: false

      attribute :quota,
        type: 'Integer',
        json_key: 'quota',
        required: false

      attribute :state,
        type: 'MsServicesServiceStateEnum',
        json_key: 'state',
        required: false

      attribute :task_pending_id,
        type: 'Integer',
        json_key: 'taskPendingId',
        required: false

      attribute :url,
        type: 'String',
        json_key: 'url',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
