# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    class MsServicesExchangeService
      include Ovh::Api::Serializable
      include Ovh::Api::Validations

      attribute :display_name,
        type: 'String',
        json_key: 'displayName',
        required: false

      attribute :domain,
        type: 'String',
        json_key: 'domain',
        required: false

      attribute :hostname,
        type: 'String',
        json_key: 'hostname',
        required: false

      attribute :max_receive_size,
        type: 'Integer',
        json_key: 'maxReceiveSize',
        required: false

      attribute :max_send_size,
        type: 'Integer',
        json_key: 'maxSendSize',
        required: false

      attribute :offer,
        type: 'MsServicesServiceOfferEnum',
        json_key: 'offer',
        required: false

      attribute :spam_and_virus_configuration,
        type: 'MsServicesSpamAndVirusConfiguration',
        json_key: 'spamAndVirusConfiguration',
        required: false

      attribute :ssl_expiration_date,
        type: 'Date',
        json_key: 'sslExpirationDate',
        required: false

      attribute :state,
        type: 'MsServicesServiceStateEnum',
        json_key: 'state',
        required: false

      attribute :task_pending_id,
        type: 'Integer',
        json_key: 'taskPendingId',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
