# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    module MsServicesServiceStateEnum
      CREATING = 'creating'
      DELETING = 'deleting'
      IN_MAINTENANCE = 'inMaintenance'
      OK = 'ok'
      REOPENING = 'reopening'
      SUSPENDED = 'suspended'
      SUSPENDING = 'suspending'

      def self.all
        @all ||= [
          CREATING,
          DELETING,
          IN_MAINTENANCE,
          OK,
          REOPENING,
          SUSPENDED,
          SUSPENDING,
        ].freeze
      end

      def self.valid?(value)
        all.include?(value)
      end
    end
  end
end
