# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    class NichandleNicAutorenewInfos
      include Ovh::Api::Serializable
      include Ovh::Api::Validations

      attribute :active,
        type: 'Boolean',
        json_key: 'active',
        required: false

      attribute :last_renew,
        type: 'Time',
        json_key: 'lastRenew',
        required: false

      attribute :renew_day,
        type: 'Integer',
        json_key: 'renewDay',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
