# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    class NichandleNichandle
      include Ovh::Api::Serializable
      include Ovh::Api::Validations

      attribute :address,
        type: 'String',
        json_key: 'address',
        required: false

      attribute :area,
        type: 'String',
        json_key: 'area',
        required: false

      attribute :birth_city,
        type: 'String',
        json_key: 'birthCity',
        required: false

      attribute :birth_day,
        type: 'String',
        json_key: 'birthDay',
        required: false

      attribute :city,
        type: 'String',
        json_key: 'city',
        required: false

      attribute :company_national_identification_number,
        type: 'String',
        json_key: 'companyNationalIdentificationNumber',
        required: false

      attribute :complementary_address,
        type: 'String',
        json_key: 'complementaryAddress',
        required: false

      attribute :corporation_type,
        type: 'String',
        json_key: 'corporationType',
        required: false

      attribute :country,
        type: 'NichandleCountryEnum',
        json_key: 'country',
        required: false

      attribute :currency,
        type: 'NichandleCurrency',
        json_key: 'currency',
        required: false

      attribute :customer_code,
        type: 'String',
        json_key: 'customerCode',
        required: false

      attribute :display_name,
        type: 'String',
        json_key: 'displayName',
        required: false

      attribute :email,
        type: 'String',
        json_key: 'email',
        required: false

      attribute :fax,
        type: 'String',
        json_key: 'fax',
        required: false

      attribute :firstname,
        type: 'String',
        json_key: 'firstname',
        required: false

      attribute :italian_sdi,
        type: 'String',
        json_key: 'italianSDI',
        required: false

      attribute :kyc_validated,
        type: 'Boolean',
        json_key: 'kycValidated',
        required: false

      attribute :language,
        type: 'NichandleLanguageEnum',
        json_key: 'language',
        required: false

      attribute :legalform,
        type: 'NichandleLegalFormEnum',
        json_key: 'legalform',
        required: false

      attribute :name,
        type: 'String',
        json_key: 'name',
        required: false

      attribute :national_identification_number,
        type: 'String',
        json_key: 'nationalIdentificationNumber',
        required: false

      attribute :nichandle,
        type: 'String',
        json_key: 'nichandle',
        required: false

      attribute :organisation,
        type: 'String',
        json_key: 'organisation',
        required: false

      attribute :ovh_company,
        type: 'NichandleOvhCompanyEnum',
        json_key: 'ovhCompany',
        required: false

      attribute :ovh_subsidiary,
        type: 'NichandleOvhSubsidiaryEnum',
        json_key: 'ovhSubsidiary',
        required: false

      attribute :phone,
        type: 'String',
        json_key: 'phone',
        required: false

      attribute :phone_country,
        type: 'NichandleCountryEnum',
        json_key: 'phoneCountry',
        required: false

      attribute :phone_type,
        type: 'NichandlePhoneTypeEnum',
        json_key: 'phoneType',
        required: false

      attribute :purpose_of_purchase,
        type: 'String',
        json_key: 'purposeOfPurchase',
        required: false

      attribute :sex,
        type: 'NichandleGenderEnum',
        json_key: 'sex',
        required: false

      attribute :spare_email,
        type: 'String',
        json_key: 'spareEmail',
        required: false

      attribute :state,
        type: 'NichandleStateEnum',
        json_key: 'state',
        required: false

      attribute :vat,
        type: 'String',
        json_key: 'vat',
        required: false

      attribute :zip,
        type: 'String',
        json_key: 'zip',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
