# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    module NichandleOvhSubsidiaryEnum
      ASIA = 'ASIA'
      AU = 'AU'
      CA = 'CA'
      CZ = 'CZ'
      DE = 'DE'
      ES = 'ES'
      EU = 'EU'
      FI = 'FI'
      FR = 'FR'
      GB = 'GB'
      IE = 'IE'
      IN = 'IN'
      IT = 'IT'
      LT = 'LT'
      MA = 'MA'
      NL = 'NL'
      PL = 'PL'
      PT = 'PT'
      QC = 'QC'
      SG = 'SG'
      SN = 'SN'
      TN = 'TN'
      US = 'US'
      WE = 'WE'
      WS = 'WS'

      def self.all
        @all ||= [
          ASIA,
          AU,
          CA,
          CZ,
          DE,
          ES,
          EU,
          FI,
          FR,
          GB,
          IE,
          IN,
          IT,
          LT,
          MA,
          NL,
          PL,
          PT,
          QC,
          SG,
          SN,
          TN,
          US,
          WE,
          WS,
        ].freeze
      end

      def self.valid?(value)
        all.include?(value)
      end
    end
  end
end
