# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    module NichandleAccessRestrictionTOTPStatusEnum
      DISABLED = 'disabled'
      ENABLED = 'enabled'
      NEED_CODE_VALIDATION = 'needCodeValidation'
      NEED_EMAIL_VALIDATION = 'needEmailValidation'

      def self.all
        @all ||= [
          DISABLED,
          ENABLED,
          NEED_CODE_VALIDATION,
          NEED_EMAIL_VALIDATION,
        ].freeze
      end

      def self.valid?(value)
        all.include?(value)
      end
    end
  end
end
