# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    module NichandleLanguageEnum
      CS_CZ = 'cs_CZ'
      DE_DE = 'de_DE'
      EN_AU = 'en_AU'
      EN_CA = 'en_CA'
      EN_GB = 'en_GB'
      EN_IE = 'en_IE'
      EN_US = 'en_US'
      ES_ES = 'es_ES'
      FI_FI = 'fi_FI'
      FR_CA = 'fr_CA'
      FR_FR = 'fr_FR'
      FR_MA = 'fr_MA'
      FR_SN = 'fr_SN'
      FR_TN = 'fr_TN'
      IT_IT = 'it_IT'
      LT_LT = 'lt_LT'
      NL_NL = 'nl_NL'
      PL_PL = 'pl_PL'
      PT_PT = 'pt_PT'

      def self.all
        @all ||= [
          CS_CZ,
          DE_DE,
          EN_AU,
          EN_CA,
          EN_GB,
          EN_IE,
          EN_US,
          ES_ES,
          FI_FI,
          FR_CA,
          FR_FR,
          FR_MA,
          FR_SN,
          FR_TN,
          IT_IT,
          LT_LT,
          NL_NL,
          PL_PL,
          PT_PT,
        ].freeze
      end

      def self.valid?(value)
        all.include?(value)
      end
    end
  end
end
