# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    class NutanixPrismcentral
      include Ovh::Api::Serializable
      include Ovh::Api::Validations

      attribute :ips,
        type: 'Array<String>',
        json_key: 'ips',
        required: false

      attribute :size,
        type: 'NutanixPcsizeEnum',
        json_key: 'size',
        required: false

      attribute :type,
        type: 'NutanixPctypeEnum',
        json_key: 'type',
        required: false

      attribute :vip,
        type: 'String',
        json_key: 'vip',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
