# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    class OrderTelephonyBillingAccountNumberNogeographicPostRequest
      include Ovh::Api::Serializable
      include Ovh::Api::Validations

      attribute :ape,
        type: 'String',
        json_key: 'ape',
        required: false

      attribute :city,
        type: 'String',
        json_key: 'city',
        required: false

      attribute :country,
        type: 'TelephonyNumberCountryEnum',
        json_key: 'country',
        required: true

      attribute :display_universal_directory,
        type: 'Boolean',
        json_key: 'displayUniversalDirectory',
        required: true

      attribute :email,
        type: 'String',
        json_key: 'email',
        required: false

      attribute :firstname,
        type: 'String',
        json_key: 'firstname',
        required: false

      attribute :legalform,
        type: 'NichandleLegalFormEnum',
        json_key: 'legalform',
        required: true

      attribute :name,
        type: 'String',
        json_key: 'name',
        required: false

      attribute :offer,
        type: 'TelephonyNumberOffer',
        json_key: 'offer',
        required: true

      attribute :organisation,
        type: 'String',
        json_key: 'organisation',
        required: false

      attribute :phone,
        type: 'String',
        json_key: 'phone',
        required: false

      attribute :pool,
        type: 'TelephonyNumberPoolEnum',
        json_key: 'pool',
        required: false

      attribute :retractation,
        type: 'Boolean',
        json_key: 'retractation',
        required: true

      attribute :siret,
        type: 'String',
        json_key: 'siret',
        required: false

      attribute :social_nomination,
        type: 'String',
        json_key: 'socialNomination',
        required: false

      attribute :specific_number,
        type: 'String',
        json_key: 'specificNumber',
        required: false

      attribute :street_name,
        type: 'String',
        json_key: 'streetName',
        required: false

      attribute :street_number,
        type: 'String',
        json_key: 'streetNumber',
        required: false

      attribute :zip,
        type: 'String',
        json_key: 'zip',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
