# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    class OrderHostingWebServiceNameUpgradeDurationPostRequest
      include Ovh::Api::Serializable
      include Ovh::Api::Validations

      attribute :offer,
        type: 'HostingWebOfferEnum',
        json_key: 'offer',
        required: true

      attribute :start_time,
        type: 'String',
        json_key: 'startTime',
        required: false

      attribute :waive_retractation_period,
        type: 'Boolean',
        json_key: 'waiveRetractationPeriod',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
