# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    class OrderLicensePleskServiceNameUpgradeDurationPostRequest
      include Ovh::Api::Serializable
      include Ovh::Api::Validations

      attribute :antispam,
        type: 'LicenseOrderableAntispamEnum',
        json_key: 'antispam',
        required: false

      attribute :antivirus,
        type: 'LicenseOrderableAntivirusEnum',
        json_key: 'antivirus',
        required: false

      attribute :application_set,
        type: 'LicensePleskApplicationSetEnum',
        json_key: 'applicationSet',
        required: false

      attribute :domain_number,
        type: 'LicenseOrderablePleskDomainNumberEnum',
        json_key: 'domainNumber',
        required: false

      attribute :language_pack_number,
        type: 'LicenseOrderablePleskLanguagePackEnum',
        json_key: 'languagePackNumber',
        required: false

      attribute :powerpack,
        type: 'Boolean',
        json_key: 'powerpack',
        required: false

      attribute :reseller_management,
        type: 'Boolean',
        json_key: 'resellerManagement',
        required: false

      attribute :version,
        type: 'LicensePleskVersionEnum',
        json_key: 'version',
        required: false

      attribute :wordpress_toolkit,
        type: 'Boolean',
        json_key: 'wordpressToolkit',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
