# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    class OrderTelephonyBillingAccountLinePostRequest
      include Ovh::Api::Serializable
      include Ovh::Api::Validations

      attribute :brand,
        type: 'String',
        json_key: 'brand',
        required: false

      attribute :display_universal_directories,
        type: 'Array<Object>',
        json_key: 'displayUniversalDirectories',
        required: true

      attribute :extra_simultaneous_lines,
        type: 'Array<Object>',
        json_key: 'extraSimultaneousLines',
        required: true

      attribute :mondial_relay_id,
        type: 'String',
        json_key: 'mondialRelayId',
        required: false

      attribute :offers,
        type: 'Array<Object>',
        json_key: 'offers',
        required: true

      attribute :owner_contact_ids,
        type: 'Array<Object>',
        json_key: 'ownerContactIds',
        required: true

      attribute :quantity,
        type: 'Integer',
        json_key: 'quantity',
        required: true

      attribute :retractation,
        type: 'Boolean',
        json_key: 'retractation',
        required: true

      attribute :shipping_contact_id,
        type: 'Integer',
        json_key: 'shippingContactId',
        required: true

      attribute :types,
        type: 'Array<TelephonyLineTypeEnum>',
        json_key: 'types',
        required: true

      attribute :zones,
        type: 'Array<Object>',
        json_key: 'zones',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
