# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    class OrderPrice
      include Ovh::Api::Serializable
      include Ovh::Api::Validations

      attribute :currency_code,
        type: 'OrderCurrencyCodeEnum',
        json_key: 'currencyCode',
        required: false

      attribute :price_in_ucents,
        type: 'Integer',
        json_key: 'priceInUcents',
        required: false

      attribute :text,
        type: 'String',
        json_key: 'text',
        required: false

      attribute :value,
        type: 'Float',
        json_key: 'value',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
