# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    class OrderTelephonySpareNewPostRequest
      include Ovh::Api::Serializable
      include Ovh::Api::Validations

      attribute :brand,
        type: 'String',
        json_key: 'brand',
        required: true

      attribute :mondial_relay_id,
        type: 'String',
        json_key: 'mondialRelayId',
        required: false

      attribute :quantity,
        type: 'Integer',
        json_key: 'quantity',
        required: true

      attribute :shipping_contact_id,
        type: 'Integer',
        json_key: 'shippingContactId',
        required: true

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
