# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    module OverTheBoxTunnelModeEnum
      GLORYTUN = 'glorytun'
      GLORYTUN_HYBRID = 'glorytun_hybrid'
      GLORYTUN_MUD = 'glorytun_mud'

      def self.all
        @all ||= [
          GLORYTUN,
          GLORYTUN_HYBRID,
          GLORYTUN_MUD,
        ].freeze
      end

      def self.valid?(value)
        all.include?(value)
      end
    end
  end
end
