# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    module OverTheBoxServiceStatusEnum
      ACTIVE = 'active'
      CREATING = 'creating'
      DELETED = 'deleted'
      SUSPENDED = 'suspended'
      TO_CREATE = 'toCreate'
      TO_DELETE = 'toDelete'

      def self.all
        @all ||= [
          ACTIVE,
          CREATING,
          DELETED,
          SUSPENDED,
          TO_CREATE,
          TO_DELETE,
        ].freeze
      end

      def self.valid?(value)
        all.include?(value)
      end
    end
  end
end
