# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    class OverTheBoxServiceNameRemoteAccessesPostRequest
      include Ovh::Api::Serializable
      include Ovh::Api::Validations

      attribute :allowed_ip,
        type: 'String',
        json_key: 'allowedIp',
        required: false

      attribute :expiration_date,
        type: 'Time',
        json_key: 'expirationDate',
        required: false

      attribute :exposed_port,
        type: 'Integer',
        json_key: 'exposedPort',
        required: true

      attribute :public_key,
        type: 'String',
        json_key: 'publicKey',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
