# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    module OvhcloudconnectDiagnosticTypeEnum
      ADVERTISED_ROUTES = 'advertised-routes'
      DEFAULT = 'default'
      ROUTES = 'routes'

      def self.all
        @all ||= [
          ADVERTISED_ROUTES,
          DEFAULT,
          ROUTES,
        ].freeze
      end

      def self.valid?(value)
        all.include?(value)
      end
    end
  end
end
