# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    module OvhcloudconnectPopConfigTypeEnum
      L2 = 'l2'
      L3 = 'l3'

      def self.all
        @all ||= [
          L2,
          L3,
        ].freeze
      end

      def self.valid?(value)
        all.include?(value)
      end
    end
  end
end
