# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    class PackXdslPackNameMigrationMigratePostRequest
      include Ovh::Api::Serializable
      include Ovh::Api::Validations

      attribute :accept_contracts,
        type: 'Boolean',
        json_key: 'acceptContracts',
        required: true

      attribute :building_reference,
        type: 'String',
        json_key: 'buildingReference',
        required: false

      attribute :contact_phone,
        type: 'String',
        json_key: 'contactPhone',
        required: false

      attribute :engage_months,
        type: 'Integer',
        json_key: 'engageMonths',
        required: false

      attribute :floor,
        type: 'String',
        json_key: 'floor',
        required: false

      attribute :installation_type,
        type: 'ConnectivityEligibilityInstallationTypeEnum',
        json_key: 'installationType',
        required: false

      attribute :meeting,
        type: 'XdslEligibilityBookMeetingSlot',
        json_key: 'meeting',
        required: false

      attribute :modem,
        type: 'PackXdslModemOptionEnum',
        json_key: 'modem',
        required: true

      attribute :mondial_relay_id,
        type: 'Integer',
        json_key: 'mondialRelayId',
        required: false

      attribute :nic_shipping,
        type: 'String',
        json_key: 'nicShipping',
        required: false

      attribute :offer_name,
        type: 'String',
        json_key: 'offerName',
        required: true

      attribute :ont_shipping_contact,
        type: 'String',
        json_key: 'ontShippingContact',
        required: false

      attribute :options,
        type: 'Array<PackXdslMigrationOfferOption>',
        json_key: 'options',
        required: false

      attribute :otp,
        type: 'Boolean',
        json_key: 'otp',
        required: false

      attribute :otp_reference,
        type: 'String',
        json_key: 'otpReference',
        required: false

      attribute :product_code,
        type: 'String',
        json_key: 'productCode',
        required: false

      attribute :stair,
        type: 'String',
        json_key: 'stair',
        required: false

      attribute :sub_services_to_delete,
        type: 'Array<PackXdslMigrationOfferServiceToDelete>',
        json_key: 'subServicesToDelete',
        required: false

      attribute :sub_services_to_keep,
        type: 'Array<PackXdslMigrationOfferServiceToKeep>',
        json_key: 'subServicesToKeep',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
