# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    class PackXdslPackNameDomainServicesPostRequest
      include Ovh::Api::Serializable
      include Ovh::Api::Validations

      attribute :action,
        type: 'PackXdslDomainActionEnum',
        json_key: 'action',
        required: true

      attribute :auth_info,
        type: 'String',
        json_key: 'authInfo',
        required: false

      attribute :domain,
        type: 'String',
        json_key: 'domain',
        required: true

      attribute :tld,
        type: 'String',
        json_key: 'tld',
        required: true

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
