# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    class PackXdslPackNameVoipLineServicesPostRequest
      include Ovh::Api::Serializable
      include Ovh::Api::Validations

      attribute :hardware_names,
        type: 'Array<Object>',
        json_key: 'hardwareNames',
        required: true

      attribute :mondial_relay_id,
        type: 'String',
        json_key: 'mondialRelayId',
        required: false

      attribute :shipping_id,
        type: 'String',
        json_key: 'shippingId',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
