# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    module PackXdslServiceNameEnum
      DOMAIN = 'domain'
      EMAIL_PRO = 'emailPro'
      EXCHANGE_ACCOUNT = 'exchangeAccount'
      EXCHANGE_INDIVIDUAL = 'exchangeIndividual'
      EXCHANGE_ORGANIZATION = 'exchangeOrganization'
      GRT10HO = 'grt10ho'
      GRT20M10HO = 'grt20m10ho'
      GRT20M4HO = 'grt20m4ho'
      GRT4HO = 'grt4ho'
      GRT5M10HO = 'grt5m10ho'
      GRT5M4HO = 'grt5m4ho'
      GRT_ALT = 'grtAlt'
      GRT_DSP = 'grtDsp'
      GRT_FT = 'grtFt'
      GRT_KOSC = 'grtKosc'
      GRT_OVH = 'grtOvh'
      HOSTED_EMAIL = 'hostedEmail'
      MODEM = 'modem'
      OVER_THE_BOX_HARDWARE = 'overTheBoxHardware'
      OVER_THE_BOX_SERVICE = 'overTheBoxService'
      VOIP_ALIAS = 'voipAlias'
      VOIP_BILLING_ACCOUNT = 'voipBillingAccount'
      VOIP_ECO_FAX = 'voipEcoFax'
      VOIP_LINE = 'voipLine'
      VOIP_TRUNK = 'voipTrunk'
      XDSL_ACCESS = 'xdslAccess'

      def self.all
        @all ||= [
          DOMAIN,
          EMAIL_PRO,
          EXCHANGE_ACCOUNT,
          EXCHANGE_INDIVIDUAL,
          EXCHANGE_ORGANIZATION,
          GRT10HO,
          GRT20M10HO,
          GRT20M4HO,
          GRT4HO,
          GRT5M10HO,
          GRT5M4HO,
          GRT_ALT,
          GRT_DSP,
          GRT_FT,
          GRT_KOSC,
          GRT_OVH,
          HOSTED_EMAIL,
          MODEM,
          OVER_THE_BOX_HARDWARE,
          OVER_THE_BOX_SERVICE,
          VOIP_ALIAS,
          VOIP_BILLING_ACCOUNT,
          VOIP_ECO_FAX,
          VOIP_LINE,
          VOIP_TRUNK,
          XDSL_ACCESS,
        ].freeze
      end

      def self.valid?(value)
        all.include?(value)
      end
    end
  end
end
