# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    class Partner2Partner
      include Ovh::Api::Serializable
      include Ovh::Api::Validations

      attribute :acceptance_status,
        type: 'Partner2AcceptanceStatusEnum',
        json_key: 'acceptanceStatus',
        required: false

      attribute :account,
        type: 'Partner2Account',
        json_key: 'account',
        required: true

      attribute :area_of_expertise,
        type: 'Array<Partner2AreaOfExpertiseEnum>',
        json_key: 'areaOfExpertise',
        required: false

      attribute :contact,
        type: 'Partner2Contact',
        json_key: 'contact',
        required: true

      attribute :partners_program_reason,
        type: 'String',
        json_key: 'partnersProgramReason',
        required: false

      attribute :partnership,
        type: 'Partner2PartnerShip',
        json_key: 'partnership',
        required: false

      attribute :sales_projection,
        type: 'Float',
        json_key: 'salesProjection',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
