# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    module Partner2AreaOfExpertiseEnum
      BIG_DATA = 'BigData'
      CONNECTIVITY = 'Connectivity'
      DC = 'DC'
      DOMAIN_NAME = 'DomainName'
      EMAIL_MS_SOLUTION = 'EmailMsSolution'
      HPC = 'HPC'
      NUTANIX = 'Nutanix'
      ORCHESTRATION = 'Orchestration'
      PC = 'PC'
      PCIDSS = 'PCIDSS'
      SECURITY_CERTIF = 'SecurityCertif'
      VPS = 'VPS'
      VO_IP = 'VoIP'
      WH = 'WH'

      def self.all
        @all ||= [
          BIG_DATA,
          CONNECTIVITY,
          DC,
          DOMAIN_NAME,
          EMAIL_MS_SOLUTION,
          HPC,
          NUTANIX,
          ORCHESTRATION,
          PC,
          PCIDSS,
          SECURITY_CERTIF,
          VPS,
          VO_IP,
          WH,
        ].freeze
      end

      def self.valid?(value)
        all.include?(value)
      end
    end
  end
end
