# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    class Partner2PartnerShip
      include Ovh::Api::Serializable
      include Ovh::Api::Validations

      attribute :area_of_expertise,
        type: 'Array<Partner2AreaOfExpertiseEnum>',
        json_key: 'areaOfExpertise',
        required: false

      attribute :email_communication,
        type: 'Boolean',
        json_key: 'emailCommunication',
        required: false

      attribute :partners_program_reason,
        type: 'String',
        json_key: 'partnersProgramReason',
        required: false

      attribute :sales_growth_opportunities,
        type: 'String',
        json_key: 'salesGrowthOpportunities',
        required: false

      attribute :sales_projection,
        type: 'Float',
        json_key: 'salesProjection',
        required: false

      attribute :support_agreement_statement,
        type: 'Boolean',
        json_key: 'supportAgreementStatement',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
