# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    module Partner2PositionEnum
      AF = 'AF'
      BUSINESS_OWNER = 'BusinessOwner'
      HR = 'HR'
      IT_DEVOPS = 'ITDevops'
      IT_OTHER = 'ITOther'
      IT_SYS_ADMIN = 'ITSysAdmin'
      LC = 'LC'
      MARKETING = 'Marketing'
      OTHER = 'Other'
      PRE_SALES = 'PreSales'
      PRODUCTION = 'Production'
      PURCHASING = 'Purchasing'
      RD = 'RD'
      SALES = 'Sales'

      def self.all
        @all ||= [
          AF,
          BUSINESS_OWNER,
          HR,
          IT_DEVOPS,
          IT_OTHER,
          IT_SYS_ADMIN,
          LC,
          MARKETING,
          OTHER,
          PRE_SALES,
          PRODUCTION,
          PURCHASING,
          RD,
          SALES,
        ].freeze
      end

      def self.valid?(value)
        all.include?(value)
      end
    end
  end
end
