# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    module ServicesBillingEngagementEndStrategyEnum
      CANCEL_SERVICE = 'CANCEL_SERVICE'
      REACTIVATE_ENGAGEMENT = 'REACTIVATE_ENGAGEMENT'
      STOP_ENGAGEMENT_FALLBACK_DEFAULT_PRICE = 'STOP_ENGAGEMENT_FALLBACK_DEFAULT_PRICE'
      STOP_ENGAGEMENT_KEEP_PRICE = 'STOP_ENGAGEMENT_KEEP_PRICE'

      def self.all
        @all ||= [
          CANCEL_SERVICE,
          REACTIVATE_ENGAGEMENT,
          STOP_ENGAGEMENT_FALLBACK_DEFAULT_PRICE,
          STOP_ENGAGEMENT_KEEP_PRICE,
        ].freeze
      end

      def self.valid?(value)
        all.include?(value)
      end
    end
  end
end
