# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    module ServiceRenewalTypeEnum
      AUTOMATIC_FORCED_PRODUCT = 'automaticForcedProduct'
      AUTOMATIC_V2012 = 'automaticV2012'
      AUTOMATIC_V2014 = 'automaticV2014'
      AUTOMATIC_V2016 = 'automaticV2016'
      AUTOMATIC_V2024 = 'automaticV2024'
      MANUAL = 'manual'
      ONE_SHOT = 'oneShot'
      OPTION = 'option'

      def self.all
        @all ||= [
          AUTOMATIC_FORCED_PRODUCT,
          AUTOMATIC_V2012,
          AUTOMATIC_V2014,
          AUTOMATIC_V2016,
          AUTOMATIC_V2024,
          MANUAL,
          ONE_SHOT,
          OPTION,
        ].freeze
      end

      def self.valid?(value)
        all.include?(value)
      end
    end
  end
end
