# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    module ServicesExpandedTerminationPolicyEnum
      EMPTY = 'empty'
      TERMINATE_AT_ENGAGEMENT_DATE = 'terminateAtEngagementDate'
      TERMINATE_AT_EXPIRATION_DATE = 'terminateAtExpirationDate'

      def self.all
        @all ||= [
          EMPTY,
          TERMINATE_AT_ENGAGEMENT_DATE,
          TERMINATE_AT_EXPIRATION_DATE,
        ].freeze
      end

      def self.valid?(value)
        all.include?(value)
      end
    end
  end
end
