# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    module ServiceTerminationReasonEnum
      FEATURES_DONT_SUIT_ME = 'FEATURES_DONT_SUIT_ME'
      LACK_OF_PERFORMANCES = 'LACK_OF_PERFORMANCES'
      MIGRATED_TO_ANOTHER_OVH_PRODUCT = 'MIGRATED_TO_ANOTHER_OVH_PRODUCT'
      MIGRATED_TO_COMPETITOR = 'MIGRATED_TO_COMPETITOR'
      NOT_ENOUGH_RECOGNITION = 'NOT_ENOUGH_RECOGNITION'
      NOT_NEEDED_ANYMORE = 'NOT_NEEDED_ANYMORE'
      NOT_RELIABLE = 'NOT_RELIABLE'
      NO_ANSWER = 'NO_ANSWER'
      OTHER = 'OTHER'
      PRODUCT_DIMENSION_DONT_SUIT_ME = 'PRODUCT_DIMENSION_DONT_SUIT_ME'
      PRODUCT_TOOLS_DONT_SUIT_ME = 'PRODUCT_TOOLS_DONT_SUIT_ME'
      TOO_EXPENSIVE = 'TOO_EXPENSIVE'
      TOO_HARD_TO_USE = 'TOO_HARD_TO_USE'
      UNSATIFIED_BY_CUSTOMER_SUPPORT = 'UNSATIFIED_BY_CUSTOMER_SUPPORT'

      def self.all
        @all ||= [
          FEATURES_DONT_SUIT_ME,
          LACK_OF_PERFORMANCES,
          MIGRATED_TO_ANOTHER_OVH_PRODUCT,
          MIGRATED_TO_COMPETITOR,
          NOT_ENOUGH_RECOGNITION,
          NOT_NEEDED_ANYMORE,
          NOT_RELIABLE,
          NO_ANSWER,
          OTHER,
          PRODUCT_DIMENSION_DONT_SUIT_ME,
          PRODUCT_TOOLS_DONT_SUIT_ME,
          TOO_EXPENSIVE,
          TOO_HARD_TO_USE,
          UNSATIFIED_BY_CUSTOMER_SUPPORT,
        ].freeze
      end

      def self.valid?(value)
        all.include?(value)
      end
    end
  end
end
