# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    class ServicesConfirmTermination
      include Ovh::Api::Serializable
      include Ovh::Api::Validations

      attribute :commentary,
        type: 'String',
        json_key: 'commentary',
        required: false

      attribute :commentary_future_use,
        type: 'String',
        json_key: 'commentaryFutureUse',
        required: false

      attribute :commentary_reason,
        type: 'String',
        json_key: 'commentaryReason',
        required: false

      attribute :future_use,
        type: 'ServiceTerminationFutureUseEnum',
        json_key: 'futureUse',
        required: false

      attribute :reason,
        type: 'ServiceTerminationReasonEnum',
        json_key: 'reason',
        required: false

      attribute :token,
        type: 'String',
        json_key: 'token',
        required: true

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
