# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    module ServiceStateEnum
      AUTORENEW_IN_PROGRESS = 'autorenewInProgress'
      EXPIRED = 'expired'
      IN_CREATION = 'inCreation'
      OK = 'ok'
      PENDING_DEBT = 'pendingDebt'
      UN_PAID = 'unPaid'

      def self.all
        @all ||= [
          AUTORENEW_IN_PROGRESS,
          EXPIRED,
          IN_CREATION,
          OK,
          PENDING_DEBT,
          UN_PAID,
        ].freeze
      end

      def self.valid?(value)
        all.include?(value)
      end
    end
  end
end
