# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    class ServiceRenewType
      include Ovh::Api::Serializable
      include Ovh::Api::Validations

      attribute :automatic,
        type: 'Boolean',
        json_key: 'automatic',
        required: false

      attribute :delete_at_expiration,
        type: 'Boolean',
        json_key: 'deleteAtExpiration',
        required: false

      attribute :forced,
        type: 'Boolean',
        json_key: 'forced',
        required: false

      attribute :manual_payment,
        type: 'Boolean',
        json_key: 'manualPayment',
        required: false

      attribute :period,
        type: 'Integer',
        json_key: 'period',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
