# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    module ServiceTerminationFutureUseEnum
      NOT_REPLACING_SERVICE = 'NOT_REPLACING_SERVICE'
      OTHER = 'OTHER'
      SUBSCRIBE_AN_OTHER_SERVICE = 'SUBSCRIBE_AN_OTHER_SERVICE'
      SUBSCRIBE_OTHER_KIND_OF_SERVICE_WITH_COMPETITOR = 'SUBSCRIBE_OTHER_KIND_OF_SERVICE_WITH_COMPETITOR'
      SUBSCRIBE_SIMILAR_SERVICE_WITH_COMPETITOR = 'SUBSCRIBE_SIMILAR_SERVICE_WITH_COMPETITOR'

      def self.all
        @all ||= [
          NOT_REPLACING_SERVICE,
          OTHER,
          SUBSCRIBE_AN_OTHER_SERVICE,
          SUBSCRIBE_OTHER_KIND_OF_SERVICE_WITH_COMPETITOR,
          SUBSCRIBE_SIMILAR_SERVICE_WITH_COMPETITOR,
        ].freeze
      end

      def self.valid?(value)
        all.include?(value)
      end
    end
  end
end
