# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    class SmsAccount
      include Ovh::Api::Serializable
      include Ovh::Api::Validations

      attribute :automatic_recredit_amount,
        type: 'SmsPackQuantityAutomaticRecreditEnum',
        json_key: 'automaticRecreditAmount',
        required: false

      attribute :call_back,
        type: 'String',
        json_key: 'callBack',
        required: false

      attribute :channel,
        type: 'SmsChannelEnum',
        json_key: 'channel',
        required: false

      attribute :credit_threshold_for_automatic_recredit,
        type: 'Float',
        json_key: 'creditThresholdForAutomaticRecredit',
        required: false

      attribute :credits_hold_by_quota,
        type: 'Float',
        json_key: 'creditsHoldByQuota',
        required: false

      attribute :credits_left,
        type: 'Float',
        json_key: 'creditsLeft',
        required: false

      attribute :description,
        type: 'String',
        json_key: 'description',
        required: false

      attribute :name,
        type: 'String',
        json_key: 'name',
        required: false

      attribute :smpp,
        type: 'Boolean',
        json_key: 'smpp',
        required: false

      attribute :sms_response,
        type: 'SmsResponse',
        json_key: 'smsResponse',
        required: false

      attribute :status,
        type: 'SmsStatusAccountEnum',
        json_key: 'status',
        required: false

      attribute :stop_call_back,
        type: 'String',
        json_key: 'stopCallBack',
        required: false

      attribute :templates,
        type: 'SmsTemplates',
        json_key: 'templates',
        required: false

      attribute :user_quantity_with_quota,
        type: 'Integer',
        json_key: 'userQuantityWithQuota',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
