# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    class SmsServiceNameTemplatesControlPostRequest
      include Ovh::Api::Serializable
      include Ovh::Api::Validations

      attribute :activity,
        type: 'SmsTypeTemplateEnum',
        json_key: 'activity',
        required: true

      attribute :description,
        type: 'String',
        json_key: 'description',
        required: false

      attribute :message,
        type: 'String',
        json_key: 'message',
        required: true

      attribute :name,
        type: 'String',
        json_key: 'name',
        required: true

      attribute :reason,
        type: 'String',
        json_key: 'reason',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
