# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    module SmsCodingEnum
      N7BIT = '7bit'
      N8BIT = '8bit'

      def self.all
        @all ||= [
          N7BIT,
          N8BIT,
        ].freeze
      end

      def self.valid?(value)
        all.include?(value)
      end
    end
  end
end
