# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    class SmsEstimatePostRequest
      include Ovh::Api::Serializable
      include Ovh::Api::Validations

      attribute :message,
        type: 'String',
        json_key: 'message',
        required: true

      attribute :no_stop_clause,
        type: 'Boolean',
        json_key: 'noStopClause',
        required: true

      attribute :sender_type,
        type: 'SmsTypeSenderEnum',
        json_key: 'senderType',
        required: true

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
