# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    class SmsTemplates
      include Ovh::Api::Serializable
      include Ovh::Api::Validations

      attribute :customized_email_mode,
        type: 'Boolean',
        json_key: 'customizedEmailMode',
        required: false

      attribute :customized_sms_mode,
        type: 'Boolean',
        json_key: 'customizedSmsMode',
        required: false

      attribute :email_body,
        type: 'String',
        json_key: 'emailBody',
        required: false

      attribute :email_from,
        type: 'String',
        json_key: 'emailFrom',
        required: false

      attribute :email_subject,
        type: 'String',
        json_key: 'emailSubject',
        required: false

      attribute :sms_body,
        type: 'String',
        json_key: 'smsBody',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
