# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    class SmsSenderDocument
      include Ovh::Api::Serializable
      include Ovh::Api::Validations

      attribute :created_at,
        type: 'Time',
        json_key: 'createdAt',
        required: false

      attribute :description,
        type: 'String',
        json_key: 'description',
        required: false

      attribute :document_id,
        type: 'String',
        json_key: 'documentID',
        required: false

      attribute :get_url,
        type: 'String',
        json_key: 'getUrl',
        required: false

      attribute :name,
        type: 'String',
        json_key: 'name',
        required: false

      attribute :put_url,
        type: 'String',
        json_key: 'putUrl',
        required: false

      attribute :size,
        type: 'Integer',
        json_key: 'size',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
