# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    class StartupStartupCompany
      include Ovh::Api::Serializable
      include Ovh::Api::Validations

      attribute :detail,
        type: 'StartupStartupCompanyDetail',
        json_key: 'detail',
        required: false

      attribute :employees_number,
        type: 'StartupEmployeesNumberEnum',
        json_key: 'employeesNumber',
        required: true

      attribute :incubator,
        type: 'StartupStartupCompanyIncubator',
        json_key: 'incubator',
        required: false

      attribute :name,
        type: 'String',
        json_key: 'name',
        required: true

      attribute :related_industry,
        type: 'StartupRelatedIndustryEnum',
        json_key: 'relatedIndustry',
        required: true

      attribute :social_network,
        type: 'StartupStartupCompanySocialNetwork',
        json_key: 'socialNetwork',
        required: false

      attribute :society_website,
        type: 'String',
        json_key: 'societyWebsite',
        required: true

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
