# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    class StartupStartupCompanyDetail
      include Ovh::Api::Serializable
      include Ovh::Api::Validations

      attribute :creationdate,
        type: 'Date',
        json_key: 'creationdate',
        required: true

      attribute :last_year_turnover,
        type: 'Float',
        json_key: 'lastYearTurnover',
        required: true

      attribute :vat_number,
        type: 'String',
        json_key: 'vatNumber',
        required: true

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
