# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    module StartupAwarnessEnum
      EMAIL = 'Email'
      EMPACT_VENTURE = 'EmpactVenture'
      EVENT = 'Event'
      FACEBOOK = 'Facebook'
      INTERNET_SEARCH = 'InternetSearch'
      LINKED_IN = 'LinkedIn'
      ONLINE_ADVERT = 'OnlineAdvert'
      PARTNER = 'Partner'
      TWITTER = 'Twitter'
      WEBSITE = 'Website'
      WORD_OF_MOUTH = 'WordOfMouth'

      def self.all
        @all ||= [
          EMAIL,
          EMPACT_VENTURE,
          EVENT,
          FACEBOOK,
          INTERNET_SEARCH,
          LINKED_IN,
          ONLINE_ADVERT,
          PARTNER,
          TWITTER,
          WEBSITE,
          WORD_OF_MOUTH,
        ].freeze
      end

      def self.valid?(value)
        all.include?(value)
      end
    end
  end
end
