# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    module StartupRelatedIndustryEnum
      AI_WHOLESALE = 'AI_Wholesale'
      ARTISANAT = 'ARTISANAT'
      ASP_SI_IT_SERVICES = 'ASP_SI_ITServices'
      ACCOMMODATION_AND_FOOD_SERVICES = 'Accommodation_and_FoodServices'
      AGRICULTURE = 'Agriculture'
      AGRO_INDUSTRY = 'Agro_industry'
      ART_SPORT_ENTERTAINMENT = 'Art_Sport_Entertainment'
      AUTOMOTIVE = 'Automotive'
      BANKING = 'Banking'
      CONSTRUCTION_AND_ARCHITECTURE = 'Construction_and_Architecture'
      DATABASES_WHOLESALE = 'Databases_Wholesale'
      DIGITAL_SERVICES = 'DigitalServices'
      E_RETAIL = 'E_Retail'
      EDUCATIONAL_SERVICES = 'EducationalServices'
      ENERGY_AND_WATER = 'Energy_and_Water'
      GAME_WHOLESALE = 'Game_Wholesale'
      HEAD_OFFICE = 'HeadOffice'
      HEALTHCARE = 'Healthcare'
      HOST_THE_HOSTER_WHOLESALE = 'Host_the_Hoster_Wholesale'
      HUMAN_RESOURCES = 'Human_Resources'
      IAA_SPROVIDERS_WEB_HOSTERS_DATA = 'IAASproviders_WebHosters_Data'
      LIFE_SCIENCES = 'Life_Sciences'
      MANUFACTURING_INDUSTRY = 'Manufacturing_Industry'
      MINING_INDUSTRY = 'Mining_Industry'
      NON_PROFIT = 'NonProfit'
      OTHER_SERVICES_BUSINESS = 'Other_Services_Business'
      OTHER_SERVICES_PERSONAL = 'Other_Services_Personal'
      OTHERS = 'Others'
      PUBLIC_SECTOR = 'PublicSector'
      REAL_ESTATE = 'Real_Estate'
      RETAIL_AND_TRADE = 'Retail_and_Trade'
      SCIENCE_RD = 'ScienceR&D'
      SOFTWARE_EDITORS = 'Software Editors'
      STORAGE_WHOLESALE = 'Storage_Wholesale'
      TV_MEDIA = 'TV_Media'
      TELECOMMUNICATION_INTERNET = 'Telecommunication_Internet'
      TRANSPORTATION_LOGISTICS = 'Transportation_Logistics'
      VENTURES_FOR_GOOD = 'Ventures_for_Good'
      VIRTUALIZATION_WHOLESALE = 'Virtualization_Wholesale'
      WEB_AGENCIES = 'WebAgencies'

      def self.all
        @all ||= [
          AI_WHOLESALE,
          ARTISANAT,
          ASP_SI_IT_SERVICES,
          ACCOMMODATION_AND_FOOD_SERVICES,
          AGRICULTURE,
          AGRO_INDUSTRY,
          ART_SPORT_ENTERTAINMENT,
          AUTOMOTIVE,
          BANKING,
          CONSTRUCTION_AND_ARCHITECTURE,
          DATABASES_WHOLESALE,
          DIGITAL_SERVICES,
          E_RETAIL,
          EDUCATIONAL_SERVICES,
          ENERGY_AND_WATER,
          GAME_WHOLESALE,
          HEAD_OFFICE,
          HEALTHCARE,
          HOST_THE_HOSTER_WHOLESALE,
          HUMAN_RESOURCES,
          IAA_SPROVIDERS_WEB_HOSTERS_DATA,
          LIFE_SCIENCES,
          MANUFACTURING_INDUSTRY,
          MINING_INDUSTRY,
          NON_PROFIT,
          OTHER_SERVICES_BUSINESS,
          OTHER_SERVICES_PERSONAL,
          OTHERS,
          PUBLIC_SECTOR,
          REAL_ESTATE,
          RETAIL_AND_TRADE,
          SCIENCE_RD,
          SOFTWARE_EDITORS,
          STORAGE_WHOLESALE,
          TV_MEDIA,
          TELECOMMUNICATION_INTERNET,
          TRANSPORTATION_LOGISTICS,
          VENTURES_FOR_GOOD,
          VIRTUALIZATION_WHOLESALE,
          WEB_AGENCIES,
        ].freeze
      end

      def self.valid?(value)
        all.include?(value)
      end
    end
  end
end
