# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    class StorageNetAppSnapshotPolicySchedule
      include Ovh::Api::Serializable
      include Ovh::Api::Validations

      attribute :days,
        type: 'Array<Object>',
        json_key: 'days',
        required: false

      attribute :hours,
        type: 'Array<Object>',
        json_key: 'hours',
        required: false

      attribute :minutes,
        type: 'Array<Object>',
        json_key: 'minutes',
        required: true

      attribute :months,
        type: 'Array<Object>',
        json_key: 'months',
        required: false

      attribute :weekdays,
        type: 'Array<Object>',
        json_key: 'weekdays',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
