# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    class SupportTicketsCreatePostRequest
      include Ovh::Api::Serializable
      include Ovh::Api::Validations

      attribute :body,
        type: 'String',
        json_key: 'body',
        required: true

      attribute :category,
        type: 'SupportTicketCategoryEnum',
        json_key: 'category',
        required: false

      attribute :impact,
        type: 'SupportTicketImpactUrgencyEnum',
        json_key: 'impact',
        required: false

      attribute :product,
        type: 'SupportTicketProductEnum',
        json_key: 'product',
        required: false

      attribute :service_name,
        type: 'String',
        json_key: 'serviceName',
        required: false

      attribute :subcategory,
        type: 'SupportTicketSubCategoryEnum',
        json_key: 'subcategory',
        required: false

      attribute :subject,
        type: 'String',
        json_key: 'subject',
        required: true

      attribute :type,
        type: 'SupportTicketTypeEnum',
        json_key: 'type',
        required: false

      attribute :urgency,
        type: 'SupportTicketImpactUrgencyEnum',
        json_key: 'urgency',
        required: false

      attribute :watchers,
        type: 'Array<Object>',
        json_key: 'watchers',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
