# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    module SupportTicketProductEnum
      ADSL = 'adsl'
      CDN = 'cdn'
      DEDICATED = 'dedicated'
      DEDICATED_BILLING = 'dedicated-billing'
      DEDICATED_OTHER = 'dedicated-other'
      DEDICATEDCLOUD = 'dedicatedcloud'
      DOMAIN = 'domain'
      EXCHANGE = 'exchange'
      FAX = 'fax'
      HOSTING = 'hosting'
      HOUSING = 'housing'
      IAAS = 'iaas'
      MAIL = 'mail'
      NETWORK = 'network'
      PUBLICCLOUD = 'publiccloud'
      SMS = 'sms'
      SSL = 'ssl'
      STORAGE = 'storage'
      TELECOM_BILLING = 'telecom-billing'
      TELECOM_OTHER = 'telecom-other'
      VAC = 'vac'
      VOIP = 'voip'
      VPS = 'vps'
      WEB_BILLING = 'web-billing'
      WEB_OTHER = 'web-other'

      def self.all
        @all ||= [
          ADSL,
          CDN,
          DEDICATED,
          DEDICATED_BILLING,
          DEDICATED_OTHER,
          DEDICATEDCLOUD,
          DOMAIN,
          EXCHANGE,
          FAX,
          HOSTING,
          HOUSING,
          IAAS,
          MAIL,
          NETWORK,
          PUBLICCLOUD,
          SMS,
          SSL,
          STORAGE,
          TELECOM_BILLING,
          TELECOM_OTHER,
          VAC,
          VOIP,
          VPS,
          WEB_BILLING,
          WEB_OTHER,
        ].freeze
      end

      def self.valid?(value)
        all.include?(value)
      end
    end
  end
end
