# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    class TelephonyBillingAccountOvhPabxServiceNameMenuPostRequest
      include Ovh::Api::Serializable
      include Ovh::Api::Validations

      attribute :greet_sound,
        type: 'Integer',
        json_key: 'greetSound',
        required: false

      attribute :greet_sound_tts,
        type: 'Integer',
        json_key: 'greetSoundTts',
        required: false

      attribute :inter_digit_timeout,
        type: 'Integer',
        json_key: 'interDigitTimeout',
        required: false

      attribute :invalid_sound,
        type: 'Integer',
        json_key: 'invalidSound',
        required: false

      attribute :invalid_sound_tts,
        type: 'Integer',
        json_key: 'invalidSoundTts',
        required: false

      attribute :name,
        type: 'String',
        json_key: 'name',
        required: true

      attribute :timeout,
        type: 'Integer',
        json_key: 'timeout',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
