# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    module TelephonyOutplanNotificationBlockEnum
      BLOCK_ALL_CALLS = 'blockAllCalls'
      BLOCK_INCOMING_CALLS = 'blockIncomingCalls'
      BLOCK_OUTGOING_CALLS = 'blockOutgoingCalls'
      NONE = 'none'

      def self.all
        @all ||= [
          BLOCK_ALL_CALLS,
          BLOCK_INCOMING_CALLS,
          BLOCK_OUTGOING_CALLS,
          NONE,
        ].freeze
      end

      def self.valid?(value)
        all.include?(value)
      end
    end
  end
end
