# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    module TelephonyScreenListNatureEnum
      FAX = 'fax'
      INTERNATIONAL = 'international'
      SERVICES = 'services'
      SPECIAL = 'special'
      VOICEMAIL = 'voicemail'

      def self.all
        @all ||= [
          FAX,
          INTERNATIONAL,
          SERVICES,
          SPECIAL,
          VOICEMAIL,
        ].freeze
      end

      def self.valid?(value)
        all.include?(value)
      end
    end
  end
end
