# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    class TelephonyBillingAccountOvhPabxServiceNameDialplanPostRequest
      include Ovh::Api::Serializable
      include Ovh::Api::Validations

      attribute :anonymous_rejection,
        type: 'Boolean',
        json_key: 'anonymousRejection',
        required: true

      attribute :name,
        type: 'String',
        json_key: 'name',
        required: true

      attribute :show_caller_number,
        type: 'TelephonyOvhPabxDialplanNumberPresentationEnum',
        json_key: 'showCallerNumber',
        required: true

      attribute :transfer_timeout,
        type: 'Integer',
        json_key: 'transferTimeout',
        required: true

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
