# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    class TelephonyRma
      include Ovh::Api::Serializable
      include Ovh::Api::Validations

      attribute :cancellable,
        type: 'Boolean',
        json_key: 'cancellable',
        required: false

      attribute :creation_datetime,
        type: 'Time',
        json_key: 'creationDatetime',
        required: false

      attribute :equipment_reference,
        type: 'String',
        json_key: 'equipmentReference',
        required: false

      attribute :id,
        type: 'String',
        json_key: 'id',
        required: false

      attribute :new_merchandise,
        type: 'String',
        json_key: 'newMerchandise',
        required: false

      attribute :offer_type_new,
        type: 'TelephonyRmaOfferTypeEnum',
        json_key: 'offerTypeNew',
        required: false

      attribute :offer_type_old,
        type: 'TelephonyRmaOfferTypeEnum',
        json_key: 'offerTypeOld',
        required: false

      attribute :process,
        type: 'TelephonyRmaReplaceTypeEnum',
        json_key: 'process',
        required: false

      attribute :reception_datetime,
        type: 'Time',
        json_key: 'receptionDatetime',
        required: false

      attribute :shipping_contact,
        type: 'TelephonyContact',
        json_key: 'shippingContact',
        required: false

      attribute :status,
        type: 'TelephonyRmaStatusEnum',
        json_key: 'status',
        required: false

      attribute :steps,
        type: 'Array<TelephonyRmaStep>',
        json_key: 'steps',
        required: false

      attribute :termination_datetime,
        type: 'Time',
        json_key: 'terminationDatetime',
        required: false

      attribute :type,
        type: 'TelephonyRmaTypeEnum',
        json_key: 'type',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
