# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    module TelephonyOvhPabxHuntingQueueRecordDisablingLanguageEnum
      ENGLISH = 'english'
      FRENCH = 'french'

      def self.all
        @all ||= [
          ENGLISH,
          FRENCH,
        ].freeze
      end

      def self.valid?(value)
        all.include?(value)
      end
    end
  end
end
