# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    class TelephonyFunctionKey
      include Ovh::Api::Serializable
      include Ovh::Api::Validations

      attribute :default,
        type: 'String',
        json_key: 'default',
        required: false

      attribute :function,
        type: 'String',
        json_key: 'function',
        required: false

      attribute :key_num,
        type: 'Integer',
        json_key: 'keyNum',
        required: false

      attribute :label,
        type: 'String',
        json_key: 'label',
        required: false

      attribute :parameter,
        type: 'String',
        json_key: 'parameter',
        required: false

      attribute :type,
        type: 'String',
        json_key: 'type',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
