# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    class TelephonyTimeConditionOptions
      include Ovh::Api::Serializable
      include Ovh::Api::Validations

      attribute :slot1_number,
        type: 'String',
        json_key: 'slot1Number',
        required: false

      attribute :slot1_type,
        type: 'TelephonyTimeConditionsSlotTypeEnum',
        json_key: 'slot1Type',
        required: false

      attribute :slot2_number,
        type: 'String',
        json_key: 'slot2Number',
        required: false

      attribute :slot2_type,
        type: 'TelephonyTimeConditionsSlotTypeEnum',
        json_key: 'slot2Type',
        required: false

      attribute :slot3_number,
        type: 'String',
        json_key: 'slot3Number',
        required: false

      attribute :slot3_type,
        type: 'TelephonyTimeConditionsSlotTypeEnum',
        json_key: 'slot3Type',
        required: false

      attribute :status,
        type: 'TelephonyTimeConditionsGlobalStatusEnum',
        json_key: 'status',
        required: false

      attribute :timeout,
        type: 'TelephonyTimeConditionsTimeoutEnum',
        json_key: 'timeout',
        required: false

      attribute :unavailable_number,
        type: 'String',
        json_key: 'unavailableNumber',
        required: false

      attribute :unavailable_type,
        type: 'TelephonyTimeConditionsSlotTypeEnum',
        json_key: 'unavailableType',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
