# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    module TelephonyAntihackActionEnum
      AUTHORIZE_ALL = 'AUTHORIZE_ALL'
      AUTHORIZE_ONE_NUMBER = 'AUTHORIZE_ONE_NUMBER'
      BLOCK_ALL = 'BLOCK_ALL'
      BLOCK_ONE_NUMBER = 'BLOCK_ONE_NUMBER'

      def self.all
        @all ||= [
          AUTHORIZE_ALL,
          AUTHORIZE_ONE_NUMBER,
          BLOCK_ALL,
          BLOCK_ONE_NUMBER,
        ].freeze
      end

      def self.valid?(value)
        all.include?(value)
      end
    end
  end
end
