# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    module TelephonyRmaPublicTypeEnum
      CHANGE_TO_ANOTHER_PHONE_EQUIPMENT__RESTITUTION_FIRST_AND_SHIPPING_THEN = 'change to another phone/equipment (restitution first and shipping then)'
      RESTITUTION_BUT_KEEP_THE_SERVICE_ENABLE = 'restitution but keep the service enable'

      def self.all
        @all ||= [
          CHANGE_TO_ANOTHER_PHONE_EQUIPMENT__RESTITUTION_FIRST_AND_SHIPPING_THEN,
          RESTITUTION_BUT_KEEP_THE_SERVICE_ENABLE,
        ].freeze
      end

      def self.valid?(value)
        all.include?(value)
      end
    end
  end
end
