# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    module TelephonyCallsGeneratorDialplanEnum
      READ_TEXT = 'ReadText'
      REQUEST_APPOINTMENT_CONFIRMATION = 'RequestAppointmentConfirmation'
      REQUEST_APPOINTMENT_CONFIRMATION_WITH_TRANSFER = 'RequestAppointmentConfirmationWithTransfer'

      def self.all
        @all ||= [
          READ_TEXT,
          REQUEST_APPOINTMENT_CONFIRMATION,
          REQUEST_APPOINTMENT_CONFIRMATION_WITH_TRANSFER,
        ].freeze
      end

      def self.valid?(value)
        all.include?(value)
      end
    end
  end
end
