# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    module TelephonyServiceVoicemailAudioFormatEnum
      AIFF = 'aiff'
      AU = 'au'
      FLAC = 'flac'
      MP3 = 'mp3'
      OGG = 'ogg'
      WAV = 'wav'

      def self.all
        @all ||= [
          AIFF,
          AU,
          FLAC,
          MP3,
          OGG,
          WAV,
        ].freeze
      end

      def self.valid?(value)
        all.include?(value)
      end
    end
  end
end
