# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    module TelephonyRmaTypeEnum
      AFTER_SALE_EQUIPMENT_SERVICE_EXCHANGE = 'after sale equipment service exchange'
      AFTER_SALE_PHONE_SERVICE_EXCHANGE = 'after sale phone service exchange'
      EQUIPMENT_RESTITUTION = 'equipment restitution'
      FAST_EXCHANGE = 'fast exchange'
      OLD_MERCHANDISE_RECEPTION_BEFORE_EXCHANGE = 'old merchandise reception before exchange'
      PHONE_RESTITUTION = 'phone restitution'
      RESENDS_DUE_TO_SHIPPING_LOST_BY_THE_CARRIER = 'resends due to shipping lost by the carrier'
      RESENDS_DUE_TO_SHIPPING_NOT_WITHDRAW = 'resends due to shipping not withdraw'
      SPECIFIC_RETURN_MERCHANDISE_AUTHORISATION = 'specific return merchandise authorisation'
      TERMINATION = 'termination'
      UNKNOWN = 'unknown'

      def self.all
        @all ||= [
          AFTER_SALE_EQUIPMENT_SERVICE_EXCHANGE,
          AFTER_SALE_PHONE_SERVICE_EXCHANGE,
          EQUIPMENT_RESTITUTION,
          FAST_EXCHANGE,
          OLD_MERCHANDISE_RECEPTION_BEFORE_EXCHANGE,
          PHONE_RESTITUTION,
          RESENDS_DUE_TO_SHIPPING_LOST_BY_THE_CARRIER,
          RESENDS_DUE_TO_SHIPPING_NOT_WITHDRAW,
          SPECIFIC_RETURN_MERCHANDISE_AUTHORISATION,
          TERMINATION,
          UNKNOWN,
        ].freeze
      end

      def self.valid?(value)
        all.include?(value)
      end
    end
  end
end
