# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    module TelephonyTimeZone
      EUROPE_BERLIN = 'Europe/Berlin'
      EUROPE_BRUSSELS = 'Europe/Brussels'
      EUROPE_LONDON = 'Europe/London'
      EUROPE_MADRID = 'Europe/Madrid'
      EUROPE_PARIS = 'Europe/Paris'
      EUROPE_ZURICH = 'Europe/Zurich'

      def self.all
        @all ||= [
          EUROPE_BERLIN,
          EUROPE_BRUSSELS,
          EUROPE_LONDON,
          EUROPE_MADRID,
          EUROPE_PARIS,
          EUROPE_ZURICH,
        ].freeze
      end

      def self.valid?(value)
        all.include?(value)
      end
    end
  end
end
