# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    class TelephonyBillingAccountLineServiceNameAutomaticCallPostRequest
      include Ovh::Api::Serializable
      include Ovh::Api::Validations

      attribute :bridge_number_dialplan,
        type: 'String',
        json_key: 'bridgeNumberDialplan',
        required: false

      attribute :called_number,
        type: 'String',
        json_key: 'calledNumber',
        required: true

      attribute :calling_number,
        type: 'String',
        json_key: 'callingNumber',
        required: false

      attribute :dialplan,
        type: 'TelephonyCallsGeneratorDialplanEnum',
        json_key: 'dialplan',
        required: true

      attribute :is_anonymous,
        type: 'Boolean',
        json_key: 'isAnonymous',
        required: true

      attribute :playback_audio_file_dialplan,
        type: 'String',
        json_key: 'playbackAudioFileDialplan',
        required: false

      attribute :timeout,
        type: 'Integer',
        json_key: 'timeout',
        required: false

      attribute :tts_text_dialplan,
        type: 'String',
        json_key: 'ttsTextDialplan',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
