# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    module TelephonyTypeEnum
      CARRIER_SIP = 'carrierSip'
      CLOUD_HUNTING = 'cloudHunting'
      CLOUD_IVR = 'cloudIvr'
      CONFERENCE = 'conference'
      CONTACT_CENTER_SOLUTION = 'contactCenterSolution'
      CONTACT_CENTER_SOLUTION_EXPERT = 'contactCenterSolutionExpert'
      DDI = 'ddi'
      EASY_HUNTING = 'easyHunting'
      EMPTY = 'empty'
      FAX = 'fax'
      FREEFAX = 'freefax'
      MGCP = 'mgcp'
      OLD_CONFERENCE = 'oldConference'
      PLUG_AND_FAX = 'plugAndFax'
      REDIRECT = 'redirect'
      SIP = 'sip'
      SVI = 'svi'
      VOICEFAX = 'voicefax'
      VOICEMAIL = 'voicemail'
      VXML = 'vxml'

      def self.all
        @all ||= [
          CARRIER_SIP,
          CLOUD_HUNTING,
          CLOUD_IVR,
          CONFERENCE,
          CONTACT_CENTER_SOLUTION,
          CONTACT_CENTER_SOLUTION_EXPERT,
          DDI,
          EASY_HUNTING,
          EMPTY,
          FAX,
          FREEFAX,
          MGCP,
          OLD_CONFERENCE,
          PLUG_AND_FAX,
          REDIRECT,
          SIP,
          SVI,
          VOICEFAX,
          VOICEMAIL,
          VXML,
        ].freeze
      end

      def self.valid?(value)
        all.include?(value)
      end
    end
  end
end
