# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    module TelephonyLineNotificationsLogsFrequencyEnum
      NEVER = 'Never'
      ONCE_A_DAY = 'Once a day'
      TWICE_A_DAY = 'Twice a day'

      def self.all
        @all ||= [
          NEVER,
          ONCE_A_DAY,
          TWICE_A_DAY,
        ].freeze
      end

      def self.valid?(value)
        all.include?(value)
      end
    end
  end
end
