# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    module TelephonyPhoneConfigurationTypeEnum
      BOOLEAN = 'boolean'
      ENUM = 'enum'
      HIDDEN = 'hidden'
      IPV4 = 'ipv4'
      NUMERIC = 'numeric'
      STRING = 'string'

      def self.all
        @all ||= [
          BOOLEAN,
          ENUM,
          HIDDEN,
          IPV4,
          NUMERIC,
          STRING,
        ].freeze
      end

      def self.valid?(value)
        all.include?(value)
      end
    end
  end
end
