# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    module TelephonyTimeConditionsPolicyEnum
      AVAILABLE = 'available'
      SLOT1 = 'slot1'
      SLOT2 = 'slot2'
      SLOT3 = 'slot3'

      def self.all
        @all ||= [
          AVAILABLE,
          SLOT1,
          SLOT2,
          SLOT3,
        ].freeze
      end

      def self.valid?(value)
        all.include?(value)
      end
    end
  end
end
