# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    module TelephonyOfferTaskActionEnum
      CONVERT_TO_ALIAS = 'convertToAlias'
      CONVERT_TO_SIP = 'convertToSip'
      MIGRATE_TO_NEW_VOICEMAIL = 'migrateToNewVoicemail'
      REMOVE_SIMLTANEOUS_LINES = 'removeSimltaneousLines'
      SWITCH_SERVER = 'switchServer'
      TERMINATION = 'termination'
      UPDATE_FIRMWARE = 'updateFirmware'
      UPGRADE = 'upgrade'

      def self.all
        @all ||= [
          CONVERT_TO_ALIAS,
          CONVERT_TO_SIP,
          MIGRATE_TO_NEW_VOICEMAIL,
          REMOVE_SIMLTANEOUS_LINES,
          SWITCH_SERVER,
          TERMINATION,
          UPDATE_FIRMWARE,
          UPGRADE,
        ].freeze
      end

      def self.valid?(value)
        all.include?(value)
      end
    end
  end
end
