# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    module TelephonyTonesTypeEnum
      CALL_WAITING = 'callWaiting'
      END_CALL = 'endCall'
      ON_HOLD = 'onHold'
      RINGBACK = 'ringback'

      def self.all
        @all ||= [
          CALL_WAITING,
          END_CALL,
          ON_HOLD,
          RINGBACK,
        ].freeze
      end

      def self.valid?(value)
        all.include?(value)
      end
    end
  end
end
