# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    module TelephonyConferenceLanguageEnum
      DE = 'de'
      EN = 'en'
      ES = 'es'
      FR = 'fr'
      IT = 'it'

      def self.all
        @all ||= [
          DE,
          EN,
          ES,
          FR,
          IT,
        ].freeze
      end

      def self.valid?(value)
        all.include?(value)
      end
    end
  end
end
