# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    module TelephonyOvhPabxDialplanExtensionRuleActionEnum
      BRIDGE = 'bridge'
      ENDLESS_PLAYBACK = 'endless_playback'
      HANGUP = 'hangup'
      HUNTING = 'hunting'
      IVR = 'ivr'
      PLAYBACK = 'playback'
      READ_DTMF = 'readDtmf'
      SET_CALLER_NAME = 'setCallerName'
      SLEEP = 'sleep'
      TTS = 'tts'
      VOICEMAIL = 'voicemail'

      def self.all
        @all ||= [
          BRIDGE,
          ENDLESS_PLAYBACK,
          HANGUP,
          HUNTING,
          IVR,
          PLAYBACK,
          READ_DTMF,
          SET_CALLER_NAME,
          SLEEP,
          TTS,
          VOICEMAIL,
        ].freeze
      end

      def self.valid?(value)
        all.include?(value)
      end
    end
  end
end
