# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    class TelephonyOvhPabxHuntingQueue
      include Ovh::Api::Serializable
      include Ovh::Api::Validations

      attribute :action_on_closure,
        type: 'TelephonyOvhPabxQueueActionEnum',
        json_key: 'actionOnClosure',
        required: false

      attribute :action_on_closure_param,
        type: 'String',
        json_key: 'actionOnClosureParam',
        required: false

      attribute :action_on_overflow,
        type: 'TelephonyOvhPabxQueueActionEnum',
        json_key: 'actionOnOverflow',
        required: false

      attribute :action_on_overflow_param,
        type: 'String',
        json_key: 'actionOnOverflowParam',
        required: false

      attribute :ask_for_record_disabling,
        type: 'Boolean',
        json_key: 'askForRecordDisabling',
        required: false

      attribute :confirm_key,
        type: 'TelephonyOvhPabxIvrMenuKeyEnum',
        json_key: 'confirmKey',
        required: false

      attribute :description,
        type: 'String',
        json_key: 'description',
        required: false

      attribute :follow_call_forwards,
        type: 'Boolean',
        json_key: 'followCallForwards',
        required: false

      attribute :max_member,
        type: 'Integer',
        json_key: 'maxMember',
        required: false

      attribute :max_wait_time,
        type: 'Integer',
        json_key: 'maxWaitTime',
        required: false

      attribute :queue_id,
        type: 'Integer',
        json_key: 'queueId',
        required: false

      attribute :record,
        type: 'Boolean',
        json_key: 'record',
        required: false

      attribute :record_disabling_digit,
        type: 'TelephonyOvhPabxHuntingQueueRecordDisablingDigitEnum',
        json_key: 'recordDisablingDigit',
        required: false

      attribute :record_disabling_language,
        type: 'TelephonyOvhPabxHuntingQueueRecordDisablingLanguageEnum',
        json_key: 'recordDisablingLanguage',
        required: false

      attribute :sound_on_hold,
        type: 'Integer',
        json_key: 'soundOnHold',
        required: false

      attribute :strategy,
        type: 'TelephonyOvhPabxHuntingQueueStrategyEnum',
        json_key: 'strategy',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
