# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    module TelephonyOvhPabxDialplanExtensionConditionTimeWeekDayEnum
      FRIDAY = 'friday'
      MONDAY = 'monday'
      SATURDAY = 'saturday'
      SUNDAY = 'sunday'
      THURSDAY = 'thursday'
      TUESDAY = 'tuesday'
      WEDNESDAY = 'wednesday'

      def self.all
        @all ||= [
          FRIDAY,
          MONDAY,
          SATURDAY,
          SUNDAY,
          THURSDAY,
          TUESDAY,
          WEDNESDAY,
        ].freeze
      end

      def self.valid?(value)
        all.include?(value)
      end
    end
  end
end
