# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    class TelephonyFaxProperties
      include Ovh::Api::Serializable
      include Ovh::Api::Validations

      attribute :call_number,
        type: 'String',
        json_key: 'callNumber',
        required: false

      attribute :country_code,
        type: 'String',
        json_key: 'countryCode',
        required: false

      attribute :fax_max_call,
        type: 'TelephonyFaxSendingTries',
        json_key: 'faxMaxCall',
        required: false

      attribute :fax_quality,
        type: 'TelephonyFaxQualityEnum',
        json_key: 'faxQuality',
        required: false

      attribute :fax_tag_line,
        type: 'String',
        json_key: 'faxTagLine',
        required: false

      attribute :from_email,
        type: 'String',
        json_key: 'fromEmail',
        required: false

      attribute :from_name,
        type: 'String',
        json_key: 'fromName',
        required: false

      attribute :mail_format,
        type: 'TelephonyFaxMailFormatEnum',
        json_key: 'mailFormat',
        required: false

      attribute :receiver,
        type: 'String',
        json_key: 'receiver',
        required: false

      attribute :redirection_email,
        type: 'Array<Object>',
        json_key: 'redirectionEmail',
        required: false

      attribute :reject_anonymous,
        type: 'Boolean',
        json_key: 'rejectAnonymous',
        required: false

      attribute :sender,
        type: 'String',
        json_key: 'sender',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
