# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    class TelephonyBillingAccount
      include Ovh::Api::Serializable
      include Ovh::Api::Validations

      attribute :allowed_outplan,
        type: 'OrderPrice',
        json_key: 'allowedOutplan',
        required: false

      attribute :billing_account,
        type: 'String',
        json_key: 'billingAccount',
        required: false

      attribute :credit_threshold,
        type: 'OrderPrice',
        json_key: 'creditThreshold',
        required: false

      attribute :current_outplan,
        type: 'OrderPrice',
        json_key: 'currentOutplan',
        required: false

      attribute :description,
        type: 'String',
        json_key: 'description',
        required: false

      attribute :has_special_numbers,
        type: 'Boolean',
        json_key: 'hasSpecialNumbers',
        required: false

      attribute :hidden_external_number,
        type: 'Boolean',
        json_key: 'hiddenExternalNumber',
        required: false

      attribute :override_displayed_number,
        type: 'Boolean',
        json_key: 'overrideDisplayedNumber',
        required: false

      attribute :security_deposit,
        type: 'OrderPrice',
        json_key: 'securityDeposit',
        required: false

      attribute :status,
        type: 'TelephonyBillingAccountStatusEnum',
        json_key: 'status',
        required: false

      attribute :trusted,
        type: 'Boolean',
        json_key: 'trusted',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
