# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    module TelephonyNumberCountryCodeEnum
      N32 = '32'
      N33 = '33'
      N34 = '34'
      N41 = '41'
      N44 = '44'
      N49 = '49'

      def self.all
        @all ||= [
          N32,
          N33,
          N34,
          N41,
          N44,
          N49,
        ].freeze
      end

      def self.valid?(value)
        all.include?(value)
      end
    end
  end
end
