# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    module TelephonyRmaReplaceTypeEnum
      CHANGE_PHONE = 'changePhone'
      PHONE_RESTITUTION = 'phoneRestitution'
      UNDEFINED = 'undefined'

      def self.all
        @all ||= [
          CHANGE_PHONE,
          PHONE_RESTITUTION,
          UNDEFINED,
        ].freeze
      end

      def self.valid?(value)
        all.include?(value)
      end
    end
  end
end
