# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    module TelephonyTimeConditionsTimeoutEnum
      N5 = '5'
      N10 = '10'
      N15 = '15'
      N20 = '20'
      N25 = '25'
      N30 = '30'
      N35 = '35'
      N40 = '40'
      N45 = '45'
      N50 = '50'
      N55 = '55'
      N60 = '60'
      N65 = '65'
      N70 = '70'
      N75 = '75'
      N80 = '80'
      N85 = '85'
      N90 = '90'

      def self.all
        @all ||= [
          N5,
          N10,
          N15,
          N20,
          N25,
          N30,
          N35,
          N40,
          N45,
          N50,
          N55,
          N60,
          N65,
          N70,
          N75,
          N80,
          N85,
          N90,
        ].freeze
      end

      def self.valid?(value)
        all.include?(value)
      end
    end
  end
end
