# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    module TelephonyFaxSendingTries
      N1 = '1'
      N2 = '2'
      N3 = '3'
      N4 = '4'
      N5 = '5'
      N6 = '6'
      N7 = '7'
      N8 = '8'
      N9 = '9'

      def self.all
        @all ||= [
          N1,
          N2,
          N3,
          N4,
          N5,
          N6,
          N7,
          N8,
          N9,
        ].freeze
      end

      def self.valid?(value)
        all.include?(value)
      end
    end
  end
end
