# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    module TelephonyNumberPoolEnum
      N10 = '10'
      N50 = '50'
      N100 = '100'

      def self.all
        @all ||= [
          N10,
          N50,
          N100,
        ].freeze
      end

      def self.valid?(value)
        all.include?(value)
      end
    end
  end
end
