# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    class TelephonyPhoneConfigurationProperty
      include Ovh::Api::Serializable
      include Ovh::Api::Validations

      attribute :default,
        type: 'String',
        json_key: 'default',
        required: false

      attribute :description,
        type: 'String',
        json_key: 'description',
        required: false

      attribute :enum,
        type: 'Array<Object>',
        json_key: 'enum',
        required: false

      attribute :group,
        type: 'String',
        json_key: 'group',
        required: false

      attribute :level,
        type: 'TelephonyPhoneConfigurationLevelEnum',
        json_key: 'level',
        required: false

      attribute :maxlength,
        type: 'Integer',
        json_key: 'maxlength',
        required: false

      attribute :name,
        type: 'String',
        json_key: 'name',
        required: false

      attribute :range_value,
        type: 'ComplexTypeRangeLong',
        json_key: 'rangeValue',
        required: false

      attribute :type,
        type: 'TelephonyPhoneConfigurationTypeEnum',
        json_key: 'type',
        required: false

      attribute :value,
        type: 'String',
        json_key: 'value',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
