# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    class TelephonyConferenceRoom
      include Ovh::Api::Serializable
      include Ovh::Api::Validations

      attribute :announce_file,
        type: 'Boolean',
        json_key: 'announceFile',
        required: false

      attribute :announce_filename,
        type: 'String',
        json_key: 'announceFilename',
        required: false

      attribute :announce_sound_id,
        type: 'Integer',
        json_key: 'announceSoundId',
        required: false

      attribute :anonymous_rejection,
        type: 'Boolean',
        json_key: 'anonymousRejection',
        required: false

      attribute :enter_muted,
        type: 'Boolean',
        json_key: 'enterMuted',
        required: false

      attribute :events_channel,
        type: 'String',
        json_key: 'eventsChannel',
        required: false

      attribute :expiration_date,
        type: 'Time',
        json_key: 'expirationDate',
        required: false

      attribute :language,
        type: 'TelephonyConferenceLanguageEnum',
        json_key: 'language',
        required: false

      attribute :pin,
        type: 'String',
        json_key: 'pin',
        required: false

      attribute :record_status,
        type: 'Boolean',
        json_key: 'recordStatus',
        required: false

      attribute :report_email,
        type: 'String',
        json_key: 'reportEmail',
        required: false

      attribute :report_status,
        type: 'TelephonyConferenceReportStatusEnum',
        json_key: 'reportStatus',
        required: false

      attribute :room_number,
        type: 'Integer',
        json_key: 'roomNumber',
        required: false

      attribute :white_label_report,
        type: 'Boolean',
        json_key: 'whiteLabelReport',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
