# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    class TelephonySchedulerEvent
      include Ovh::Api::Serializable
      include Ovh::Api::Validations

      attribute :categories,
        type: 'TelephonySchedulerCategoryEnum',
        json_key: 'categories',
        required: false

      attribute :date_end,
        type: 'Time',
        json_key: 'dateEnd',
        required: false

      attribute :date_start,
        type: 'Time',
        json_key: 'dateStart',
        required: false

      attribute :description,
        type: 'String',
        json_key: 'description',
        required: false

      attribute :title,
        type: 'String',
        json_key: 'title',
        required: false

      attribute :uid,
        type: 'String',
        json_key: 'uid',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
