# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    module VpsVncProtocolEnum
      VNC = 'VNC'
      VNC_OVER_WEB_SOCKET = 'VNCOverWebSocket'

      def self.all
        @all ||= [
          VNC,
          VNC_OVER_WEB_SOCKET,
        ].freeze
      end

      def self.valid?(value)
        all.include?(value)
      end
    end
  end
end
