# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    class VpsDisk
      include Ovh::Api::Serializable
      include Ovh::Api::Validations

      attribute :bandwidth_limit,
        type: 'Integer',
        json_key: 'bandwidthLimit',
        required: false

      attribute :id,
        type: 'Integer',
        json_key: 'id',
        required: false

      attribute :low_free_space_threshold,
        type: 'Integer',
        json_key: 'lowFreeSpaceThreshold',
        required: false

      attribute :monitoring,
        type: 'Boolean',
        json_key: 'monitoring',
        required: false

      attribute :service_name,
        type: 'String',
        json_key: 'serviceName',
        required: false

      attribute :size,
        type: 'Integer',
        json_key: 'size',
        required: false

      attribute :state,
        type: 'VpsDiskStateEnum',
        json_key: 'state',
        required: false

      attribute :type,
        type: 'VpsDiskTypeEnum',
        json_key: 'type',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
