# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    class VpsReinstallPost
      include Ovh::Api::Serializable
      include Ovh::Api::Validations

      attribute :do_not_send_password,
        type: 'Boolean',
        json_key: 'doNotSendPassword',
        required: false

      attribute :language,
        type: 'String',
        json_key: 'language',
        required: false

      attribute :public_ssh_key,
        type: 'String',
        json_key: 'publicSshKey',
        required: false

      attribute :software_id,
        type: 'Array<Object>',
        json_key: 'softwareId',
        required: false

      attribute :ssh_key,
        type: 'Array<Object>',
        json_key: 'sshKey',
        required: false

      attribute :template_id,
        type: 'Integer',
        json_key: 'templateId',
        required: true

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
