# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    class VpsVPS
      include Ovh::Api::Serializable
      include Ovh::Api::Validations

      attribute :cluster,
        type: 'String',
        json_key: 'cluster',
        required: false

      attribute :display_name,
        type: 'String',
        json_key: 'displayName',
        required: false

      attribute :keymap,
        type: 'VpsVpsKeymapEnum',
        json_key: 'keymap',
        required: false

      attribute :lock_status,
        type: 'VpsLockStatus',
        json_key: 'lockStatus',
        required: false

      attribute :memory_limit,
        type: 'Integer',
        json_key: 'memoryLimit',
        required: false

      attribute :model,
        type: 'VpsModel',
        json_key: 'model',
        required: false

      attribute :monitoring_ip_blocks,
        type: 'Array<String>',
        json_key: 'monitoringIpBlocks',
        required: false

      attribute :name,
        type: 'String',
        json_key: 'name',
        required: false

      attribute :netboot_mode,
        type: 'VpsVpsNetbootEnum',
        json_key: 'netbootMode',
        required: false

      attribute :offer_type,
        type: 'VpsVpsOfferEnum',
        json_key: 'offerType',
        required: false

      attribute :sla_monitoring,
        type: 'Boolean',
        json_key: 'slaMonitoring',
        required: false

      attribute :state,
        type: 'VpsVpsStateEnum',
        json_key: 'state',
        required: false

      attribute :vcore,
        type: 'Integer',
        json_key: 'vcore',
        required: false

      attribute :zone,
        type: 'String',
        json_key: 'zone',
        required: false

      attribute :zone_type,
        type: 'VpsZoneTypeEnum',
        json_key: 'zoneType',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
