# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    class VpsIp
      include Ovh::Api::Serializable
      include Ovh::Api::Validations

      attribute :gateway,
        type: 'String',
        json_key: 'gateway',
        required: false

      attribute :geolocation,
        type: 'VpsIpGeolocationEnum',
        json_key: 'geolocation',
        required: false

      attribute :ip_address,
        type: 'String',
        json_key: 'ipAddress',
        required: false

      attribute :mac_address,
        type: 'String',
        json_key: 'macAddress',
        required: false

      attribute :reverse,
        type: 'String',
        json_key: 'reverse',
        required: false

      attribute :type,
        type: 'VpsIpTypeEnum',
        json_key: 'type',
        required: false

      attribute :version,
        type: 'CoreTypesIpVersionEnum',
        json_key: 'version',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
