# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    class VrackPublicRoutingPriority
      include Ovh::Api::Serializable
      include Ovh::Api::Validations

      attribute :availability_zones,
        type: 'Array<VrackPublicRoutingDefinition>',
        json_key: 'availabilityZones',
        required: false

      attribute :priority_id,
        type: 'String',
        json_key: 'priorityId',
        required: false

      attribute :region,
        type: 'String',
        json_key: 'region',
        required: false

      attribute :type,
        type: 'VrackPublicRoutingPriorityTypeEnum',
        json_key: 'type',
        required: false

      attribute :vrack,
        type: 'String',
        json_key: 'vrack',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
