# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    module XanderContactFieldEnum
      ADDRESS_CITY = 'address.city'
      ADDRESS_COUNTRY = 'address.country'
      ADDRESS_LINE1 = 'address.line1'
      ADDRESS_LINE2 = 'address.line2'
      ADDRESS_LINE3 = 'address.line3'
      ADDRESS_OTHER_DETAILS = 'address.otherDetails'
      ADDRESS_PROVINCE = 'address.province'
      ADDRESS_ZIP = 'address.zip'
      BIRTH_CITY = 'birthCity'
      BIRTH_COUNTRY = 'birthCountry'
      BIRTH_DAY = 'birthDay'
      BIRTH_ZIP = 'birthZip'
      CELL_PHONE = 'cellPhone'
      COMPANY_NATIONAL_IDENTIFICATION_NUMBER = 'companyNationalIdentificationNumber'
      EMAIL = 'email'
      FAX = 'fax'
      FIRST_NAME = 'firstName'
      GENDER = 'gender'
      LANGUAGE = 'language'
      LAST_NAME = 'lastName'
      LEGAL_FORM = 'legalForm'
      NATIONAL_IDENTIFICATION_NUMBER = 'nationalIdentificationNumber'
      NATIONALITY = 'nationality'
      ORGANISATION_NAME = 'organisationName'
      ORGANISATION_TYPE = 'organisationType'
      PHONE = 'phone'
      SPARE_EMAIL = 'spareEmail'
      VAT = 'vat'

      def self.all
        @all ||= [
          ADDRESS_CITY,
          ADDRESS_COUNTRY,
          ADDRESS_LINE1,
          ADDRESS_LINE2,
          ADDRESS_LINE3,
          ADDRESS_OTHER_DETAILS,
          ADDRESS_PROVINCE,
          ADDRESS_ZIP,
          BIRTH_CITY,
          BIRTH_COUNTRY,
          BIRTH_DAY,
          BIRTH_ZIP,
          CELL_PHONE,
          COMPANY_NATIONAL_IDENTIFICATION_NUMBER,
          EMAIL,
          FAX,
          FIRST_NAME,
          GENDER,
          LANGUAGE,
          LAST_NAME,
          LEGAL_FORM,
          NATIONAL_IDENTIFICATION_NUMBER,
          NATIONALITY,
          ORGANISATION_NAME,
          ORGANISATION_TYPE,
          PHONE,
          SPARE_EMAIL,
          VAT,
        ].freeze
      end

      def self.valid?(value)
        all.include?(value)
      end
    end
  end
end
