# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    module XdslXdslModemConfigFrequencyEnum
      N2_4_GHZ = '2.4GHz'
      N5_GHZ = '5GHz'

      def self.all
        @all ||= [
          N2_4_GHZ,
          N5_GHZ,
        ].freeze
      end

      def self.valid?(value)
        all.include?(value)
      end
    end
  end
end
