# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    class XdslMonitoringNotificationsPost
      include Ovh::Api::Serializable
      include Ovh::Api::Validations

      attribute :allow_incident,
        type: 'Boolean',
        json_key: 'allowIncident',
        required: false

      attribute :down_threshold,
        type: 'Integer',
        json_key: 'downThreshold',
        required: false

      attribute :email,
        type: 'String',
        json_key: 'email',
        required: false

      attribute :frequency,
        type: 'XdslMonitoringNotificationsFrequencyEnum',
        json_key: 'frequency',
        required: true

      attribute :phone,
        type: 'String',
        json_key: 'phone',
        required: false

      attribute :sms_account,
        type: 'String',
        json_key: 'smsAccount',
        required: false

      attribute :type,
        type: 'XdslMonitoringNotificationsTypeEnum',
        json_key: 'type',
        required: true

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
