# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    class XdslTemplateModemLAN
      include Ovh::Api::Serializable
      include Ovh::Api::Validations

      attribute :ip_address,
        type: 'String',
        json_key: 'IPAddress',
        required: false

      attribute :addressing_type,
        type: 'XdslXdslModemConfigAddressingTypeEnum',
        json_key: 'addressingType',
        required: false

      attribute :lan_name,
        type: 'String',
        json_key: 'lanName',
        required: false

      attribute :subnet_mask,
        type: 'String',
        json_key: 'subnetMask',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
