# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    module XdslXdslModemConfigEasyFirewallLevelEnum
      BLOCK_ALL = 'BlockAll'
      DISABLED = 'Disabled'
      NORMAL = 'Normal'

      def self.all
        @all ||= [
          BLOCK_ALL,
          DISABLED,
          NORMAL,
        ].freeze
      end

      def self.valid?(value)
        all.include?(value)
      end
    end
  end
end
