# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    module XdslResiliationReasonEnum
      ADDRESS_MOVE = 'addressMove'
      BILLING_PROBLEMS = 'billingProblems'
      CESSATION_OF_ACTIVITY = 'cessationOfActivity'
      CHANGE_OF_TERMS = 'changeOfTerms'
      FTTH = 'ftth'
      GO_TO_COMPETITOR = 'goToCompetitor'
      OTHER = 'other'
      TECHNICAL_PROBLEMS = 'technicalProblems'

      def self.all
        @all ||= [
          ADDRESS_MOVE,
          BILLING_PROBLEMS,
          CESSATION_OF_ACTIVITY,
          CHANGE_OF_TERMS,
          FTTH,
          GO_TO_COMPETITOR,
          OTHER,
          TECHNICAL_PROBLEMS,
        ].freeze
      end

      def self.valid?(value)
        all.include?(value)
      end
    end
  end
end
