# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    module XdslMonitoringNotificationsFrequencyEnum
      N1H = '1h'
      N5M = '5m'
      N6H = '6h'
      ONCE = 'once'

      def self.all
        @all ||= [
          N1H,
          N5M,
          N6H,
          ONCE,
        ].freeze
      end

      def self.valid?(value)
        all.include?(value)
      end
    end
  end
end
