# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    class XdslAddressDetail
      include Ovh::Api::Serializable
      include Ovh::Api::Validations

      attribute :building,
        type: 'String',
        json_key: 'building',
        required: false

      attribute :city,
        type: 'String',
        json_key: 'city',
        required: false

      attribute :door,
        type: 'String',
        json_key: 'door',
        required: false

      attribute :first_name,
        type: 'String',
        json_key: 'firstName',
        required: false

      attribute :floor,
        type: 'String',
        json_key: 'floor',
        required: false

      attribute :insee_code,
        type: 'String',
        json_key: 'inseeCode',
        required: false

      attribute :last_name,
        type: 'String',
        json_key: 'lastName',
        required: false

      attribute :number_street,
        type: 'String',
        json_key: 'numberStreet',
        required: false

      attribute :residence,
        type: 'String',
        json_key: 'residence',
        required: false

      attribute :rivoli_code,
        type: 'String',
        json_key: 'rivoliCode',
        required: false

      attribute :stairs,
        type: 'String',
        json_key: 'stairs',
        required: false

      attribute :street,
        type: 'String',
        json_key: 'street',
        required: false

      attribute :zip_code,
        type: 'String',
        json_key: 'zipCode',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
