# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    class XdslLineDiagnosticAnswers
      include Ovh::Api::Serializable
      include Ovh::Api::Validations

      attribute :bandwidth_test_unit,
        type: 'XdslLineDiagnosticBandwidthTestUnitEnum',
        json_key: 'bandwidthTestUnit',
        required: false

      attribute :comment,
        type: 'String',
        json_key: 'comment',
        required: false

      attribute :conditions_accepted,
        type: 'Boolean',
        json_key: 'conditionsAccepted',
        required: false

      attribute :contact_phone,
        type: 'String',
        json_key: 'contactPhone',
        required: false

      attribute :datetime_of_appearance,
        type: 'Time',
        json_key: 'datetimeOfAppearance',
        required: false

      attribute :download_bandwidth_test,
        type: 'Integer',
        json_key: 'downloadBandwidthTest',
        required: false

      attribute :end_afternoon_hours,
        type: 'String',
        json_key: 'endAfternoonHours',
        required: false

      attribute :end_morning_hours,
        type: 'String',
        json_key: 'endMorningHours',
        required: false

      attribute :follow_by_sms,
        type: 'Boolean',
        json_key: 'followBySms',
        required: false

      attribute :has_modem_kept_synchronization,
        type: 'Boolean',
        json_key: 'hasModemKeptSynchronization',
        required: false

      attribute :id_appointment,
        type: 'Integer',
        json_key: 'idAppointment',
        required: false

      attribute :individual_site,
        type: 'Boolean',
        json_key: 'individualSite',
        required: false

      attribute :modem_is_synchronized,
        type: 'Boolean',
        json_key: 'modemIsSynchronized',
        required: false

      attribute :modem_mac,
        type: 'String',
        json_key: 'modemMac',
        required: false

      attribute :modem_still_synchronized,
        type: 'Boolean',
        json_key: 'modemStillSynchronized',
        required: false

      attribute :modem_type,
        type: 'String',
        json_key: 'modemType',
        required: false

      attribute :ovh_ticket,
        type: 'String',
        json_key: 'ovhTicket',
        required: false

      attribute :problem_type,
        type: 'XdslLineDiagnosticProblemTypeEnum',
        json_key: 'problemType',
        required: false

      attribute :resolved_after_tests,
        type: 'Boolean',
        json_key: 'resolvedAfterTests',
        required: false

      attribute :secure_site,
        type: 'Boolean',
        json_key: 'secureSite',
        required: false

      attribute :several_internet_connections,
        type: 'Boolean',
        json_key: 'severalInternetConnections',
        required: false

      attribute :site_closed_days,
        type: 'String',
        json_key: 'siteClosedDays',
        required: false

      attribute :site_digicode,
        type: 'String',
        json_key: 'siteDigicode',
        required: false

      attribute :site_opening,
        type: 'String',
        json_key: 'siteOpening',
        required: false

      attribute :start_afternoon_hours,
        type: 'String',
        json_key: 'startAfternoonHours',
        required: false

      attribute :start_morning_hours,
        type: 'String',
        json_key: 'startMorningHours',
        required: false

      attribute :upload_bandwidth_test,
        type: 'Integer',
        json_key: 'uploadBandwidthTest',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
