# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    class XdslTemplateModem
      include Ovh::Api::Serializable
      include Ovh::Api::Validations

      attribute :dhcp,
        type: 'Array<XdslTemplateModemDHCP>',
        json_key: 'DHCP',
        required: false

      attribute :lan,
        type: 'Array<XdslTemplateModemLAN>',
        json_key: 'LAN',
        required: false

      attribute :wlan,
        type: 'Array<XdslTemplateModemWLAN>',
        json_key: 'WLAN',
        required: false

      attribute :capabilities,
        type: 'String',
        json_key: 'capabilities',
        required: false

      attribute :creation_date,
        type: 'Time',
        json_key: 'creationDate',
        required: false

      attribute :dmz_ip,
        type: 'String',
        json_key: 'dmzIP',
        required: false

      attribute :mtu_size,
        type: 'XdslXdslModemConfigMTUSizeEnum',
        json_key: 'mtuSize',
        required: false

      attribute :name,
        type: 'String',
        json_key: 'name',
        required: false

      attribute :parameters_to_ignore,
        type: 'XdslTemplateModemParametersToIgnore',
        json_key: 'parametersToIgnore',
        required: false

      attribute :port_mapping,
        type: 'Array<XdslTemplateModemPortMapping>',
        json_key: 'portMapping',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
