# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    class XdslAccess
      include Ovh::Api::Serializable
      include Ovh::Api::Validations

      attribute :access_name,
        type: 'String',
        json_key: 'accessName',
        required: false

      attribute :access_type,
        type: 'XdslDslTypeEnum',
        json_key: 'accessType',
        required: false

      attribute :address,
        type: 'XdslAddressDetail',
        json_key: 'address',
        required: false

      attribute :capabilities,
        type: 'XdslAccessCapabilities',
        json_key: 'capabilities',
        required: false

      attribute :description,
        type: 'String',
        json_key: 'description',
        required: false

      attribute :ipv6_enabled,
        type: 'Boolean',
        json_key: 'ipv6Enabled',
        required: false

      attribute :lns_rate_limit,
        type: 'Integer',
        json_key: 'lnsRateLimit',
        required: false

      attribute :mail_sending,
        type: 'XdslMailSendingAccessStatusEnum',
        json_key: 'mailSending',
        required: false

      attribute :modem_profile,
        type: 'XdslModemConnectionProfileEnum',
        json_key: 'modemProfile',
        required: false

      attribute :monitoring,
        type: 'Boolean',
        json_key: 'monitoring',
        required: false

      attribute :mttr,
        type: 'XdslGtrEnum',
        json_key: 'mttr',
        required: false

      attribute :nra,
        type: 'String',
        json_key: 'nra',
        required: false

      attribute :pack_name,
        type: 'String',
        json_key: 'packName',
        required: false

      attribute :pairs_number,
        type: 'Integer',
        json_key: 'pairsNumber',
        required: false

      attribute :provider,
        type: 'XdslProviderEnum',
        json_key: 'provider',
        required: false

      attribute :provider_infra,
        type: 'String',
        json_key: 'providerInfra',
        required: false

      attribute :role,
        type: 'XdslAccessRoleEnum',
        json_key: 'role',
        required: false

      attribute :status,
        type: 'XdslAccessStatusEnum',
        json_key: 'status',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
