# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    module XdslXdslModemConfigSecurityTypeEnum
      NONE = 'None'
      WEP = 'WEP'
      WPA = 'WPA'
      WPA2 = 'WPA2'
      WPA2AND_WPA3 = 'WPA2andWPA3'
      WPA3 = 'WPA3'
      WP_AAND_WPA2 = 'WPAandWPA2'

      def self.all
        @all ||= [
          NONE,
          WEP,
          WPA,
          WPA2,
          WPA2AND_WPA3,
          WPA3,
          WP_AAND_WPA2,
        ].freeze
      end

      def self.valid?(value)
        all.include?(value)
      end
    end
  end
end
