# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    module XdslLineDiagnosticProblemTypeEnum
      LOW_BANDWIDTH = 'lowBandwidth'
      SYNC_LOSS = 'syncLoss'

      def self.all
        @all ||= [
          LOW_BANDWIDTH,
          SYNC_LOSS,
        ].freeze
      end

      def self.valid?(value)
        all.include?(value)
      end
    end
  end
end
