# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    class XdslModemPortMappingsPost
      include Ovh::Api::Serializable
      include Ovh::Api::Validations

      attribute :allowed_remote_ip,
        type: 'String',
        json_key: 'allowedRemoteIp',
        required: false

      attribute :description,
        type: 'String',
        json_key: 'description',
        required: false

      attribute :external_port_end,
        type: 'Integer',
        json_key: 'externalPortEnd',
        required: false

      attribute :external_port_start,
        type: 'Integer',
        json_key: 'externalPortStart',
        required: true

      attribute :internal_client,
        type: 'String',
        json_key: 'internalClient',
        required: true

      attribute :internal_port,
        type: 'Integer',
        json_key: 'internalPort',
        required: true

      attribute :internal_port_end,
        type: 'Integer',
        json_key: 'internalPortEnd',
        required: false

      attribute :name,
        type: 'String',
        json_key: 'name',
        required: true

      attribute :protocol,
        type: 'XdslXdslModemConfigProtocolTypeEnum',
        json_key: 'protocol',
        required: true

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
