# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    class XdslEligibilityMeetingSlot
      include Ovh::Api::Serializable
      include Ovh::Api::Validations

      attribute :end_date,
        type: 'Time',
        json_key: 'endDate',
        required: false

      attribute :slot_id,
        type: 'String',
        json_key: 'slotId',
        required: false

      attribute :start_date,
        type: 'Time',
        json_key: 'startDate',
        required: false

      attribute :ui_code,
        type: 'String',
        json_key: 'uiCode',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
