# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    class XdslAccessCapabilities
      include Ovh::Api::Serializable
      include Ovh::Api::Validations

      attribute :can_apply_lns_rate_limit,
        type: 'Boolean',
        json_key: 'canApplyLnsRateLimit',
        required: false

      attribute :can_change_dslam_profile,
        type: 'Boolean',
        json_key: 'canChangeDslamProfile',
        required: false

      attribute :can_change_lns,
        type: 'Boolean',
        json_key: 'canChangeLns',
        required: false

      attribute :can_get_radius_connection_logs,
        type: 'Boolean',
        json_key: 'canGetRadiusConnectionLogs',
        required: false

      attribute :can_reset_dslam_port,
        type: 'Boolean',
        json_key: 'canResetDslamPort',
        required: false

      attribute :has_dslam_port,
        type: 'Boolean',
        json_key: 'hasDslamPort',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
