# frozen_string_literal: true

# OVH API
#
# The version of the OpenAPI document: 1.0
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Ovh::Api
  module Models
    class XdslModem
      include Ovh::Api::Serializable
      include Ovh::Api::Validations

      attribute :acs_backend,
        type: 'XdslXdslModemConfigACSBackendEnum',
        json_key: 'acsBackend',
        required: false

      attribute :acs_version,
        type: 'String',
        json_key: 'acsVersion',
        required: false

      attribute :brand_name,
        type: 'String',
        json_key: 'brandName',
        required: false

      attribute :capabilities,
        type: 'XdslModemCapabilities',
        json_key: 'capabilities',
        required: false

      attribute :dmz_ip,
        type: 'String',
        json_key: 'dmzIP',
        required: false

      attribute :easy_firewall_level,
        type: 'XdslXdslModemConfigEasyFirewallLevelEnum',
        json_key: 'easyFirewallLevel',
        required: false

      attribute :ipv6_support,
        type: 'Boolean',
        json_key: 'ipv6Support',
        required: false

      attribute :is_bridged,
        type: 'Boolean',
        json_key: 'isBridged',
        required: false

      attribute :last_cwmp_request_date,
        type: 'Time',
        json_key: 'lastCwmpRequestDate',
        required: false

      attribute :mac_address,
        type: 'String',
        json_key: 'macAddress',
        required: false

      attribute :managed_by_ovh,
        type: 'Boolean',
        json_key: 'managedByOvh',
        required: false

      attribute :model,
        type: 'String',
        json_key: 'model',
        required: false

      attribute :mtu_size,
        type: 'XdslXdslModemConfigMTUSizeEnum',
        json_key: 'mtuSize',
        required: false

      attribute :serial_number,
        type: 'String',
        json_key: 'serialNumber',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
